"""Additional Top 6 Law Practice Candidates for Maximum Pipeline Depth"""

ADDITIONAL_CANDIDATES = [
    # FLORIDA
    ("FL", "Wites & Rogers, PLLC", "witeslaw.com", "Marc A. Wites", "Property Insurance & Real Estate Litigation", 4, "/contact/"),
    ("FL", "The Leach Firm, P.A.", "theleachfirm.com", "Carlos Leach", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("FL", "Kula & Associates, P.A.", "kula-law.com", "Elliot Kula", "Appellate & Complex Real Estate Law", 4, "/contact/"),
    ("FL", "Fischer & Feldman, P.A.", "fischerfeldman.com", "David Fischer", "Probate, Estate & Civil Litigation", 3, "/contact/"),
    ("FL", "Gold & Parado, P.A.", "goldparado.com", "Alan Gold", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("FL", "Koss Law Firm, P.A.", "kosslawfirm.com", "Donald Koss", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("FL", "ZinnLaw, PLLC", "zinnlaw.com", "Brian Zinn", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Law Offices of Larry E. Schner, P.A.", "schnerlaw.com", "Larry E. Schner", "Real Estate, HOA & Foreclosure", 2, "/contact/"),
    ("FL", "The Law Office of Robert B. Cook, P.A.", "cooklawoffice.com", "Robert B. Cook", "Real Estate & Estate Planning", 3, "/contact/"),
    ("FL", "Hough Law Firm, P.A.", "houghlaw.com", "David Hough", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("FL", "The Arcia Law Firm, P.M.", "arcialawfirm.com", "Omar Arcia", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("FL", "Babbitt, Johnson, Osborne & LeClainche", "babbitt-johnson.com", "Joseph Johnson", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Searcy Denney (Tallahassee)", "searcylaw.com", "Brian Denney", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "RumbergerKirk (Miami)", "rumberger.com", "Scott Sarason", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("FL", "GrayRobinson (Tampa)", "gray-robinson.com", "Richard M. Blau", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),

    # TEXAS
    ("TX", "Chappell, Lanehart & Stangl, P.C.", "cls-law.com", "Dan Chappell", "Civil Trial & Real Estate Litigation", 4, "/contact/"),
    ("TX", "Whittenburg Law Firm", "whittenburglaw.com", "George Whittenburg", "Civil Litigation & Property Claims", 4, "/contact/"),
    ("TX", "Gibson, Ochsner & Adkins, L.L.P.", "gibsonlaw.com", "Tom Ochsner", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Kemp Smith LLP", "kempsmith.com", "Ken Slavin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Mounce, Green, Myers, Safi, Paxson & Galatzan, P.C.", "mgmsg.com", "Bruce Safi", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("TX", "Ray, McChristian & Jeans, P.C.", "rmjfirm.com", "Jeff Ray", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Guevara & Reeb, PLLC", "guevarareeb.com", "Hector Guevara", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TX", "Davis, Cedillo & Mendoza, Inc.", "dcmf.com", "Ricardo Cedillo", "Complex Commercial & Real Estate Trial", 4, "/contact/"),
    ("TX", "Goode Casseb Jones Riklin Choate & Watson, P.C.", "goodelaw.com", "Richard Riklin", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TX", "Brock Person Guerra Reyna, P.C.", "brockperson.com", "Roy Brock", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Ball & Weed, P.C.", "ballweed.com", "Gerald Weed", "Civil Litigation & Property Law", 4, "/contact/"),
    ("TX", "Groce, Locke & Hebdon / Cox Smith (TX)", "dykema.com", "David Groce", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("TX", "Matthews, Branscomb, Pool & Drake / Cox Smith", "dykema.com", "Richard Matthews", "Real Estate, Oil & Gas Litigation", 4, "/contact/"),
    ("TX", "Kleberg & Head, P.C. / Welder Leshin LLP", "welderleshin.com", "Leo Welder", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Porter, Rogers, Dahlman & Gordon, P.C.", "prdg.com", "Charles Gordon", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("TX", "Wood, Boykin & Wolter, P.C.", "woodboykin.com", "Rick Wolter", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TX", "Chaves, Gonzales & Hoblit L.L.P.", "cghlaw.com", "Tony Chaves", "Civil Trial & Real Estate Defense", 4, "/contact/"),
    ("TX", "Donato, Minx, Brown & Pool, P.C.", "donatominxbrown.com", "Robert Donato", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Lorance & Thompson, P.C.", "lorancethompson.com", "Wayne Thompson", "Civil Litigation & Property Defense", 4, "/contact/"),
    ("TX", "Ramey, Chandler, Quinn & Evans, P.C.", "rameychandler.com", "William Evans", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Harlan Law Firm, P.C.", "harlanlawpc.com", "Mark Harlan", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("TX", "Gillespie & Rozen, P.C.", "laborlawtx.com", "Hal Gillespie", "Civil Trial Practice", 4, "/contact/"),
    ("TX", "The Law Offices of Richard Cahan", "cahanlaw.com", "Richard Cahan", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("TX", "Law Office of J. Kevin Clark P.C.", "fortworthdivorcelawyer.com", "Kevin Clark", "Asset Division & Probate Litigation", 3, "/contact/"),
    ("TX", "The Law Office of Robert E. Luedke", "luedkelaw.com", "Robert Luedke", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Weaver Law Firm (The Woodlands)", "weaverlawyers.com", "Richard Weaver", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),

    # CALIFORNIA
    ("CA", "Gurnee Mason Rushford Bonotto & Forestiere LLP", "gurneelaw.com", "Steven Gurnee", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("CA", "Boutin Jones Inc.", "boutinjones.com", "Stephen F. Boutin", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("CA", "Murphy Austin Easton, LLP", "murphyaustin.com", "Lisa Austin", "Real Estate, Construction & Probate", 3, "/contact/"),
    ("CA", "Wilke Fleury LLP", "wilkefleury.com", "Steven J. Fass", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("CA", "Somach Simmons & Dunn", "somachlaw.com", "Stuart L. Somach", "Water Rights, Real Estate & Environmental", 4, "/contact/"),
    ("CA", "Trainor Fairbrook", "trainorfairbrook.com", "Charles W. Trainor", "Commercial Real Estate Litigation & Title", 1, "/contact/"),
    ("CA", "Diepenbrock Elkin Dauer McCandless LLP", "diepenbrock.com", "Mark D. McCandless", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("CA", "Wagner Kirkman Blaine Klomparens & Youmans LLP", "wkbk.com", "Douglas L. Youmans", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("CA", "Cook Brown LLP", "cookbrown.com", "Ronald Cook", "Commercial Trial Practice", 4, "/contact/"),
    ("CA", "Mastagni Holstedt, A.P.C.", "mastagni.com", "David E. Mastagni", "Civil Trial & Asset Protection", 4, "/contact/"),
    ("CA", "Kershaw, Cook & Talley PC", "kctlegal.com", "William A. Kershaw", "Complex Civil Litigation", 4, "/contact/"),
    ("CA", "Dreyer Babich Buccola Wood Campora, LLP", "dbbwc.com", "Joseph J. Babich", "Trial Practice & Asset Recovery", 4, "/contact/"),
    ("CA", "Freeman Firm", "freemanfirm.com", "Lee C. Rosenthal", "Real Estate, Agriculture & Probate", 3, "/contact/"),
    ("CA", "Shore, McKinley, Conger & Jolley, LLP", "smcjlendinglaw.com", "John McKinley", "Banking, Real Estate & Creditors Rights", 1, "/contact/"),
    ("CA", "Herum Crabtree Suntag", "herumcrabtree.com", "Steven A. Herum", "Real Estate Litigation & Eminent Domain", 1, "/contact/"),
    ("CA", "Hanson Law Firm", "hansonlawfirm.com", "John Hanson", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("CA", "Law Offices of Michael G. Doan", "doanlaw.com", "Michael G. Doan", "Foreclosure Defense & Consumer Law", 2, "/contact/"),
    ("CA", "The Law Offices of Larry D. Simons", "larrysimonslaw.com", "Larry Simons", "Foreclosure Defense & Bankruptcy", 2, "/contact/"),
    ("CA", "Law Offices of Nicholas Gebelt", "gebeltlaw.com", "Nicholas Gebelt", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("CA", "The Law Offices of Daniela Romero", "romerolaw.com", "Daniela Romero", "Foreclosure Defense & Debt Recovery", 2, "/contact/"),

    # GEORGIA
    ("GA", "Andersen, Tate & Carr, P.C.", "atclawfirm.com", "Thomas T. Tate", "Real Estate Litigation & Eminent Domain", 1, "/contact/"),
    ("GA", "Chandler, Britt & Jay, LLC", "cbjlawfirm.com", "Walter Chandler", "Real Estate, Land Use & Litigation", 4, "/contact/"),
    ("GA", "Mahaffey Pickens Tucker, LLP", "mptlawfirm.com", "Steven A. Pickens", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("GA", "Fox, Chandler, Homans, Hicks & McKinnon, LLP", "foxchandler.com", "David A. Fox", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Stewart, Melvin & Frost, LLP", "smf-law.com", "J. Douglas Stewart", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("GA", "Hulsey, Oliver & Mahar, LLP", "homlaw.com", "Thomas Mahar", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("GA", "Whelchel, Dunlap, Jarrard & Walker, LLP", "wdjwlaw.com", "Thomas Walker", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("GA", "Lawson and Berry", "lawsonandberry.com", "Richard Lawson", "Civil Litigation & Trial Defense", 4, "/contact/"),
    ("GA", "Moore, Clarke, DuVall & Rodgers, P.C.", "mcdr-law.com", "Kimberly Clarke", "Real Estate, Banking & Creditors Rights", 1, "/contact/"),
    ("GA", "Watson Spence LLP", "watsonspence.com", "Mark Watson", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Langdale Vallotton, LLP", "langdalelaw.com", "William P. Langdale", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Coleman Talley LLP", "colemantalley.com", "Justin Scott", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Tillman & Tillman", "tillmanlaw.com", "Wallace Tillman", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("GA", "Young, Thagard, Hoffmann, Smith, Lawrence & Shenton, LLP", "youngthagard.com", "F. Thomas Young", "Civil Trial Practice & Real Estate", 4, "/contact/"),
    ("GA", "Glover & Davis, P.A.", "gloverdavis.com", "J. Littleton Glover", "Real Estate, Probate & Trial Law", 3, "/contact/"),

    # NORTH CAROLINA
    ("NC", "Poyner Spruill LLP (Rocky Mount)", "poynerspruill.com", "David Dreifus", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Battle, Winslow, Scott & Wiley, P.A.", "battlewinslow.com", "J. Brian Scott", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("NC", "Ward and Smith, P.A. (New Bern)", "wardandsmith.com", "Ken Wooten", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("NC", "Sumrell Sugg, P.A.", "sumrellsugg.com", "James R. Sugg", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("NC", "Howard & Stallings (New Bern)", "hsfad.com", "Robert Stallings", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "White & Allen, P.A.", "whiteandallen.com", "C. Gray Johnsey", "Real Estate, Probate, Tax & Title Law", 3, "/contact/"),
    ("NC", "Taft, Taft & Haigler, P.A.", "taftlawfirm.com", "Thomas F. Taft", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Hardee, Massey & Blount, LLP", "hardeemasseylaw.com", "Charles Hardee", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("NC", "Teague, Rotenstreich, Stanaland, Fox & Freiberg, LLP", "trslaw.com", "Paul Rotenstreich", "Civil Trial & Property Defense", 4, "/contact/"),
    ("NC", "Hill Evans Jordan & Beatty, PLLC", "hejb.com", "Karl N. Hill", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("NC", "Carruthers & Roth, P.A. (Greensboro)", "crlaw.com", "June L. Basden", "Banking, Real Estate & Creditors Rights", 1, "/contact/"),
    ("NC", "Sharpless & Stavola, P.A.", "sharpless-stavola.com", "Frederick K. Sharpless", "Civil Trial & Real Estate Litigation", 4, "/contact/"),
    ("NC", "Forman Rossabi Black, P.A.", "frb-law.com", "Amiel J. Rossabi", "Real Estate Litigation & HOA Practice", 2, "/contact/"),
    ("NC", "Henson & Talley LLP", "hensontalley.com", "Perry C. Henson", "Civil Litigation & Trial Defense", 4, "/contact/"),
    ("NC", "Adams, Howell, Sizemore & Lenfestey, P.A.", "adamshowell.com", "Douglas Howell", "Real Estate, Title Clearance & Foreclosure", 1, "/contact/"),

    # TENNESSEE
    ("TN", "Farris Bobango PLC (Nashville)", "farrisbobango.com", "John Bobango", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Ortale Kelley Herbert & Crawford (Nashville)", "ortalekelley.com", "Daniel Herbert", "Real Estate Litigation & Commercial Law", 4, "/contact/"),
    ("TN", "Tune, Entrekin & White, P.C.", "tewlaw.com", "Peter White", "Real Estate, Eminent Domain & Land Use", 1, "/contact/"),
    ("TN", "Thompson Burton PLLC", "thompsonburton.com", "Walt Burton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Story, Abernathy & Campbell", "storyabernathy.com", "David Story", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "Hailey, McNamara, Hall, Larmann & Papale, LLP (TN)", "haileymcnamara.com", "Richard Hall", "Civil Trial Practice & Property Law", 4, "/contact/"),
    ("TN", "Leitner, Williams, Dooley & Napolitan, PLLC (Knoxville)", "leitnerfirm.com", "Paul Leitner", "Civil Trial & Property Defense", 4, "/contact/"),
    ("TN", "Kennerly, Montgomery & Finley, P.C. (Knoxville)", "kmfpc.com", "Robert Montgomery", "Real Estate Litigation & Tax Law", 1, "/contact/"),
    ("TN", "Spicer Rudstrom, PLLC (Chattanooga)", "spicerfirm.com", "Marc Dedman", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("TN", "Duncan, Hatcher, Fleenor & Culpepper, P.C.", "dhf-law.com", "Phillip Fleenor", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Cavin & O'Herren", "cavinoherren.com", "David Cavin", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Baker, Donelson (Chattanooga)", "bakerdonelson.com", "Russell W. Gray", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Miller & Martin (Chattanooga)", "millermartin.com", "James M. Haley", "Real Estate, Banking & Creditors Rights", 1, "/contact/"),
    ("TN", "Chambliss, Bahner & Stophel (Chattanooga)", "chamblisslaw.com", "Dana B. Perry", "Probate, Elder Law & Estate Litigation", 3, "/contact/"),
    ("TN", "Grant, Konvalinka & Harrison, P.C.", "gkhpc.com", "John R. Anderson", "Real Estate Litigation, Tax & Probate", 1, "/contact/"),
]

print(f"Loaded {len(ADDITIONAL_CANDIDATES)} additional Top 6 candidate practices.")
