"""California Law Firm Pipeline Candidates"""

CANDIDATES = [
    # Los Angeles & Southern California
    ("CA", "Farella Braun + Martel LLP", "fbm.com", "Douglas R. Young", "Real Estate Litigation & Dispute Resolution", 1, "/contact/"),
    ("CA", "Hanson Bridgett LLP", "hansonbridgett.com", "Andrew G. Giacomini", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Coblentz Patch Duffy & Bass LLP", "coblentzlaw.com", "Richard R. Patch", "Real Estate Litigation & Land Disputes", 1, "/contact/"),
    ("CA", "Shartsis Friese LLP", "sflaw.com", "Arthur J. Shartsis", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Allen Matkins Leck Gamble Mallory & Natsis LLP", "allenmatkins.com", "David L. Osias", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("CA", "Cox, Castle & Nicholson LLP", "coxcastle.com", "Mario Camara", "Real Estate Litigation & Distressed Property", 1, "/contact/"),
    ("CA", "Buchalter", "buchalter.com", "Adam Bass", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Best Best & Krieger LLP", "bbklaw.com", "Eric L. Garner", "Real Estate, Eminent Domain & Municipal Law", 1, "/contact/"),
    ("CA", "Procopio, Cory, Hargreaves & Savitch LLP", "procopio.com", "John D. Alessio", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Higgs Fletcher & Mack LLP", "higgslaw.com", "Steven J. Cologne", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("CA", "Solomon Ward Seidenwurm & Smith, LLP", "swsslaw.com", "Michael D. Breslauer", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("CA", "Sullivan Hill Rez & Engel", "sullivanhill.com", "Robert E. Sullivan", "Insolvency, Real Estate & Construction", 1, "/contact/"),
    ("CA", "Klinedinst PC", "klinedinstlaw.com", "John D. Klinedinst", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("CA", "Duckor Metzger & Wynne, APLC", "dmwlaw.com", "Michael Duckor", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("CA", "Seltzer Caplan McMahon Vitek", "scmv.com", "Robert S. Caplan", "Real Estate Litigation & Estate Planning", 3, "/contact/"),
    ("CA", "Ferris & Britton, APC", "ferrisbritton.com", "Michael R. Weinstein", "Real Estate Litigation & Business Law", 4, "/contact/"),
    ("CA", "Rutan & Tucker, LLP", "rutan.com", "Michael D. Adams", "Real Estate Litigation & Land Use", 1, "/contact/"),
    ("CA", "Palmieri, Tyler, Wiener, Wilhelm & Waldron LLP", "ptwww.com", "Michael H. Leifer", "Real Estate Litigation & Eminent Domain", 1, "/contact/"),
    ("CA", "Stradling Yocca Carlson & Rauth", "sycr.com", "Larry A. Cerutti", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Greenberg Glusker Fields Claman & Machtinger LLP", "greenbergglusker.com", "Bob Baradaran", "Real Estate Litigation & Estate Planning", 3, "/contact/"),
    ("CA", "Jeffer Mangels Butler & Mitchell LLP", "jmbm.com", "Bruce P. Jeffer", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("CA", "Ervin Cohen & Jessup LLP", "ecjlaw.com", "Barry MacNaughton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Lewitt Hackman Shapiro Marshall & Harlan", "lewitthackman.com", "Keith T. Zimmet", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("CA", "Nemecek & Cole", "nemecek-cole.com", "Frank W. Nemecek", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("CA", "Stone & Sallus, LLP", "stonesalluslaw.com", "Jason Stone", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("CA", "Schorr Law, APC", "schorr-law.com", "Zachary Schorr", "Real Estate Litigation & Quiet Title", 1, "/contact/"),
    ("CA", "Kendall Law, APC", "kendalllaw.net", "Sunny Kendall", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("CA", "Newmeyer & Dillion LLP", "newmeyeranddillion.com", "Paul S. Bielaczyc", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("CA", "AlvaradoSmith, APC", "alvaradosmith.com", "Ruben A. Smith", "Real Estate Litigation & Public Agency", 4, "/contact/"),
    ("CA", "Snell & Wilmer L.L.P. (CA)", "swlaw.com", "Matthew P. Kanny", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Manatt, Phelps & Phillips, LLP (CA)", "manatt.com", "Donna L. Wilson", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Sheppard, Mullin, Richter & Hampton LLP (CA)", "sheppardmullin.com", "Luca Salvi", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("CA", "Luce, Forward, Hamilton & Scripps / Dentons (CA)", "dentons.com", "Charles A. Bird", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("CA", "Nossaman LLP", "nossaman.com", "George A. Joseph", "Real Estate, Eminent Domain & Land Use", 1, "/contact/"),
    ("CA", "Musick, Peeler & Garrett LLP", "musickpeeler.com", "R. Joseph De Briyn", "Real Estate Litigation & Estate Planning", 3, "/contact/"),
    ("CA", "Loeb & Loeb LLP (CA)", "loeb.com", "Kenneth R. Florin", "Real Estate Litigation & Trusts/Estates", 3, "/contact/"),
    ("CA", "Glaser Weil Fink Howard Jordan & Shapiro LLP", "glaserweil.com", "Peter M. Weil", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("CA", "Mitchell Silberberg & Knupp LLP", "msk.com", "Gregory P. Goeckner", "Real Estate Litigation & Trusts/Estates", 3, "/contact/"),
    ("CA", "Troop Meisinger Steuber & Pasich / Akin Gump (CA)", "akingump.com", "Kirk A. Pasich", "Commercial Trial & Property Recovery", 4, "/contact/"),
    ("CA", "Gibson, Dunn & Crutcher LLP (CA)", "gibsondunn.com", "Barbara L. Becker", "Real Estate Litigation & Commercial Law", 4, "/contact/"),
    ("CA", "O'Melveny & Myers LLP (CA)", "omm.com", "Bradley J. Butwin", "Real Estate Litigation & Distressed Debt", 1, "/contact/"),
    ("CA", "Paul Hastings LLP (CA)", "paulhastings.com", "Frank Lopez", "Real Estate Finance & Litigation", 1, "/contact/"),
    ("CA", "Latham & Watkins LLP (CA)", "lw.com", "Richard M. Trobman", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("CA", "Munger, Tolles & Olson LLP", "mto.com", "Hailyn J. Chen", "Real Estate & Commercial Trial Law", 4, "/contact/"),
    ("CA", "Irell & Manella LLP", "irell.com", "Jonathan H. Steinberg", "Complex Civil Trial & Property Law", 4, "/contact/"),
    ("CA", "Cox, Wootton, Lerner, Griffin & Hansen, LLP", "cwl-law.com", "Neil S. Lerner", "Civil Litigation & Maritime/Property", 4, "/contact/"),
    ("CA", "Murphy, Campbell, Alliston & Quinn", "murphycampbell.com", "George E. Murphy", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("CA", "Porter Scott", "porterscott.com", "Carl L. Fessenden", "Civil Litigation & Real Estate Law", 4, "/contact/"),
    ("CA", "Kroloff, Belcher, Smart, Perry & Christopherson", "kroloff.com", "Christopher Christopherson", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("CA", "Neumiller & Beardslee", "neumiller.com", "George A. Petrulakis", "Real Estate, Land Use & Water Law", 4, "/contact/"),
    ("CA", "Damrell, Nelson, Schrimp, Pallios & Silva", "damrell.com", "Frank C. Damrell", "Real Estate Litigation & Agriculture", 4, "/contact/"),
    ("CA", "McCormick, Barstow, Sheppard, Wayte & Carruth LLP", "mccormickbarstow.com", "David R. McNamara", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("CA", "Baker Manock & Jensen, PC", "bakermanock.com", "Dirk B. Paloutzian", "Real Estate, Water & Probate Law", 3, "/contact/"),
    ("CA", "Dowling Aaron Incorporated / Fennemore Dowling Aaron", "fennemorelaw.com", "Richard M. Aaron", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Sagaser, Watkins & Wieland PC", "sw2law.com", "Howard A. Sagaser", "Civil Trial & Commercial Litigation", 4, "/contact/"),
    ("CA", "Wanger Jones Helsley PC", "wjhattorneys.com", "Oliver W. Wanger", "Real Estate, Water & Commercial Trial", 4, "/contact/"),
    ("CA", "Borton Petrini, LLP", "bortonpetrini.com", "Mark A. Jones", "Real Estate, Foreclosure Defense & Probate", 2, "/contact/"),
    ("CA", "Clifford & Brown, P.C.", "clifford-brownlaw.com", "Patrick J. Osborn", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("CA", "Klein, DeNatale, Goldner (Bakersfield)", "kleinlaw.com", "David J. Cooper", "Real Estate Litigation & Tax Default", 1, "/contact/"),
    ("CA", "LeBeau-Thelen, LLP", "lebeauthelen.com", "Thomas A. Thelen", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("CA", "Young Wooldridge, LLP", "youngwooldridge.com", "Ernest A. Conant", "Real Estate, Water & Trial Practice", 4, "/contact/"),
    ("CA", "Harrigan, Ruff, Phelan & Spier, APC", "hrpslaw.com", "Joseph Phelan", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("CA", "Gresham Savage Nolan & Tilden, PC", "greshamsavage.com", "Mark A. Ostoich", "Real Estate, Land Use & Mining", 4, "/contact/"),
    ("CA", "Reid & Hellyer, APC", "rhlaw.com", "Michael G. Kerbs", "Insolvency, Real Estate & Creditors Rights", 1, "/contact/"),
    ("CA", "Varner & Brandt LLP", "varnerbrandt.com", "Bruce D. Varner", "Real Estate, Corporate & Probate", 3, "/contact/"),
    ("CA", "Stream Kim Hicks Wrage & Alfaro, PC", "streamkim.com", "Theodore K. Stream", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("CA", "Wagner Zemming Sutter LLP", "wzsfirm.com", "Michael Wagner", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "The Blue Law Group", "thebluelawgroup.com", "Michael Blue", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("CA", "Holstrom, Block & Parke, APLC", "hbplaw.com", "Dayn Holstrom", "Estate Planning, Probate & Asset Division", 3, "/contact/"),
    ("CA", "CunninghamLegal", "cunninghamlegal.com", "James L. Cunningham", "Probate, Trust Administration & Real Estate", 3, "/contact/"),
    ("CA", "Barash & Silverman, APC", "barashlaw.com", "David Barash", "Foreclosure Defense & Real Estate Law", 2, "/contact/"),
    ("CA", "Law Offices of Michael D. Kwasigroch", "kwaslaw.com", "Michael Kwasigroch", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("CA", "Law Offices of Vincent D. Webb", "vincentwebblaw.com", "Vincent Webb", "Foreclosure Defense & Property Law", 2, "/contact/"),
    ("CA", "The Mellor Law Firm, APLC", "mellorlawfirm.com", "Mark Mellor", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("CA", "Law Offices of Stephen R. Wade", "stephenwadelaw.com", "Stephen R. Wade", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("CA", "Talamantes Associates, PC", "talamanteslaw.com", "Laura Talamantes", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("CA", "Law Office of Peter M. Hartley", "hartleylaw.com", "Peter Hartley", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("CA", "The Sterling Law Group", "sterlinglawgroup.net", "Michael Sterling", "Probate & Estate Administration", 3, "/contact/"),
    ("CA", "Giammichele Law, APC", "giammichelelaw.com", "Michael Giammichele", "Estate Planning & Probate Litigation", 3, "/contact/"),
    ("CA", "Modern Wealth Law, APLC", "modernwealthlaw.com", "John Wong", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("CA", "The Legacy Lawyers, P.C.", "thelegacylawyers.com", "Philip J. Kavesh", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("CA", "Crockett & Ante, APC", "crockett-law.com", "David Crockett", "Real Estate, Probate & Trust Litigation", 3, "/contact/"),
    ("CA", "The Heritage Law Group", "theheritagelawgroup.com", "Douglas B. Jacobs", "Probate, Estate Planning & Real Estate", 3, "/contact/"),
    ("CA", "Law Offices of James F. Roberts & Associates, APC", "webuildyourtrust.com", "James F. Roberts", "Probate & Trust Administration", 3, "/contact/"),
    ("CA", "Magee & Adler, APC", "mageeadler.com", "Eric Adler", "Probate, Trust & Conservatorship Law", 3, "/contact/"),
    ("CA", "Kehr Law, APC", "kehrlaw.com", "Brian Kehr", "Real Estate, Corporate & Probate Law", 3, "/contact/"),
    ("CA", "Law Office of Scott C. Soady, A.P.C.", "soadylaw.com", "Scott C. Soady", "Estate Planning & Asset Recovery", 3, "/contact/"),
    ("CA", "Antonyan Miranda, LLP", "expertdivorce.com", "Ilona Antonyan", "Complex Asset Division & Real Estate", 4, "/contact/"),
    ("CA", "Shustak Reynolds & Partners, P.C.", "shustak.com", "Erwin J. Shustak", "Commercial Trial & Asset Disputes", 4, "/contact/"),
    ("CA", "The McClellan Law Firm", "mcclellanlaw.com", "Craig R. McClellan", "Civil Trial & Complex Recovery", 4, "/contact/"),
    ("CA", "CaseyGerry", "caseygerry.com", "David S. Casey", "Civil Trial Practice & Property Law", 4, "/contact/"),
    ("CA", "Thorsnes Bartolotta McGuire LLP", "tbmlawyers.com", "Vincent J. Bartolotta", "Eminent Domain, Real Estate & Trial Law", 1, "/contact/"),
    ("CA", "Gomez Trial Attorneys", "thegomezfirm.com", "John H. Gomez", "Civil Trial & Complex Recovery", 4, "/contact/"),
    ("CA", "Hinch Newman LLP (CA)", "hinchnewman.com", "Richard Newman", "Civil Litigation & Commercial Practice", 4, "/contact/"),
    ("CA", "Bohm Wildish & Matsen, LLP", "bohmwildish.com", "James G. Bohm", "Real Estate Litigation, Probate & Estate", 3, "/contact/"),
    ("CA", "Brown & Streza LLP", "brownandstreza.com", "Matthew S. Brown", "Estate Planning, Tax & Real Estate", 3, "/contact/"),
    ("CA", "Rishwain & Rishwain", "rishwainlaw.com", "Brian Rishwain", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("CA", "Freeman, Freeman & Smiley, LLP", "ffslaw.com", "Bradley D. Smiley", "Real Estate, Trusts & Estates", 3, "/contact/"),
    ("CA", "Glaser Weil LLP (Century City)", "glaserweil.com", "Patricia L. Glaser", "Complex Trial & Real Estate Litigation", 4, "/contact/"),
    ("CA", "Bird, Marella, Boxer, Wolpert, Nessim, Drooks, Lincenberg & Rhow, P.C.", "birdmarella.com", "Terry W. Bird", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("CA", "Hueston Hennigan LLP", "hueston.com", "John C. Hueston", "Trial Practice & Commercial Disputes", 4, "/contact/"),
    ("CA", "Kendall Brill & Kelly LLP", "kbkfirm.com", "Richard B. Kendall", "Trial Practice & Real Estate Litigation", 4, "/contact/"),
    ("CA", "Kobre & Kim LLP (CA)", "kobrekim.com", "Michael S. Kim", "Asset Recovery & Creditors Rights", 1, "/contact/"),
    ("CA", "Miller Barondess, LLP", "millerbarondess.com", "Louis R. Miller", "Commercial Litigation & Real Estate Trial", 4, "/contact/"),
    ("CA", "Kaplan Marino, PC", "kaplanmarino.com", "Nina Marino", "White Collar & Asset Forfeiture Defense", 4, "/contact/"),
    ("CA", "Glaser & Associates", "glaserlawoffices.com", "Steven Glaser", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("CA", "Advocate Legal", "advocatelegal.com", "David Brown", "Foreclosure Defense & Wrongful Foreclosure", 2, "/contact/"),
    ("CA", "Consumer Action Law Group", "consumeractionlawgroup.com", "Lauren Rode", "Foreclosure Defense & Consumer Rights", 2, "/contact/"),
    ("CA", "Law Offices of David A. Boone", "boonelaw.com", "David A. Boone", "Foreclosure Defense, Bankruptcy & Real Estate", 2, "/contact/"),
    ("CA", "Rincon Law Group, P.C. (CA)", "rinconlawgroup.com", "Germán Rincon", "Real Estate Litigation & Civil Defense", 4, "/contact/"),
    ("CA", "Aaronson & Dickerson", "aaronsondickerson.com", "Arthur Aaronson", "Real Estate, Probate & Litigation", 3, "/contact/"),
    ("CA", "Carr, McClellan, Ingersoll, Thompson & Horn, P.C.", "carr-mcclellan.com", "Mark Casillas", "Real Estate, Probate & Tax Litigation", 3, "/contact/"),
    ("CA", "Berding & Weil LLP", "berdingweil.com", "Tyler Berding", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("CA", "Burnham Brown", "burnhambrown.com", "Gregory D. Brown", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("CA", "Boornazian, Jensen & Garthe", "bjg.com", "David Boornazian", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("CA", "Archer Norris / Gordon Rees Scully Mansukhani (CA)", "grsm.com", "Dion N. Cominos", "Real Estate Litigation & Commercial Defense", 4, "/contact/"),
    ("CA", "Haapala, Thompson & Abern", "htalaw.com", "David Thompson", "Civil Litigation & Trial Law", 4, "/contact/"),
    ("CA", "Gagen, McCoy, McMahon, Koss, Markowitz & Raines", "gagenmccoy.com", "Charles A. Koss", "Real Estate, Probate & Land Use", 3, "/contact/"),
    ("CA", "McNamara, Ambacher, Wheeler, Hirsig & Meyer LLP", "mcnamaralaw.com", "Thomas E. Ambacher", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("CA", "Craddick, Candland & Conti", "craddicklaw.com", "David Conti", "Civil Litigation & Trial Defense", 4, "/contact/"),
    ("CA", "Clapp, Moroney, Vucinich, Beeman and Scheley", "clappmoroney.com", "Mark Scheley", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("CA", "Coddington, Hicks & Danforth", "chdlawyers.com", "Clinton H. Coddington", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("CA", "Ropers Majeski PC", "ropers.com", "Michael J. Brady", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Severson & Werson", "severson.com", "Mark J. Kenney", "Banking, Foreclosure & Real Estate Litigation", 1, "/contact/"),
    ("CA", "Wright, Finlay & Zak, LLP", "wrightlegal.net", "Robin P. Wright", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("CA", "McCarthy & Holthus, LLP", "mccarthyholthus.com", "Thomas Holthus", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("CA", "Zieve, Brodnax & Steele, LLP", "zbslaw.com", "Les Zieve", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("CA", "Affinia Default Services, LLC", "affiniadefault.com", "Michael Barrett", "Default Servicing & Foreclosure Law", 1, "/contact/"),
    ("CA", "The Wolf Firm, A Law Corporation", "wolffirm.com", "Charles S. Wolf", "Foreclosure, Real Estate & Creditors Rights", 1, "/contact/"),
    ("CA", "Barrett Daffin Frappier Treder & Weiss, LLP", "bdfgroup.com", "Michael Barrett", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("CA", "Tromberg, Morris & Poulin, PLLC (CA)", "tmppllc.com", "Andrea Tromberg", "Foreclosure & Real Estate Practice", 1, "/contact/"),
    ("CA", "Aldridge Pite, LLP (CA)", "aldridgepite.com", "John Aldridge", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("CA", "Marinosci Law Group, P.C. (CA)", "mlg-defaultlaw.com", "Gary Marinosci", "Foreclosure, Title & Creditors Rights", 1, "/contact/"),
    ("CA", "Brock & Scott, PLLC (CA)", "brockandscott.com", "Thomas Brock", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("CA", "Robertson, Anschutz, Schneid, Crane & Partners, PLLC (CA)", "rasflaw.com", "Robert Anschutz", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("CA", "Padgett Law Group (CA)", "padgettlawgroup.com", "David Padgett", "Foreclosure & Real Estate Litigation", 1, "/contact/"),
]

print(f"Loaded {len(CANDIDATES)} California candidate practices.")
