"""Round 5 Expansion: Southeast & Mid-Atlantic Depth (GA, NC, TN, TX)"""

EXPANSION_CANDIDATES_R5 = [
    # GEORGIA (Regional County Seats & Boutiques)
    ("GA", "Barksdale & Associates, P.C.", "barksdalelaw.com", "Kenneth Barksdale", "Real Estate Litigation & Title Clearance", 1, "/contact/"),
    ("GA", "The Minor Firm", "theminorfirm.com", "John T. Minor", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Kinney, Kemp, Sponcler, Joiner & Shaheen, P.C.", "kinneykemp.com", "L. Hugh Kemp", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Mitchell & Mitchell, P.C.", "mitchellandmitchell.com", "Erwin Mitchell", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Coppedge & Dunlap, P.C.", "coppedgedunlap.com", "Warren Coppedge", "Real Estate Litigation & Corporate", 4, "/contact/"),
    ("GA", "Brinson, Askew, Berry, Seigler, Richardson & Davis, LLP", "brinson-askew.com", "Robert M. Brinson", "Real Estate Litigation & Local Government", 1, "/contact/"),
    ("GA", "Shaw, Maddox, Graham, Bowman & Neff, LLP", "shawmaddox.com", "Charles Maddox", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("GA", "McRae, Stegall, Peek, Harman, Smith & Manning, LLP", "mcraestegall.com", "Dan McRae", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("GA", "The Brown Firm", "brownfirm.com", "Harry Brown", "Civil Trial Practice & Property Recovery", 4, "/contact/"),
    ("GA", "Tate Law Group, LLC", "tatelawgroup.com", "Mark Tate", "Civil Trial Practice & Complex Recovery", 4, "/contact/"),
    ("GA", "Savage, Turner, Durham, Pinckney & Savage", "savagelawfirm.com", "Brent Savage", "Civil Trial Practice", 4, "/contact/"),
    ("GA", "Gastin & Hill, Attorneys at Law", "gastinhill.com", "C. Andrew Gastin", "Foreclosure Defense & Debt Relief", 2, "/contact/"),
    ("GA", "Edenfield, Cox, Bruce & Classens, P.C.", "edenfieldlaw.com", "Gerald M. Edenfield", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Taulbee, Rushing, Snipes, Marsh & Hodgin, LLC", "statesborolawyers.com", "Danny Rushing", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("GA", "Franklin, Taulbee, Rushing, Snipes & Marsh", "ftrlawyers.com", "James Franklin", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("GA", "Brown, Readdick, Bumgartner, Carter, Strickland & Watkins, LLP", "brbcsw.com", "Terry Readdick", "Civil Trial & Local Government Practice", 4, "/contact/"),
    ("GA", "Gilbert, Harrell, Sumerford & Martin, P.C.", "gilbertharrelllaw.com", "Wallace Harrell", "Real Estate, Probate & Tax Litigation", 1, "/contact/"),
    ("GA", "Taylor, Odachowski, Schmidt & Crossland, P.C.", "tosclaw.com", "John Taylor", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("GA", "W. Douglas Adams, Attorney at Law", "wdouglasadams.com", "Douglas Adams", "Real Estate & Title Law", 1, "/contact/"),
    ("GA", "The Bishop Law Firm", "thebishoplawfirm.com", "Mark Bishop", "Real Estate, Probate & Civil Law", 3, "/contact/"),
    ("GA", "Bishop, Collins & Richardson, P.C.", "bcrlawyers.com", "Barry Bishop", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("GA", "Dozier Law Firm LLC", "dozierlaw.com", "David Dozier", "Civil Trial Practice & Asset Disputes", 4, "/contact/"),
    ("GA", "Buzzell, Welsh & Hill", "bwhlegal.com", "Stephen Welsh", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("GA", "Adams, Jordan & Herrington, P.C.", "adamsjordan.com", "Virgil Adams", "Trial Practice & Real Estate Disputes", 4, "/contact/"),
    ("GA", "Haygood, Lynch, Harris, Melton & Curry, P.C.", "hlhmc.com", "Charles Haygood", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("GA", "Walker, Hulbert, Gray & Moore, LLP", "whgmlaw.com", "David Gray", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("GA", "Westmoreland, Patterson, Moseley & Hinson, L.L.P.", "wpmhlegal.com", "Thomas Patterson", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("GA", "Harris, Penn & Lowry, LLP", "hpllegal.com", "Darren Penn", "Civil Trial Practice & Complex Litigation", 4, "/contact/"),
    ("GA", "Ken Nugent Attorneys at Law", "attorneykennugent.com", "Kenneth S. Nugent", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("GA", "Montlick and Associates, P.C.", "montlick.com", "David Montlick", "Civil Trial Practice", 4, "/contact/"),

    # NORTH CAROLINA (Piedmont, Coastal & Mountain Boutiques)
    ("NC", "The Law Offices of James Scott Farrin", "farrin.com", "James S. Farrin", "Civil Trial Practice & Eminent Domain", 4, "/contact/"),
    ("NC", "Deuterman Law Group", "deutermanlaw.com", "Dan Deuterman", "Civil Trial Practice & Recovery", 4, "/contact/"),
    ("NC", "Crumley Roberts, LLP", "crumleyroberts.com", "Chris Roberts", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("NC", "Henson Fuerst, P.A.", "lawmed.com", "Thomas Henson", "Eminent Domain & Real Estate Litigation", 1, "/contact/"),
    ("NC", "Riddle & Brantley, LLP", "justicecounts.com", "Gene Riddle", "Civil Trial Practice & Recovery", 4, "/contact/"),
    ("NC", "Whitley Law Firm", "whitleylawfirm.com", "Robert E. Whitley", "Civil Trial Practice", 4, "/contact/"),
    ("NC", "Lanier Law Group, P.A.", "lanierlawgroup.com", "Lisa Lanier", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("NC", "Hardison & Cochran, Attorneys at Law", "lawyernc.com", "Benjamin Cochran", "Civil Trial Practice", 4, "/contact/"),
    ("NC", "Martin & Jones, PLLC", "martinandjones.com", "John Alan Jones", "Civil Trial & Complex Litigation", 4, "/contact/"),
    ("NC", "Twiggs, Strickland & Rabenau, P.A.", "twiggsstrickland.com", "Howard Twiggs", "Civil Trial Practice", 4, "/contact/"),
    ("NC", "Cheshire Parker Schneider (Raleigh)", "cheshirepark.com", "Joseph Cheshire", "Asset Recovery & Civil Trial", 4, "/contact/"),
    ("NC", "Edwards Kirby, LLP", "edwardskirby.com", "John R. Edwards", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("NC", "Thorp Law", "thorplaw.com", "Herbert Thorp", "Eminent Domain & Real Estate Litigation", 1, "/contact/"),
    ("NC", "Sever Storey LLP (NC)", "landownerattorneys.com", "Phil Sever", "Eminent Domain & Landowner Rights", 1, "/contact/"),
    ("NC", "NC Eminent Domain Law Firm", "ncomminentdomain.com", "Jason Campbell", "Eminent Domain & Real Estate Litigation", 1, "/contact/"),
    ("NC", "Starr & Dickerson, PLLC", "starrlawfirm.com", "Kenneth Starr", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("NC", "Hunton Andrews Kurth LLP (Charlotte)", "huntonak.com", "Mark Horoschak", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Mayer Brown LLP (Charlotte)", "mayerbrown.com", "David Wood", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("NC", "Alston & Bird LLP (Charlotte)", "alston.com", "David Brown", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("NC", "Troutman Pepper (Charlotte)", "troutman.com", "Christopher Kelly", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Fox Rothschild (Charlotte)", "foxrothschild.com", "Keith Neely", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Nelson Mullins (Charlotte)", "nelsonmullins.com", "Graham Morrison", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("NC", "Bradley Arant (Charlotte)", "bradley.com", "Christopher Lam", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Maynard Nexsen (Charlotte)", "maynardnexsen.com", "Leighton Lord", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("NC", "McGuireWoods (Charlotte)", "mcguirewoods.com", "Tracy Walker", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "K&L Gates (Charlotte)", "klgates.com", "Brett Buda", "Real Estate Litigation & Land Law", 1, "/contact/"),
    ("NC", "Parker Poe (Raleigh)", "parkerpoe.com", "Charles Meeker", "Real Estate Litigation & Municipal Law", 1, "/contact/"),
    ("NC", "Smith Anderson (Raleigh)", "smithlaw.com", "Byron Kirkland", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Wyrick Robbins (Raleigh)", "wyrick.com", "Donald Munford", "Trusts, Estates & Real Estate Litigation", 3, "/contact/"),
    ("NC", "Brooks Pierce (Raleigh)", "brookspierce.com", "Jim Phillips", "Real Estate Litigation & Trial Practice", 4, "/contact/"),

    # TENNESSEE (Chancery, Delinquent Tax, Estate & Property Boutiques)
    ("TN", "The Law Office of Mark A. Carver (Nashville)", "carverlawtn.com", "Mark A. Carver", "Chancery Surplus Recovery under 67-5-2510", 1, "/contact/"),
    ("TN", "Yoakum Law PLLC (Memphis)", "yoakumlaw.com", "Brian L. Yoakum", "Tax Sale Excess Proceeds Litigation", 1, "/contact/"),
    ("TN", "The Blair Firm", "blairfirm.com", "Robert Blair", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TN", "Patterson PC", "pattersonfirm.com", "Jesse Patterson", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TN", "The Law Office of George R. Fusner, Jr.", "fusnerlaw.com", "George Fusner", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Trauger & Tuke (Nashville)", "trauger-tuke.com", "Byron Trauger", "Real Estate Litigation & Land Title", 1, "/contact/"),
    ("TN", "Ortale Kelley Herbert & Crawford (Nashville)", "ortalekelley.com", "Daniel Herbert", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("TN", "White & Reasor, PLC (Nashville)", "whitereasor.com", "David White", "Real Estate, Probate & Commercial Law", 3, "/contact/"),
    ("TN", "Batson Nolan PLC (Clarksville)", "batsonnolan.com", "Dan Nolan", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Cunningham, Mitchell & Rocconi (Clarksville)", "cmrlegal.com", "Mark Mitchell", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("TN", "Rainey, Kizer, Reviere & Bell (Jackson)", "raineykizer.com", "Russell Reviere", "Real Estate Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Waldrop & Hall, P.A. (Jackson)", "waldrophall.com", "David Hall", "Real Estate, Probate & Civil Law", 3, "/contact/"),
    ("TN", "Pentecost, Glenn & Mauldin (Jackson)", "pgmlawfirm.com", "James Pentecost", "Civil Trial Practice", 4, "/contact/"),
    ("TN", "Hunter, Smith & Davis, LLP (Kingsport)", "hsdlaw.com", "Mark Dessauer", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Wilson Worley, PC (Kingsport)", "wilsonworley.com", "Richard Currie", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "Herndon, Coleman, Brading & McKee (Johnson City)", "hcblaw.com", "Matthew Bolton", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TN", "Milligan & Coleman PLLC (Greeneville)", "milligancoleman.com", "Mark Cowan", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("TN", "Barger & Gaines (Nashville)", "bargergaines.com", "Paul Barger", "Civil Trial & Asset Defense", 4, "/contact/"),
    ("TN", "The Higgins Firm (Nashville)", "higginsfirm.com", "Jim Higgins", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("TN", "Cole Law Group, PC (Brentwood)", "colelawgrouppc.com", "Peter Cole", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TN", "Rogers, Kamm & Shea (Nashville)", "rkslawgroup.com", "Helen Rogers", "Probate, Asset Division & Litigation", 3, "/contact/"),
    ("TN", "Bednarz & Bednarz (Nashville)", "bednarzlaw.com", "Joe Bednarz", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("TN", "Kinnard Law (Nashville)", "kinnardlaw.com", "Randall Kinnard", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("TN", "Rocky McElhaney Law Firm (Nashville)", "rockylawfirm.com", "Rocky McElhaney", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("TN", "Hughes & Coleman (Nashville)", "hughesandcoleman.com", "Lee Coleman", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Pohl & Berk, LLP (Nashville)", "pohlandberk.com", "Mark Pohl", "Civil Trial Practice & Asset Disputes", 4, "/contact/"),
    ("TN", "Rutherford, DeMarco & White (Nashville)", "rdwlawfirm.com", "David Rutherford", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "McNabb, Bragorgos, Burgess & Sorin (Memphis)", "mbb-law.com", "Leland McNabb", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Glassman, Wyatt, Tuttle & Cox (Memphis)", "glassmanfirm.com", "Richard Glassman", "Civil Trial & Commercial Litigation", 4, "/contact/"),
    ("TN", "Bailey & Greer, PLLC (Memphis)", "baileygreer.com", "Thomas Greer", "Civil Trial Practice & Property Law", 4, "/contact/"),
    ("TN", "Donati Law, PLLC (Memphis)", "donatilaw.com", "Donald Donati", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Farris Bobango PLC (Memphis)", "farrisbobango.com", "John Bobango", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "The Crone Law Firm, PLC (Memphis)", "cronelawfirmplc.com", "Alan Crone", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("TN", "Tune, Entrekin & White (Nashville)", "tewlaw.com", "Peter White", "Real Estate, Eminent Domain & Land Use", 1, "/contact/"),
    ("TN", "Thompson Burton PLLC (Franklin)", "thompsonburton.com", "Walt Burton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Story, Abernathy & Campbell (Franklin)", "storyabernathy.com", "David Story", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "Duncan, Hatcher, Fleenor & Culpepper (Chattanooga)", "dhf-law.com", "Phillip Fleenor", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Cavin & O'Herren (Knoxville)", "cavinoherren.com", "David Cavin", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Grant, Konvalinka & Harrison (Chattanooga)", "gkhpc.com", "John Anderson", "Real Estate Litigation, Tax & Probate", 1, "/contact/"),
    ("TN", "Luther-Anderson, P.L.L.P. (Chattanooga)", "lutheranderson.com", "William Luther", "Civil Trial & Real Estate Practice", 4, "/contact/"),

    # TEXAS (Bexar, Harris, Dallas, Travis, Tarrant Boutiques)
    ("TX", "The Moster Craft Law Firm", "mostercraft.com", "Charles Moster", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("TX", "The Weaver Law Firm (Austin)", "weaverlawyers.com", "Richard Weaver", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("TX", "The Weaver Law Firm (San Antonio)", "weaverlawyers.com", "Richard Weaver", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("TX", "The Morales Firm, P.C. (San Antonio)", "moralesfirm.com", "Jesse Morales", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Law Office of Mark C. Ticer (Dallas)", "ticerlaw.com", "Mark Ticer", "Civil Litigation & Trial Law", 4, "/contact/"),
    ("TX", "The Chenault Law Firm (Denton)", "chenaultlawfirm.com", "Jill Chenault", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Saunders, Walsh & Beard (McKinney)", "saunderswalsh.com", "Mark Walsh", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Hendershot Cowart P.C. (Houston)", "hchlawyers.com", "Trey Hendershot", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("TX", "Wright Firm, LLP (Dallas)", "thewrightlawyers.com", "Paul Wright", "Real Estate, Probate & Family Asset Recovery", 3, "/contact/"),
    ("TX", "The Cromeens Law Firm (Houston)", "cromeenslawfirm.com", "Karalynn Cromeens", "Real Estate, Liens & Quiet Title", 1, "/contact/"),
    ("TX", "Sandoz & Sandoz, PLLC (Dallas)", "sandozlaw.com", "David Sandoz", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("TX", "Leavitt & Eldredge Law Firm (Fort Worth)", "leavitteldredge.com", "Richard Leavitt", "Civil Litigation & Commercial Property", 4, "/contact/"),
    ("TX", "Kushner Law Firm, PLLC (Sugar Land)", "kushnerlaw.com", "David Kushner", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("TX", "Bailey & Galyen (Dallas)", "galyen.com", "Phillip Galyen", "Foreclosure Defense & Probate", 2, "/contact/"),
    ("TX", "Allmand Law Firm (Dallas)", "allmandlaw.com", "Reed Allmand", "Foreclosure Defense & Asset Protection", 2, "/contact/"),
    ("TX", "Leinart Law Firm (Dallas)", "leinartlaw.com", "Marcus Leinart", "Foreclosure Defense & Distressed Real Estate", 2, "/contact/"),
    ("TX", "Acker Warren, P.C. (Arlington)", "ackerwarren.com", "Sean Acker", "Foreclosure Defense & Debt Litigation", 2, "/contact/"),
    ("TX", "Fears Nachawati Law Firm (Dallas)", "fnlawfirm.com", "Bryan Fears", "Commercial Litigation & Property Rights", 4, "/contact/"),
    ("TX", "The Law Offices of Eric L. Davis (Houston)", "ericdavislaw.com", "Eric Davis", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Sethi & Mazaheri LLC (Houston)", "sethi-mazaheri.com", "Reza Mazaheri", "Real Estate & Commercial Law", 4, "/contact/"),
    ("TX", "Langley & Banack, Inc. (Kerrville)", "langleybanack.com", "Arthur Banack", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TX", "Barton, East & Caldwell (San Antonio)", "beclaw.com", "David Barton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Bonial & Associates, P.C. (Dallas)", "bonialpc.com", "Paul Bonial", "Foreclosure, Bankruptcy & Real Estate", 1, "/contact/"),
    ("TX", "Mackie Wolf Zientz & Mann (Brentwood)", "mwzmlaw.com", "Keller Mackie", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("TX", "Hughes, Watters & Askanase (Houston)", "hwa.com", "Wayne Kitchens", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
]

print(f"Loaded {len(EXPANSION_CANDIDATES_R5)} round 5 expansion candidates.")
