"""
Round 7 Expansion: Additional High-Quality Law Practices across Top 6 States
Focused on Tax Sale Litigation, Foreclosure Defense, Probate & Trust Litigation, and Real Estate Trial Law.
"""

EXPANSION_CANDIDATES_R7 = [
    # FLORIDA (Orlando, Tampa, Miami, Jacksonville, Palm Beach, Sarasota, Fort Myers)
    ("FL", "Winderweedle, Haines, Ward & Woodman, P.A.", "whww.com", "Bradley Saxton", "Creditors Rights, Real Estate & Foreclosure Litigation", 1, "/contact/"),
    ("FL", "Bogin, Munns & Munns, P.A.", "boginmunns.com", "Spencer Munns", "Real Estate Litigation, Probate & Estate Administration", 3, "/contact-us/"),
    ("FL", "Shuffield, Lowman & Wilson, P.A.", "shuffieldlowman.com", "William Lowman", "Probate Litigation, Estate Planning & Real Estate", 3, "/contact/"),
    ("FL", "Lowndes, Drosdick, Doster, Kantor & Reed, P.A.", "lowndes-law.com", "William Doster", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "DeWitt Law Firm, P.A.", "dewittlaw.com", "Moses DeWitt", "Real Estate Disputes & Foreclosure Defense", 2, "/contact/"),
    ("FL", "Latham, Luna, Eden & Beaudine, LLP", "lathamluna.com", "Michael Beaudine", "Real Property Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Mateer & Harbert, P.A.", "mateerharbert.com", "Kurt Ardaman", "Real Estate, Probate & Eminent Domain", 3, "/contact/"),
    ("FL", "Fassett, Anthony & Taylor, P.A.", "fassettlaw.com", "L. Miller Fassett", "Creditors Rights & Commercial Litigation", 1, "/contact/"),
    ("FL", "Dean, Mead, Egerton, Bloodworth, Capouano & Bozarth, P.A.", "deanmead.com", "Marc Chapman", "Probate Litigation, Trust Disputes & Real Property", 3, "/contact/"),
    ("FL", "The DeVries Law Firm, P.A.", "devrieslegal.com", "Les DeVries", "Probate, Estate Administration & Real Estate", 3, "/contact/"),
    ("FL", "Fisher Rushmer, P.A.", "fisherlawfirm.com", "John Fisher", "Civil Trial & Real Estate Litigation", 4, "/contact/"),
    ("FL", "Rumberger, Kirk & Caldwell, P.A.", "rumberger.com", "Frank Sheppard", "Commercial Litigation & Property Disputes", 4, "/contact-us/"),
    ("FL", "Trenam Law", "trenam.com", "Nelson Castellano", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("FL", "Macfarlane Ferguson & McMullen, P.A.", "macfar.com", "Stephen Sears", "Real Estate, Probate & Tax Litigation", 3, "/contact-us/"),
    ("FL", "Bush Ross, P.A.", "bushross.com", "Jeffrey Warren", "Bankruptcy, Creditors Rights & Distressed Real Estate", 1, "/contact/"),
    ("FL", "Hill Ward Henderson", "hwhlaw.com", "R. Reid Haney", "Real Estate Litigation, Land Use & Title Disputes", 1, "/contact/"),
    ("FL", "Barnett, Bolt, Kirkwood, Long & Koche, P.A.", "barnettbolt.com", "Leslie Barnett", "Estate Planning, Probate & Tax Controversies", 3, "/contact/"),
    ("FL", "Shutts & Bowen LLP", "shutts.com", "Francis Rodriguez", "Real Estate Litigation & Creditors Remedies", 1, "/contact-us/"),
    ("FL", "Gunster, Yoakley & Stewart, P.A.", "gunster.com", "H. William Perry", "Real Estate Litigation & Trust Disputes", 1, "/contact/"),
    ("FL", "Broad and Cassel LLP", "broadandcassel.com", "Mark Raymond", "Real Estate Litigation & Foreclosure Matters", 1, "/contact/"),
    ("FL", "Berger Singerman LLP", "bergersingerman.com", "Jordi Guso", "Distressed Real Estate & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Stearns Weaver Miller Weissler Alhadeff & Sitterson, P.A.", "stearnsweaver.com", "Rick Schatz", "Real Estate Litigation & Distressed Property", 1, "/contact/"),
    ("FL", "Kluger, Kaplan, Silverman, Katzen & Levine, P.L.", "klugerkaplan.com", "Alan Kluger", "Real Estate Litigation & Probate Disputes", 1, "/contact/"),
    ("FL", "Homer Bonner Jacobs Ortiz, P.A.", "homerbonner.com", "Peter Homer", "Commercial Litigation & Asset Recovery", 4, "/contact/"),
    ("FL", "Markowitz Ringel Trusty & Hartog, P.A.", "mrthlaw.com", "Jerry Markowitz", "Creditors Rights, Bankruptcy & Foreclosure", 1, "/contact/"),

    # TEXAS (Houston, Dallas, Fort Worth, Austin, San Antonio, El Paso)
    ("TX", "Munsch Hardt Kopf & Harr, P.C.", "munsch.com", "Phil C. Appenzeller", "Creditors Rights, Distressed Assets & Real Estate", 1, "/contact-us/"),
    ("TX", "Winstead PC", "winstead.com", "David Dawson", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("TX", "Bell Nunnally & Martin LLP", "bellnunnally.com", "Christopher Trowbridge", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Cobb Martinez Woodward PLLC", "cobbmartinez.com", "Daniel Woodward", "Real Property Litigation & Civil Defense", 4, "/contact/"),
    ("TX", "Cowles & Thompson, P.C.", "cowlesthompson.com", "David R. Woodward", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("TX", "Carrington, Coleman, Sloman & Blumenthal, L.L.P.", "ccsb.com", "Monica Latin", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("TX", "Kane Russell Coleman Logan PC", "krcl.com", "Robert LeMay", "Creditors Rights, Bankruptcy & Distressed Property", 1, "/contact-us/"),
    ("TX", "Scheef & Stone, L.L.P.", "solidcounsel.com", "John Scheef", "Real Estate Litigation & Construction Law", 4, "/contact/"),
    ("TX", "Crain Caton & James, P.C.", "craincaton.com", "Peter G. Nemeth", "Probate Litigation, Trust Disputes & Real Property", 3, "/contact/"),
    ("TX", "Weycer, Kaplan, Pulaski & Zuber, P.C.", "wkpz.com", "Mark Weycer", "Real Estate Litigation, Creditors Rights & Probate", 1, "/contact/"),
    ("TX", "Roberts Markel Weinberg Butler Hailey PC", "rmwbh.com", "Marc Markel", "Real Estate Litigation, HOA & Foreclosure", 2, "/contact/"),
    ("TX", "Hirsch & Westheimer, P.C.", "hirschwest.com", "David Westheimer", "Real Estate, Creditors Rights & Probate", 1, "/contact/"),
    ("TX", "BoyarMiller", "boyarmiller.com", "Chris Hanslik", "Real Estate Litigation & Asset Disputes", 1, "/contact/"),
    ("TX", "Chamberlain, Hrdlicka, White, Williams & Aughtry, P.C.", "chamberlainlaw.com", "Larry Campagna", "Tax Controversies, Probate & Real Estate", 3, "/contact-us/"),
    ("TX", "Graves, Dougherty, Hearon & Moody, P.C.", "gdhm.com", "Cliff Ernst", "Real Estate Litigation, Title & Probate Law", 1, "/contact/"),
    ("TX", "Armbrust & Brown, PLLC", "abaustin.com", "David Armbrust", "Real Estate Litigation & Land Development", 4, "/contact/"),
    ("TX", "Lloyd Gosselink Rochelle & Townsend, P.C.", "lglawfirm.com", "David Townsend", "Eminent Domain & Land Property Disputes", 4, "/contact/"),
    ("TX", "Davidson Troilo Ream & Garza, P.C.", "dtrglaw.com", "Terry Topham", "Municipal Law, Tax & Real Property Litigation", 4, "/contact/"),
    ("TX", "Langley & Banack, Inc.", "langleybanack.com", "William Banack", "Real Estate Litigation, Estate Planning & Probate", 3, "/contact/"),
    ("TX", "Kreager Mitchell, PLLC", "kreagermitchell.com", "Bruce Mitchell", "Estate Planning, Probate & Real Estate", 3, "/contact/"),

    # GEORGIA (Atlanta, Savannah, Augusta, Macon, Columbus)
    ("GA", "Taylor English Duma LLP", "taylorenglish.com", "Marc Taylor", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("GA", "Smith, Gambrell & Russell, LLP", "sgrlaw.com", "Stephen Forte", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Arnall Golden Gregory LLP", "agg.com", "Jonathan Eady", "Real Estate, Distressed Assets & Litigation", 1, "/contact-us/"),
    ("GA", "Chamberlain Hrdlicka (Atlanta)", "chamberlainlaw.com", "Richard Morrison", "Tax Disputes, Probate & Real Estate Litigation", 3, "/contact-us/"),
    ("GA", "Balch & Bingham LLP (Atlanta)", "balch.com", "Stan Blanton", "Real Estate Litigation, Creditors Rights & Banking", 1, "/contact/"),
    ("GA", "Morris, Manning & Martin, LLP", "mmmlaw.com", "Duncan Miller", "Real Estate Litigation, Distressed Property & Foreclosure", 1, "/contact/"),
    ("GA", "Parker, Hudson, Rainer & Dobbs LLP", "phrd.com", "Wayne Hillis", "Creditors Rights, Bankruptcy & Real Estate Disputes", 1, "/contact/"),
    ("GA", "HunterMaclean", "huntermaclean.com", "Brad Harmon", "Real Estate Litigation, Distressed Assets & Probate", 1, "/contact/"),
    ("GA", "Oliver Maner LLP", "olivermaner.com", "Patrick O'Connor", "Civil Trial & Real Property Litigation", 4, "/contact/"),
    ("GA", "Bouhan Falligant LLP", "bouhan.com", "Lea Holliday", "Real Estate, Probate & Trust Litigation", 3, "/contact/"),
    ("GA", "Hull Barrett, PC", "hullbarrett.com", "David Hudson", "Real Estate Litigation, Probate & Tax Disputes", 3, "/contact/"),
    ("GA", "James-Bates-Brannan-Groover-LLP", "jamesbates.com", "Duke Groover", "Real Estate Litigation, Distressed Assets & Banking", 1, "/contact/"),
    ("GA", "Page, Scrantom, Sprouse, Tucker & Ford, P.C.", "psstf.com", "Marcus Tucker", "Real Estate Litigation, Creditors Rights & Probate", 3, "/contact/"),

    # CALIFORNIA (Los Angeles, Orange County, San Diego, Riverside, Inland Empire, Bay Area)
    ("CA", "Buchalter, A Professional Corporation", "buchalter.com", "Adam Bass", "Real Estate Litigation, Creditors Rights & Distressed Debt", 1, "/contact-us/"),
    ("CA", "Cox, Castle & Nicholson LLP", "coxcastle.com", "Mathew Wyman", "Real Estate Litigation, Distressed Land & Land Use", 1, "/contact/"),
    ("CA", "Allen Matkins Leck Gamble Mallory & Natsis LLP", "allenmatkins.com", "David Osias", "Real Estate Litigation, Distressed Property & Creditors", 1, "/contact-us/"),
    ("CA", "Procopio, Cory, Hargreaves & Savitch LLP", "procopio.com", "John Lormon", "Real Estate Litigation, Probate & Distressed Assets", 1, "/contact-us/"),
    ("CA", "Best Best & Krieger LLP", "bbklaw.com", "Eric Garner", "Municipal Law, Eminent Domain & Real Property", 4, "/contact/"),
    ("CA", "Rutan & Tucker, LLP", "rutan.com", "Michael Adams", "Real Estate Litigation, Foreclosure & Land Use", 1, "/contact-us/"),
    ("CA", "Nossaman LLP", "nossaman.com", "George Joseph", "Eminent Domain, Real Estate Litigation & Title", 1, "/contact-us/"),
    ("CA", "Greenberg Glusker Fields Claman & Machtinger LLP", "greenbergglusker.com", "Bob Baradaran", "Real Estate Litigation, Probate & Wealth Planning", 3, "/contact/"),
    ("CA", "Ervin Cohen & Jessup LLP", "ecjlaw.com", "Barry MacNaughton", "Real Estate Litigation, Bankruptcy & Creditors Rights", 1, "/contact/"),
    ("CA", "Glaser Weil Fink Howard Jordan & Shapiro LLP", "glaserweil.com", "Peter Weil", "Real Estate Litigation, Distressed Property & Foreclosure", 1, "/contact/"),
    ("CA", "Crosbie Gliner Schiffman Southard & Swanson LLP", "cgs3.com", "Sean Southard", "Real Estate Litigation & Distressed Property", 1, "/contact/"),
    ("CA", "Higgs Fletcher & Mack LLP", "higgslaw.com", "Steven Micheli", "Real Estate Litigation, Probate & Business Trial", 3, "/contact/"),
    ("CA", "Seltzer Caplan McMahon Vitek", "scmv.com", "Robert Caplan", "Real Estate Litigation, Title Insurance & Probate", 1, "/contact/"),

    # NORTH CAROLINA (Raleigh, Charlotte, Greensboro, Winston-Salem, Wilmington)
    ("NC", "Poyner Spruill LLP", "poynerspruill.com", "Dan Cahill", "Real Estate Litigation, Creditors Rights & Bankruptcy", 1, "/contact/"),
    ("NC", "Ward and Smith, P.A.", "wardandsmith.com", "Brad Evans", "Creditors Rights, Real Estate & Trust Litigation", 1, "/contact/"),
    ("NC", "Brooks, Pierce, McLendon, Humphrey & Leonard, L.L.P.", "brookspierce.com", "Reid Phillips", "Real Estate Litigation, Foreclosure & Probate", 1, "/contact/"),
    ("NC", "Smith Anderson", "smithlaw.com", "Byron Kirkland", "Real Estate Litigation, Creditors Rights & Commercial", 1, "/contact-us/"),
    ("NC", "Morningstar Law Group", "morningstarlawgroup.com", "Randy Whitmeyer", "Real Estate Litigation, Land Title & Development", 4, "/contact/"),
    ("NC", "Hedrick Gardner Kincheloe & Garofalo LLP", "hedrickgardner.com", "Paul Lawrence", "Civil Trial & Real Property Claims", 4, "/contact/"),
    ("NC", "Nexsen Pruet (Charlotte)", "nexsenpruet.com", "Ernie Pearson", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Parker Poe Adams & Bernstein LLP", "parkerpoe.com", "Tom Griffin", "Real Estate Litigation, Foreclosure & Distressed Property", 1, "/contact/"),
    ("NC", "Robinson, Bradshaw & Hinson, P.A.", "robinsonbradshaw.com", "Allen Robertson", "Real Estate Litigation, Bankruptcy & Asset Recovery", 1, "/contact/"),
    ("NC", "Manning, Fulton & Skinner, P.A.", "manningfulton.com", "Barry Mann", "Real Estate, Creditors Rights & Estate Planning", 3, "/contact/"),
    ("NC", "Womble Bond Dickinson (Winston-Salem)", "womblebonddickinson.com", "Elizabeth Boston", "Real Estate Litigation & Creditors Remedies", 1, "/contact-us/"),
    ("NC", "Bell, Davis & Pitt, P.A.", "belldavispitt.com", "Alan Davis", "Real Estate Litigation, Bankruptcy & Probate Disputes", 3, "/contact/"),
    ("NC", "Craige Jenkins Liipfert & Walker LLP", "craigejenkins.com", "Gordon Jenkins", "Real Estate, Probate & Estate Administration", 3, "/contact/"),

    # TENNESSEE (Nashville, Memphis, Knoxville, Chattanooga)
    ("TN", "Bass, Berry & Sims PLC", "bassberry.com", "Todd Rolapp", "Real Estate Litigation, Distressed Debt & Creditors", 1, "/contact/"),
    ("TN", "Sherrard Roe Voigt & Harbison, PLC", "srvhlaw.com", "Thomas Voigt", "Real Estate Litigation, Probate Disputes & Commercial", 3, "/contact/"),
    ("TN", "Butler Snow LLP (Nashville)", "butlersnow.com", "Christopher Maddux", "Creditors Rights, Real Estate & Bankruptcy", 1, "/contact-us/"),
    ("TN", "Bone McAllester Norton PLLC", "bonelaw.com", "Charles Robert Bone", "Real Estate Litigation, Foreclosure & Land Title", 1, "/contact/"),
    ("TN", "Gullett Sanford Robinson & Martin PLLC", "gsrm.com", "F. Scott Thomas", "Real Estate Litigation, Probate & Creditors Rights", 3, "/contact/"),
    ("TN", "Neal & Harwell, PLC", "nealharwell.com", "Ronald G. Harris", "Civil Trial, Real Property Disputes & Estate Litigation", 4, "/contact/"),
    ("TN", "Wyatt, Tarrant & Combs, LLP (Memphis)", "wyattfirm.com", "Franklin Jobe", "Real Estate, Creditors Rights & Probate Disputes", 1, "/contact/"),
    ("TN", "Burch, Porter & Johnson, PLLC", "bpjlaw.com", "Les Jones", "Commercial Litigation, Real Estate & Estate Disputes", 3, "/contact/"),
    ("TN", "Evans Petree PC", "evanspetree.com", "C. Thomas Cates", "Real Estate Litigation, Foreclosure & Tax Disputes", 1, "/contact/"),
    ("TN", "Harris Shelton Hanover Walsh, PLLC", "harrisshelton.com", "Brett Hughes", "Real Estate, Probate & Creditors Rights", 3, "/contact/"),
    ("TN", "Woolf, McClane, Bright, Allen & Carpenter, PLLC", "wmbac.com", "J. Christopher Woolf", "Real Estate Litigation, Probate & Trust Disputes", 3, "/contact/"),
    ("TN", "Kramer Rayson LLP", "kramer-rayson.com", "John T. Johnson", "Real Estate, Probate & Civil Litigation", 3, "/contact/"),
    ("TN", "Chambliss, Bahner & Stophel, P.C.", "chamblisslaw.com", "Mark Cunningham", "Real Estate Litigation, Creditors Rights & Probate", 1, "/contact/"),
    ("TN", "Miller & Martin PLLC", "millermartin.com", "Scott Parrish", "Real Estate Litigation, Bankruptcy & Title Disputes", 1, "/contact/")
]
