"""Round 4 Expansion: High-Yield Metro & County Boutiques across Top 6 States"""

EXPANSION_CANDIDATES_R4 = [
    # FLORIDA (Polk, Brevard, Volusia, Marion, Martin, St. Lucie, Collier)
    ("FL", "Boswell & Dunlap LLP", "bosdun.com", "Donald H. Wilson", "Real Estate, Probate & Local Government", 3, "/contact/"),
    ("FL", "Peterson & Myers, P.A.", "petersonmyers.com", "Jack P. Brandon", "Real Estate Litigation, Probate & Title", 1, "/contact/"),
    ("FL", "Clark, Campbell, Lancaster, Workman & Airth, P.A.", "cclwa.com", "Timothy Campbell", "Real Estate Litigation & Land Use", 1, "/contact/"),
    ("FL", "Gray, Ackermann & Ward, P.A.", "gray-law.com", "David Gray", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("FL", "Straughn & Turner, P.A.", "straughnturner.com", "Jack Straughn", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("FL", "Frost Van den Boom, P.A.", "frostlawfirm.com", "Peter Van den Boom", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "Lilly, O'Toole & Brown, LLP", "lob-law.com", "Kenneth Lilly", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Widerman Malek, PL", "uslegalteam.com", "Mark Malek", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Vance, Lotane & Bookhardt, P.A.", "vancelaw.com", "David Lotane", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Volk Law Offices, P.A.", "volklawoffices.com", "David J. Volk", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Alpizar Law, LLC", "alpizarlaw.com", "John Alpizar", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Cantwell & Goldman, P.A.", "cantwellgoldman.com", "Richard Goldman", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("FL", "Fallace & Associates, P.A.", "fallacelaw.com", "Michael Fallace", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Glover Law Firm", "gloverlawfirm.com", "Gordon Glover", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("FL", "The King Law Firm", "kinglawfirm.org", "Gregory King", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "Craggs & Brough, P.A.", "craggsbrough.com", "David Craggs", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "McCarthy, Summers, Bobko, Wood, Norman, Bass & Melby, P.A.", "mccarthysummers.com", "Terence McCarthy", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("FL", "Fox, Wackeen, Dungey, Beard, Bush, Goldman, Kilbride, Waters & Robison, L.L.P.", "foxwackeen.com", "George W. Bush", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "Crary Buchanan, P.A.", "crarybuchanan.com", "Michael Crary", "Real Estate, Probate & Title Clearance", 1, "/contact/"),
    ("FL", "Gunster (Stuart)", "gunster.com", "Preston J. Fields", "Real Estate Litigation & Title Law", 1, "/contact-us/"),
    ("FL", "Kramer, Sopko & Levenstein, P.A.", "kslattorneys.com", "David Levenstein", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "Collins Brown Barkett, CHARTERED", "verobeachlawyers.com", "David Brown", "Real Estate, Probate & Tax Law", 3, "/contact/"),
    ("FL", "Gould Cooksey Fennell, P.A.", "gouldcooksey.com", "Troy B. Hafner", "Real Estate, Probate & Estate Planning", 3, "/contact/"),
    ("FL", "Vocelle & Berg, LLP", "vocelleberg.com", "Louis B. Vocelle", "Civil Trial Practice & Real Estate", 4, "/contact/"),
    ("FL", "Block & Scarpa", "blockscarpa.com", "Michael Scarpa", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("FL", "Lulich & Attorneys, P.A.", "lulich.com", "John Lulich", "Real Estate, Foreclosure & Estate Planning", 2, "/contact/"),
    ("FL", "Rossway Swan Tierney Barry & Oliver, P.L.", "rosswayswan.com", "Bradley Rossway", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("FL", "WhiteBird, PLLC", "whitebirdlaw.com", "Gregory White", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Amphion Law, P.A.", "amphionlaw.com", "Matthew Amphion", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("FL", "The Ticktin Law Group (Deerfield Beach)", "legalbrains.com", "Peter Ticktin", "Foreclosure Defense & Civil Litigation", 2, "/contact/"),

    # TEXAS (Collin, Denton, Williamson, Fort Bend, Montgomery, Bexar, Travis)
    ("TX", "Koester Law Firm, P.C.", "koesterlawfirm.com", "Kurt Koester", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TX", "The Barrows Firm, P.C. (Southlake)", "barrowsfirm.com", "Leslie Barrows", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Underwood Perkins, P.C.", "uplawtx.com", "David Underwood", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "The Francis Firm", "francisfirm.com", "Michael Francis", "Civil Trial Practice & Recovery", 4, "/contact/"),
    ("TX", "Noteboom The Law Firm", "noteboomlaw.com", "Chuck Noteboom", "Civil Trial Practice", 4, "/contact/"),
    ("TX", "Patterson Law Group", "pattersonpersonalinjury.com", "Travis Patterson", "Civil Trial Practice", 4, "/contact/"),
    ("TX", "Varghese Summersett PLLC", "versustexas.com", "Benson Varghese", "Civil Trial & Asset Protection", 4, "/contact/"),
    ("TX", "Crestman & Associates, P.C.", "crestmanlaw.com", "Mark Crestman", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Strong Firm P.C. (The Woodlands)", "thestrongfirm.com", "Bret Strong", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Gauntt, Koen, Binney & Kidd, LLP", "gkbk.com", "Chad Gauntt", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("TX", "Dossey & Jones, PLLC", "dosseyjones.com", "Jim Dossey", "Probate, Estate Planning & Real Estate", 3, "/contact/"),
    ("TX", "Hope & Causey, P.C.", "hopeandcausey.com", "John Causey", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "The Jurek Law Group (Sugar Land)", "jureklaw.com", "Michael Jurek", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Romano & Sumner (Sugar Land)", "romanosumner.com", "Kenny Sumner", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Riddle & Butts (Sugar Land)", "riddlebutts.com", "Christine Butts", "Probate, Estate & Heirship Litigation", 3, "/contact/"),
    ("TX", "The Curley Law Firm (Sugar Land)", "thecurleylawfirm.com", "Adam Curley", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("TX", "Frazier & Frazier (Sugar Land)", "frazierlaw.com", "Robert Frazier", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Pollard Firm (Round Rock)", "pollardfirm.com", "Brad Pollard", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Springer Law Firm (Georgetown)", "springer-law.com", "Sarah Springer", "Probate, Estate & Civil Litigation", 3, "/contact/"),
    ("TX", "Farner & Lawson (Round Rock)", "farnerlawson.com", "Thomas Lawson", "Probate, Trust & Estate Planning", 3, "/contact/"),
    ("TX", "Baysinger & Green (Round Rock)", "baysingergreen.com", "Kyle Baysinger", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TX", "Scanlan, Buckle & Young, P.C.", "sbylaw.com", "David Buckle", "Real Estate, Probate & Tax Law", 3, "/contact/"),
    ("TX", "The Evans Law Firm", "austintxelderlaw.com", "David Evans", "Probate & Estate Administration", 3, "/contact/"),
    ("TX", "Barnett & Leuty, P.C.", "barnettleuty.com", "David Leuty", "Real Estate, Probate & Business Law", 3, "/contact/"),
    ("TX", "The Jones Law Firm (Round Rock)", "thejoneslawfirm.com", "Craig Jones", "Real Estate Litigation & Foreclosure", 2, "/contact/"),
    ("TX", "Meyers & Meyers, PLLC", "meyersandmeyerslaw.com", "David Meyers", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Law Office of David S. Kohm (Arlington)", "kohm.com", "David Kohm", "Foreclosure Defense & Real Estate", 2, "/contact/"),
    ("TX", "Toronjo & Prosser Law (Dallas)", "dallasbankruptcylaw.com", "Joshua Toronjo", "Foreclosure Defense & Distressed Debt", 2, "/contact/"),
    ("TX", "Bailey & Galyen (Fort Worth)", "galyen.com", "Phillip Galyen", "Foreclosure Defense & Probate", 2, "/contact/"),
    ("TX", "Rubin & Associates (Dallas)", "rubinlawfirm.com", "Ron Rubin", "Foreclosure Defense & Debt Relief", 2, "/contact/"),

    # CALIFORNIA (Orange County, San Diego, Riverside, Bay Area, Sacramento)
    ("CA", "Giammichele Law (Irvine)", "giammichelelaw.com", "Michael Giammichele", "Estate Planning & Probate Litigation", 3, "/contact/"),
    ("CA", "Modern Wealth Law (Costa Mesa)", "modernwealthlaw.com", "John Wong", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("CA", "The Legacy Lawyers (Torrance)", "thelegacylawyers.com", "Philip Kavesh", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("CA", "Crockett & Ante (Palm Desert)", "crockett-law.com", "David Crockett", "Real Estate, Probate & Trust Litigation", 3, "/contact/"),
    ("CA", "The Heritage Law Group (San Jose)", "theheritagelawgroup.com", "Douglas Jacobs", "Probate, Estate & Real Estate", 3, "/contact/"),
    ("CA", "James F. Roberts & Associates (Anaheim)", "webuildyourtrust.com", "James Roberts", "Probate & Trust Administration", 3, "/contact/"),
    ("CA", "Magee & Adler (Long Beach)", "mageeadler.com", "Eric Adler", "Probate, Trust & Conservatorship", 3, "/contact/"),
    ("CA", "Kehr Law (San Diego)", "kehrlaw.com", "Brian Kehr", "Real Estate, Corporate & Probate", 3, "/contact/"),
    ("CA", "Scott C. Soady (San Diego)", "soadylaw.com", "Scott Soady", "Estate Planning & Asset Recovery", 3, "/contact/"),
    ("CA", "Antonyan Miranda (San Diego)", "expertdivorce.com", "Ilona Antonyan", "Complex Asset Division & Real Estate", 4, "/contact/"),
    ("CA", "Shustak Reynolds (San Diego)", "shustak.com", "Erwin Shustak", "Commercial Trial & Asset Disputes", 4, "/contact/"),
    ("CA", "The McClellan Law Firm (San Diego)", "mcclellanlaw.com", "Craig McClellan", "Civil Trial & Complex Recovery", 4, "/contact/"),
    ("CA", "CaseyGerry (San Diego)", "caseygerry.com", "David Casey", "Civil Trial Practice & Property Law", 4, "/contact/"),
    ("CA", "Thorsnes Bartolotta (San Diego)", "tbmlawyers.com", "Vincent Bartolotta", "Eminent Domain & Real Estate Trial", 1, "/contact/"),
    ("CA", "Gomez Trial Attorneys (San Diego)", "thegomezfirm.com", "John Gomez", "Civil Trial & Complex Recovery", 4, "/contact/"),
    ("CA", "Hinch Newman (San Diego)", "hinchnewman.com", "Richard Newman", "Civil Litigation & Commercial Practice", 4, "/contact/"),
    ("CA", "Bohm Wildish & Matsen (Costa Mesa)", "bohmwildish.com", "James Bohm", "Real Estate Litigation, Probate & Estate", 3, "/contact/"),
    ("CA", "Brown & Streza (Irvine)", "brownandstreza.com", "Matthew Brown", "Estate Planning, Tax & Real Estate", 3, "/contact/"),
    ("CA", "Rishwain & Rishwain (Stockton)", "rishwainlaw.com", "Brian Rishwain", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("CA", "Freeman, Freeman & Smiley (Century City)", "ffslaw.com", "Bradley Smiley", "Real Estate, Trusts & Estates", 3, "/contact/"),
    ("CA", "Bird Marella (Los Angeles)", "birdmarella.com", "Terry Bird", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("CA", "Hueston Hennigan (Los Angeles)", "hueston.com", "John Hueston", "Trial Practice & Commercial Disputes", 4, "/contact/"),
    ("CA", "Kendall Brill & Kelly (Los Angeles)", "kbkfirm.com", "Richard Kendall", "Trial Practice & Real Estate Litigation", 4, "/contact/"),
    ("CA", "Miller Barondess (Los Angeles)", "millerbarondess.com", "Louis Miller", "Commercial Litigation & Real Estate Trial", 4, "/contact/"),
    ("CA", "Kaplan Marino (Beverly Hills)", "kaplanmarino.com", "Nina Marino", "White Collar & Asset Forfeiture", 4, "/contact/"),
    ("CA", "Glaser & Associates (Los Angeles)", "glaserlawoffices.com", "Steven Glaser", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("CA", "Advocate Legal (Los Angeles)", "advocatelegal.com", "David Brown", "Foreclosure Defense & Wrongful Foreclosure", 2, "/contact/"),
    ("CA", "Consumer Action Law Group (Glendale)", "consumeractionlawgroup.com", "Lauren Rode", "Foreclosure Defense & Consumer Rights", 2, "/contact/"),
    ("CA", "David A. Boone Law (San Jose)", "boonelaw.com", "David Boone", "Foreclosure Defense & Real Estate", 2, "/contact/"),
    ("CA", "Rincon Law Group (San Diego)", "rinconlawgroup.com", "German Rincon", "Real Estate Litigation & Civil Defense", 4, "/contact/"),

    # GEORGIA (Cobb, Gwinnett, DeKalb, Fulton, Chatham, Richmond)
    ("GA", "Berman Fink Van Horn (Atlanta)", "bfvlaw.com", "Benjamin Fink", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Krevolin & Horst (Atlanta)", "khlawfirm.com", "Douglas Krevolin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Bloom Parham (Atlanta)", "bloom-law.com", "Stephen Parham", "Real Estate Litigation & Land Disputes", 1, "/contact/"),
    ("GA", "Schulten Ward Turner & Weiss (Atlanta)", "swtlaw.com", "Kevin Ward", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("GA", "Scrudder Bass (Atlanta)", "scrudderbass.com", "Glenn Bass", "Civil Trial & Real Estate", 4, "/contact/"),
    ("GA", "Weinberg Wheeler (Atlanta)", "wwhgd.com", "David Dial", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("GA", "Hawkins Parnell (Atlanta)", "hpylaw.com", "Jack Sibley", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Carlock Copeland (Atlanta)", "carlockcopeland.com", "Thomas Carlock", "Civil Trial & Real Estate", 4, "/contact/"),
    ("GA", "The Saylor Law Firm (Atlanta)", "saylorlaw.com", "Linda Saylor", "Probate, Estate & Heirship Litigation", 3, "/contact/"),
    ("GA", "Hungeling Law (Atlanta)", "hungelinglaw.com", "David Hungeling", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("GA", "Duncan Adams Law (Atlanta)", "duncanadamslaw.com", "Duncan Adams", "Real Estate Litigation & Quiet Title", 1, "/contact/"),
    ("GA", "The Finley Firm (Columbus)", "thefinleyfirm.com", "Benjamin Finley", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Stiles & Associates (Alpharetta)", "stileslaw.com", "Kevin Stiles", "Real Estate Litigation & Title Clearance", 1, "/contact/"),
    ("GA", "Lueder, Larkin & Hunter (Tucker)", "luederlaw.com", "John Lueder", "Real Estate, HOA & Foreclosure", 2, "/contact/"),
    ("GA", "Lipshutz Greenblatt (Atlanta)", "lgattorneys.com", "Randall Lipshutz", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("GA", "Lazega & Johanson (Atlanta)", "ljlaw.com", "Jay Lazega", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("GA", "Perrie & Associates (Marietta)", "perrielaw.com", "Robert Perrie", "Real Estate, Title & Probate", 3, "/contact/"),
    ("GA", "Weinstock & Scavo (Atlanta)", "wslaw.net", "Michael Weinstock", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "NowackHoward (Atlanta)", "nowackhoward.com", "Julie Howard", "HOA Foreclosure & Real Estate", 2, "/contact/"),
    ("GA", "Gowens, Price & Associates (Stockbridge)", "gowensprice.com", "Michael Gowens", "Real Estate Litigation & Title", 1, "/contact/"),
    ("GA", "Paul Black Law (Atlanta)", "paulblacklaw.com", "Paul Black", "Probate, Trust & Estate Litigation", 3, "/contact/"),
    ("GA", "Hurban Law (Lawrenceville)", "hurbanlaw.com", "Gabriel Hurban", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("GA", "O'Kelley & Sorohan (Duluth)", "oslawllc.com", "Joe O'Kelley", "Real Estate, Title Clearance & Foreclosure", 1, "/contact/"),
    ("GA", "Cook & James (Roswell)", "cookandjames.com", "Kara Cook", "Real Estate Litigation & Title", 1, "/contact/"),
    ("GA", "Gaslowitz Frankel (Atlanta)", "gaslowitzfrankel.com", "Adam Gaslowitz", "Fiduciary, Estate & Trust Litigation", 3, "/contact/"),
    ("GA", "The Farrell Law Firm (Marietta)", "farrellfirm.com", "Patrick Farrell", "Probate, Estate Planning & Real Estate", 3, "/contact/"),

    # NORTH CAROLINA (Wake, Mecklenburg, Guilford, Forsyth, Buncombe, New Hanover)
    ("NC", "Poyner Spruill (Raleigh)", "poynerspruill.com", "Dan Cahill", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Wyrick Robbins (Raleigh)", "wyrick.com", "Jimmy Yates", "Real Estate Litigation & Commercial Law", 4, "/contact/"),
    ("NC", "Manning Fulton (Raleigh)", "manningfulton.com", "Barry Mann", "Real Estate, Eminent Domain & Litigation", 1, "/contact/"),
    ("NC", "Schell Bray (Greensboro)", "schellbray.com", "Michael Schell", "Real Estate, Estate Planning & Probate", 3, "/contact/"),
    ("NC", "Tuggle Duggins (Greensboro)", "tuggleduggins.com", "Richard Tuggle", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Higgins Benjamin (Greensboro)", "greensborolaw.com", "John Higgins", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Johnston Allison (Charlotte)", "jahlaw.com", "David Gilpin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "James McElroy (Charlotte)", "jmdlaw.com", "Marshall Yoder", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("NC", "Horack Talley (Charlotte)", "horacktalley.com", "Keith Nichols", "Real Estate Litigation & HOA Law", 2, "/contact/"),
    ("NC", "Moon Wright (Charlotte)", "mwhlaw.com", "Richard Wright", "Insolvency, Creditors Rights & Real Estate", 1, "/contact/"),
    ("NC", "Cranfill Sumner (Raleigh)", "cshlaw.com", "Marshall Wall", "Real Estate Litigation & Civil Defense", 4, "/contact/"),
    ("NC", "Young Moore (Raleigh)", "youngmoorelaw.com", "David Duke", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("NC", "Teague Campbell (Raleigh)", "teaguecampbell.com", "Dayle Flammia", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Tharrington Smith (Raleigh)", "tharringtonsmith.com", "Hill Allen", "Real Estate Litigation & Education Law", 4, "/contact/"),
    ("NC", "Cheshire Parker (Raleigh)", "cheshirepark.com", "Joseph Cheshire", "Civil Trial & Asset Forfeiture", 4, "/contact/"),
    ("NC", "Roberts & Stevens (Asheville)", "roberts-stevens.com", "Marc Rudow", "Real Estate Litigation & Probate", 1, "/contact/"),
    ("NC", "Van Winkle Law (Asheville)", "vwlawfirm.com", "Larry McDevitt", "Real Estate Litigation, Probate & Title", 1, "/contact/"),
    ("NC", "McGuire Wood (Asheville)", "mwbavl.com", "Sabrina Rockoff", "Real Estate, Estate Planning & Litigation", 3, "/contact/"),
    ("NC", "Ferikes & Bleynat (Asheville)", "ashevillelitigators.com", "Edward Bleynat", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Hutchens Law Firm (Fayetteville)", "hutchenslawfirm.com", "Terry Hutchens", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),

    # TENNESSEE (Davidson, Shelby, Knox, Hamilton, Rutherford, Williamson)
    ("TN", "Gullett Sanford (Nashville)", "gsrm.com", "Phillip Young", "Real Estate Litigation & Estate Planning", 3, "/contact/"),
    ("TN", "Dodson Parker (Nashville)", "dodsonparker.com", "Harlan Dodson", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Leitner Williams (Chattanooga)", "leitnerfirm.com", "Paul Leitner", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Chambliss Bahner (Chattanooga)", "chamblisslaw.com", "Mark Turner", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Miller & Martin (Chattanooga)", "millermartin.com", "Scott Parrish", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Luther-Anderson (Chattanooga)", "lutheranderson.com", "William Luther", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Gearhiser Peters (Chattanooga)", "gearhiserpeters.com", "Wayne Peters", "Real Estate, Probate & Tax Litigation", 3, "/contact/"),
    ("TN", "Patrick Beard (Chattanooga)", "pbsjlaw.com", "Gary Patrick", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("TN", "Speek Webb (Chattanooga)", "speekandwebb.com", "Jerry Speek", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("TN", "Evans Petree (Memphis)", "evanspetree.com", "Joseph Walker", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("TN", "Glankler Brown (Memphis)", "glankler.com", "Michael Coury", "Insolvency, Real Estate & Creditors Rights", 1, "/contact/"),
    ("TN", "Burch Porter (Memphis)", "bpjlaw.com", "Les Jones", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("TN", "Harris Shelton (Memphis)", "harrisshelton.com", "Brett Hughes", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("TN", "Martin Tate (Memphis)", "martintate.com", "Lee Piovarcy", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Apperson Crump (Memphis)", "appersoncrump.com", "Albert Harvey", "Real Estate, Probate & Trial Litigation", 3, "/contact/"),
    ("TN", "Pietrangelo Cook (Memphis)", "plegal.com", "John Cook", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("TN", "Kramer Rayson (Knoxville)", "kramer-rayson.com", "John Johnson", "Real Estate, Probate & Employment", 3, "/contact/"),
    ("TN", "Woolf McClane (Knoxville)", "wmbac.com", "Chadwick Hatmaker", "Real Estate Litigation & Tax", 1, "/contact/"),
    ("TN", "Egerton McAfee (Knoxville)", "emlaw.com", "Cheryl Rice", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Bernstein Stair (Knoxville)", "bsmlaw.com", "Bernard Bernstein", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
]

print(f"Loaded {len(EXPANSION_CANDIDATES_R4)} round 4 expansion candidates.")
