"""Round 2 Expansion: Additional High-Quality Law Practices across Top 6 States"""

EXPANSION_CANDIDATES = [
    # FLORIDA (Tampa, Orlando, South Florida, Jacksonville, Panhandle)
    ("FL", "Perenich, Caulfield, Avril & Noyes, P.A.", "usalaw.com", "Mark Perenich", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Florin|Roebig, P.A.", "florinroebig.com", "Wil H. Florin", "Civil Trial & Property Disputes", 4, "/contact/"),
    ("FL", "Roman & Gaynor", "romangaynor.com", "Mark Roman", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("FL", "Alley, Clark & Greiwe", "tampatriallawyers.com", "C. Todd Alley", "Civil Trial & Complex Litigation", 4, "/contact/"),
    ("FL", "Wagner McLaughlin Whittemore", "wagnerlaw.com", "Alan Wagner", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "Yerrid Law Firm", "yerridlaw.com", "C. Steven Yerrid", "Civil Trial Practice & Asset Recovery", 4, "/contact/"),
    ("FL", "Buell & Elligett, P.A.", "belaw.com", "Mark Buell", "Eminent Domain & Real Estate Litigation", 1, "/contact/"),
    ("FL", "Swope, Rodante P.A.", "swoperodante.com", "Dale Swope", "Civil Trial & Insurance Bad Faith", 4, "/contact/"),
    ("FL", "Ficarrotta & Ficarrotta, P.A.", "ficarrottalaw.com", "Frank Ficarrotta", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("FL", "The Solomon Law Group, P.A.", "solomonlaw.com", "Hamilton Solomon", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Barr, Murman & Tonelli, P.A.", "barrmurman.com", "Keith Barr", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("FL", "Gunn Law Group, P.A.", "gunnlawgroup.com", "Lee D. Gunn", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Beytin, McLaughlin, McLaughlin, O'Hara & Bocchino, P.A.", "law-fla.com", "Mark McLaughlin", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "Bivins & Hemenway, P.A.", "bhappe.com", "Robert Bivins", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("FL", "Gibbons Neuman, P.A.", "gibbonsneuman.com", "Stephen Gibbons", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Fowler, O'Quinn, Feeney & Sneed, P.A.", "fowleroquinn.com", "Mark Fowler", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "The Rosenthal Firm", "rosenthalcounsel.com", "Alex Rosenthal", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "ZinnLaw, PLLC (Fort Myers)", "zinnlaw.com", "Brian Zinn", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Roetzel & Andress (Fort Myers)", "ralaw.com", "Paul Giordano", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Hahn Loeser & Parks (Naples)", "hahnlaw.com", "Mark Fischer", "Real Estate Litigation & Estate Planning", 3, "/contact-us/"),
    ("FL", "Bond, Schoeneck & King (Naples)", "bsk.com", "Dennis Brown", "Trusts, Estates & Real Estate", 3, "/contact-us/"),
    ("FL", "Quarles & Brady (Naples)", "quarles.com", "Bradley Rigor", "Real Estate & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Cummings & Lockwood (Bonita Springs)", "cl-law.com", "William Wright", "Trusts, Estates & Real Estate", 3, "/contact-us/"),
    ("FL", "Henderson Franklin (Bonita Springs)", "henlaw.com", "Russell Schropp", "Real Estate Litigation & Distressed Property", 1, "/contact/"),
    ("FL", "Pavese Law (Cape Coral)", "paveselaw.com", "Christopher Shields", "Real Estate, Probate & Land Title", 3, "/contact/"),
    ("FL", "Knott Ebelini Hart (Fort Myers)", "knott-law.com", "George Knott", "Real Estate Litigation & Land Law", 1, "/contact/"),
    ("FL", "Woodward Pires & Lombardo (Marco Island)", "wpl-legal.com", "Craig Woodward", "Real Estate, Probate & Land Use", 3, "/contact/"),
    ("FL", "Grant Fridkin Pearson (Naples)", "gfpac.com", "Jeffrey Fridkin", "Real Estate Litigation & Probate Disputes", 1, "/contact/"),
    ("FL", "Laird A. Lile PLLC (Naples)", "lairdalile.com", "Laird Lile", "Probate, Trust & Estate Litigation", 3, "/contact/"),
    ("FL", "Weldon & Rothman (Naples)", "weldonrothman.com", "Bradley Weldon", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "Cardillo Keith & Bonaquist (Naples)", "ckblaw.com", "William Keith", "Real Estate & Estate Planning", 3, "/contact/"),
    ("FL", "Salvatori Wood Buckel (Naples)", "swbl-law.com", "Leo Salvatori", "Real Estate, Probate & Land Title", 3, "/contact/"),
    ("FL", "Goede DeBoest & Cross (Naples)", "gadclaw.com", "John Goede", "Real Estate, HOA & Foreclosure", 2, "/contact/"),
    ("FL", "Older Lundy Koch & Martino (Tampa)", "olalaw.com", "Benjamin Lundy", "Probate, Estate & Civil Litigation", 3, "/contact-us/"),
    ("FL", "Sachs Sax Caplan (Boca Raton)", "ssclawfirm.com", "Peter Sachs", "Real Estate & HOA Foreclosure", 2, "/contact/"),
    ("FL", "Padula Bennardo Levine (Boca Raton)", "pbl-law.com", "Stephen Padula", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Katzman Chandler (Fort Lauderdale)", "katzmanchandler.com", "Leigh Katzman", "Real Estate, HOA & Foreclosure", 2, "/contact/"),
    ("FL", "Shapiro Blasi Wasserman & Hermann (Boca Raton)", "sbwh.law", "Michael Wasserman", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("FL", "Lavalle Brown & Ronan (Boca Raton)", "lavallebrown.com", "Charles Lavalle", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("FL", "Boyer Law Firm (Miami)", "boyerlawfirm.com", "Francis Boyer", "Real Estate, Probate & Surplus", 1, "/contact/"),
    ("FL", "Ansbacher Law (Jacksonville)", "ansbacher.net", "Barry Ansbacher", "Real Estate, Title & Foreclosure", 1, "/contact/"),
    ("FL", "Fisher Tousey Leas & Medina (Jacksonville)", "fishertousey.com", "Mark Leas", "Estate Planning, Tax & Real Estate", 3, "/contact/"),
    ("FL", "Donahoo & McMenamy (Jacksonville)", "dmjaxlaw.com", "John Donahoo", "Estate Planning, Probate & Real Estate", 3, "/contact/"),
    ("FL", "Campione & Hackney (Leesburg)", "campionelaw.com", "Mark Campione", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("FL", "Bowen & Schroth (Eustis)", "bowenschroth.com", "Derek Schroth", "Real Estate & Local Government", 4, "/contact/"),
    ("FL", "McLin Burnsed (The Villages)", "mclinburnsed.com", "Mark Burnsed", "Real Estate, Estate Planning & Probate", 3, "/contact/"),
    ("FL", "Crawford Modica & O'Keefe (Clermont)", "cmo-law.com", "Timothy Crawford", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Stone & Gerken (Montverde)", "stoneandgerken.com", "Richard Stone", "Real Estate & Probate Law", 3, "/contact/"),
    ("FL", "Gaylord & Rogers (Eustis)", "gaylordrogers.com", "Kevin Rogers", "Real Estate Litigation & Title", 4, "/contact/"),
    ("FL", "Potter Clement Lowery (Spring Hill)", "potterclement.com", "Charles Clement", "Real Estate, Probate & Title", 3, "/contact/"),

    # TEXAS (Dallas, Houston, Austin, San Antonio, Fort Worth, El Paso, Collin County)
    ("TX", "Goff & Goff, PLLC (San Antonio)", "gofflawtexas.com", "Russell Goff", "Real Estate, Title & Foreclosure", 2, "/contact/"),
    ("TX", "Barton, East & Caldwell (San Antonio)", "beclaw.com", "David Barton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Langley & Banack (San Antonio)", "langleybanack.com", "Arthur Banack", "Real Estate, Probate & Title", 3, "/contact/"),
    ("TX", "Thornton, Biechlin, Reynolds & Guerra (San Antonio)", "thorntonfirm.com", "Robert Biechlin", "Civil Trial & Real Estate", 4, "/contact/"),
    ("TX", "Curney, Farmer, House, Osuna & Jackson (San Antonio)", "curneyfarmer.com", "David Farmer", "Civil Litigation & Trial Law", 4, "/contact/"),
    ("TX", "Plunkett, Griesenbeck & Elizabeth (San Antonio)", "pgelaw.com", "Lewin Plunkett", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("TX", "Schmoyer Reinhard (San Antonio)", "sr-lawfirm.com", "Shannon Schmoyer", "Civil Trial Practice", 4, "/contact/"),
    ("TX", "Davis, Cedillo & Mendoza (San Antonio)", "dcmf.com", "Ricardo Cedillo", "Complex Real Estate Trial", 4, "/contact/"),
    ("TX", "Goode Casseb Jones (San Antonio)", "goodelaw.com", "Richard Riklin", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TX", "Brock Person Guerra Reyna (San Antonio)", "brockperson.com", "Roy Brock", "Civil Trial & Real Estate", 4, "/contact/"),
    ("TX", "Kemp Smith LLP (El Paso)", "kempsmith.com", "Ken Slavin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Mounce, Green, Myers (El Paso)", "mgmsg.com", "Bruce Safi", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("TX", "Ray, McChristian & Jeans (El Paso)", "rmjfirm.com", "Jeff Ray", "Civil Trial Practice", 4, "/contact/"),
    ("TX", "ScottHulse PC (El Paso)", "scotthulse.com", "David Bernard", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Underwood Law Firm (Amarillo)", "underwoodlawfirm.com", "Gavin Gadberry", "Real Estate, Tax & Trial Law", 1, "/contact/"),
    ("TX", "Sprouse Shrader Smith (Amarillo)", "sprouselaw.com", "Joel Sprouse", "Real Estate & Probate Law", 3, "/contact/"),
    ("TX", "Mullin Hoard & Brown (Amarillo)", "mhba.com", "David Mullin", "Banking & Creditors Rights", 1, "/contact/"),
    ("TX", "Crenshaw, Dupree & Milam (Lubbock)", "cdmlaw.com", "Cecil Kuhne", "Real Estate & Trial Law", 4, "/contact/"),
    ("TX", "McCleskey, Harriger, Brazill & Graf (Lubbock)", "mccleskeylaw.com", "Jerry Kolander", "Real Estate & Probate", 3, "/contact/"),
    ("TX", "Naman, Howell, Smith & Lee (Waco)", "namanhowell.com", "Larry Brady", "Real Estate, Tax & Creditors Rights", 1, "/contact/"),
    ("TX", "Pakis, Giotes, Page & Burleson (Waco)", "pakislaw.com", "David Deaconson", "Real Estate, Probate & Litigation", 3, "/contact/"),
    ("TX", "Haley & Olson (Waco)", "haleyolson.com", "Blake Rasner", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("TX", "Beard Kultgen Brophy (Waco)", "beardkultgen.com", "David Dickson", "Real Estate & Probate", 3, "/contact/"),
    ("TX", "Bickerstaff Heath Delgado Acosta (Austin)", "bickerstaff.com", "Robert Heath", "Real Estate & Public Law", 4, "/contact/"),
    ("TX", "McGinnis Lochridge (Austin)", "mcginnislaw.com", "Doug Dodds", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Armbrust & Brown (Austin)", "abaustin.com", "David Armbrust", "Real Estate Development & Litigation", 4, "/contact/"),
    ("TX", "Allensworth (Austin)", "allensworthlaw.com", "Will Allensworth", "Construction & Real Estate Litigation", 4, "/contact/"),
    ("TX", "DuBois, Bryant & Campbell (Austin)", "dbcllp.com", "Rick DuBois", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("TX", "Wright & Greenhill (Austin)", "wrightgreenhill.com", "Heidi Coughlin", "Civil Trial & Real Estate", 4, "/contact/"),
    ("TX", "Richards Rodriguez & Skeith (Austin)", "rrsfirm.com", "Dan Richards", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("TX", "George Brothers Kincaid & Horton (Austin)", "gbkh.com", "Douglas Brothers", "Trial Practice & Real Estate Disputes", 4, "/contact/"),
    ("TX", "Scott Douglass & McConnico (Austin)", "scottdoug.com", "Steve McConnico", "Real Estate & Commercial Trial", 4, "/contact/"),
    ("TX", "Enoch Kever PLLC (Austin)", "enochkever.com", "Craig Enoch", "Appellate & Real Estate Trial", 4, "/contact/"),
    ("TX", "Welder Leshin LLP (Corpus Christi)", "welderleshin.com", "Leo Welder", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Porter, Rogers, Dahlman & Gordon (Corpus Christi)", "prdg.com", "Charles Gordon", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("TX", "Wood, Boykin & Wolter (Corpus Christi)", "woodboykin.com", "Rick Wolter", "Real Estate Litigation & Title", 1, "/contact/"),
    ("TX", "Chaves, Gonzales & Hoblit (Corpus Christi)", "cghlaw.com", "Tony Chaves", "Civil Trial & Real Estate", 4, "/contact/"),
    ("TX", "MehaffyWeber (Beaumont)", "mehaffyweber.com", "Barbara Barron", "Commercial Litigation & Real Estate", 4, "/contact/"),
    ("TX", "Germer PLLC (Beaumont)", "germer.com", "Lawrence Germer", "Civil Trial & Real Estate", 4, "/contact/"),
    ("TX", "Strong Pipkin Bissell & Ledyard (Beaumont)", "strongpipkin.com", "Michael Baker", "Civil Trial Practice", 4, "/contact/"),
    ("TX", "Orgain Bell & Tucker (Beaumont)", "obt.com", "John Johnson", "Real Estate Litigation & Title", 1, "/contact/"),
    ("TX", "Benckenstein & Oxford (Beaumont)", "benoxford.com", "Hubert Oxford", "Real Estate & Probate", 3, "/contact/"),
    ("TX", "Cantey Hanger (Dallas)", "canteyhanger.com", "Michael Appleman", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TX", "Griffith, Jay & Carman (Fort Worth)", "gjclaw.com", "John Griffith", "Real Estate Litigation & Land Title", 4, "/contact/"),
    ("TX", "Kelly Hart & Hallman (Fort Worth)", "kellyhart.com", "Marianne Auld", "Real Estate & Commercial Litigation", 1, "/contact/"),
    ("TX", "McDonald Sanders (Fort Worth)", "mcdonaldlaw.com", "Peter Green", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Decker Jones (Fort Worth)", "deckerjones.com", "Adam Fulkerson", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("TX", "Moses, Palmer & Howell (Fort Worth)", "mph-law.com", "Tim Howell", "Real Estate Litigation & Land Title", 1, "/contact/"),
    ("TX", "Harris, Finley & Bogle (Fort Worth)", "hfblaw.com", "Dee Finley", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("TX", "Bourland, Wall & Wenzel (Fort Worth)", "bwwlaw.com", "Michael Bourland", "Probate, Estate, Tax & Real Estate", 3, "/contact/"),

    # CALIFORNIA (San Diego, Orange County, Inland Empire, Central Valley, Bay Area)
    ("CA", "Gurnee Mason Rushford Bonotto (Roseville)", "gurneelaw.com", "Steven Gurnee", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("CA", "Boutin Jones Inc. (Sacramento)", "boutinjones.com", "Stephen Boutin", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("CA", "Murphy Austin Easton (Sacramento)", "murphyaustin.com", "Lisa Austin", "Real Estate, Construction & Probate", 3, "/contact/"),
    ("CA", "Wilke Fleury (Sacramento)", "wilkefleury.com", "Steven Fass", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("CA", "Somach Simmons & Dunn (Sacramento)", "somachlaw.com", "Stuart Somach", "Water Rights & Real Estate", 4, "/contact/"),
    ("CA", "Trainor Fairbrook (Sacramento)", "trainorfairbrook.com", "Charles Trainor", "Commercial Real Estate & Title", 1, "/contact/"),
    ("CA", "Diepenbrock Elkin (Sacramento)", "diepenbrock.com", "Mark McCandless", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("CA", "Wagner Kirkman Blaine (Sacramento)", "wkbk.com", "Douglas Youmans", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("CA", "Kershaw, Cook & Talley (Sacramento)", "kctlegal.com", "William Kershaw", "Complex Civil Litigation", 4, "/contact/"),
    ("CA", "Dreyer Babich Buccola (Sacramento)", "dbbwc.com", "Joseph Babich", "Trial Practice & Asset Recovery", 4, "/contact/"),
    ("CA", "Freeman Firm (Stockton)", "freemanfirm.com", "Lee Rosenthal", "Real Estate, Agriculture & Probate", 3, "/contact/"),
    ("CA", "Shore McKinley Conger (Stockton)", "smcjlendinglaw.com", "John McKinley", "Banking & Real Estate", 1, "/contact/"),
    ("CA", "Herum Crabtree Suntag (Stockton)", "herumcrabtree.com", "Steven Herum", "Real Estate Litigation & Eminent Domain", 1, "/contact/"),
    ("CA", "Kroloff Belcher Smart (Stockton)", "kroloff.com", "Christopher Christopherson", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("CA", "Neumiller & Beardslee (Stockton)", "neumiller.com", "George Petrulakis", "Real Estate & Land Use", 4, "/contact/"),
    ("CA", "Damrell Nelson Schrimp (Modesto)", "damrell.com", "Frank Damrell", "Real Estate & Agriculture", 4, "/contact/"),
    ("CA", "McCormick Barstow (Fresno)", "mccormickbarstow.com", "David McNamara", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("CA", "Baker Manock & Jensen (Fresno)", "bakermanock.com", "Dirk Paloutzian", "Real Estate, Water & Probate", 3, "/contact/"),
    ("CA", "Sagaser, Watkins & Wieland (Fresno)", "sw2law.com", "Howard Sagaser", "Civil Trial & Commercial Litigation", 4, "/contact/"),
    ("CA", "Wanger Jones Helsley (Fresno)", "wjhattorneys.com", "Oliver Wanger", "Real Estate, Water & Commercial Trial", 4, "/contact/"),
    ("CA", "Borton Petrini (Bakersfield)", "bortonpetrini.com", "Mark Jones", "Real Estate, Foreclosure Defense & Probate", 2, "/contact/"),
    ("CA", "Clifford & Brown (Bakersfield)", "clifford-brownlaw.com", "Patrick Osborn", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("CA", "Klein DeNatale Goldner (Fresno)", "kleinlaw.com", "David Cooper", "Real Estate & Tax Default Surplus", 1, "/contact/"),
    ("CA", "LeBeau-Thelen (Bakersfield)", "lebeauthelen.com", "Thomas Thelen", "Real Estate & Probate", 3, "/contact/"),
    ("CA", "Young Wooldridge (Bakersfield)", "youngwooldridge.com", "Ernest Conant", "Real Estate, Water & Trial Practice", 4, "/contact/"),
    ("CA", "Gresham Savage Nolan (Riverside)", "greshamsavage.com", "Mark Ostoich", "Real Estate & Land Use", 4, "/contact/"),
    ("CA", "Reid & Hellyer (Riverside)", "rhlaw.com", "Michael Kerbs", "Insolvency, Real Estate & Creditors Rights", 1, "/contact/"),
    ("CA", "Varner & Brandt (Riverside)", "varnerbrandt.com", "Bruce Varner", "Real Estate, Corporate & Probate", 3, "/contact/"),
    ("CA", "Stream Kim Hicks (Riverside)", "streamkim.com", "Theodore Stream", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("CA", "Wagner Zemming Sutter (Riverside)", "wzsfirm.com", "Michael Wagner", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "The Blue Law Group (Rancho Cucamonga)", "thebluelawgroup.com", "Michael Blue", "Foreclosure Defense & Real Estate", 2, "/contact/"),
    ("CA", "Holstrom, Block & Parke (Corona)", "hbplaw.com", "Dayn Holstrom", "Estate Planning & Probate", 3, "/contact/"),
    ("CA", "CunninghamLegal (Pasadena)", "cunninghamlegal.com", "James Cunningham", "Probate, Trust & Real Estate", 3, "/contact/"),
    ("CA", "Barash & Silverman (Tarzana)", "barashlaw.com", "David Barash", "Foreclosure Defense & Real Estate", 2, "/contact/"),
    ("CA", "Mellor Law Firm (Riverside)", "mellorlawfirm.com", "Mark Mellor", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("CA", "Stephen R. Wade (Claremont)", "stephenwadelaw.com", "Stephen Wade", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("CA", "Talamantes Associates (Chula Vista)", "talamanteslaw.com", "Laura Talamantes", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("CA", "Peter M. Hartley (San Diego)", "hartleylaw.com", "Peter Hartley", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("CA", "The Sterling Law Group (Roseville)", "sterlinglawgroup.net", "Michael Sterling", "Probate & Estate Administration", 3, "/contact/"),
    ("CA", "Giammichele Law (Irvine)", "giammichelelaw.com", "Michael Giammichele", "Estate Planning & Probate Litigation", 3, "/contact/"),
    ("CA", "Modern Wealth Law (Costa Mesa)", "modernwealthlaw.com", "John Wong", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("CA", "The Legacy Lawyers (Torrance)", "thelegacylawyers.com", "Philip Kavesh", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("CA", "Crockett & Ante (Palm Desert)", "crockett-law.com", "David Crockett", "Real Estate, Probate & Trust Litigation", 3, "/contact/"),
    ("CA", "The Heritage Law Group (San Jose)", "theheritagelawgroup.com", "Douglas Jacobs", "Probate, Estate & Real Estate", 3, "/contact/"),
    ("CA", "James F. Roberts & Associates (Anaheim)", "webuildyourtrust.com", "James Roberts", "Probate & Trust Administration", 3, "/contact/"),
    ("CA", "Magee & Adler (Long Beach)", "mageeadler.com", "Eric Adler", "Probate, Trust & Conservatorship", 3, "/contact/"),
    ("CA", "Kehr Law (San Diego)", "kehrlaw.com", "Brian Kehr", "Real Estate, Corporate & Probate", 3, "/contact/"),
    ("CA", "Scott C. Soady (San Diego)", "soadylaw.com", "Scott Soady", "Estate Planning & Asset Recovery", 3, "/contact/"),
    ("CA", "Antonyan Miranda (San Diego)", "expertdivorce.com", "Ilona Antonyan", "Complex Asset Division & Real Estate", 4, "/contact/"),
    ("CA", "Shustak Reynolds (San Diego)", "shustak.com", "Erwin Shustak", "Commercial Trial & Asset Disputes", 4, "/contact/"),

    # GEORGIA (Atlanta, Savannah, Macon, Columbus, Augusta, North GA)
    ("GA", "Andersen, Tate & Carr (Duluth)", "atclawfirm.com", "Thomas Tate", "Real Estate Litigation & Eminent Domain", 1, "/contact/"),
    ("GA", "Chandler, Britt & Jay (Buford)", "cbjlawfirm.com", "Walter Chandler", "Real Estate & Land Use", 4, "/contact/"),
    ("GA", "Mahaffey Pickens Tucker (Lawrenceville)", "mptlawfirm.com", "Steven Pickens", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("GA", "Fox, Chandler, Homans (Gainesville)", "foxchandler.com", "David Fox", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Stewart, Melvin & Frost (Gainesville)", "smf-law.com", "Douglas Stewart", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("GA", "Hulsey, Oliver & Mahar (Gainesville)", "homlaw.com", "Thomas Mahar", "Real Estate Litigation & Title", 1, "/contact/"),
    ("GA", "Whelchel, Dunlap, Jarrard (Gainesville)", "wdjwlaw.com", "Thomas Walker", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("GA", "Moore, Clarke, DuVall (Albany)", "mcdr-law.com", "Kimberly Clarke", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("GA", "Watson Spence (Albany)", "watsonspence.com", "Mark Watson", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Langdale Vallotton (Valdosta)", "langdalelaw.com", "William Langdale", "Real Estate & Probate", 3, "/contact/"),
    ("GA", "Coleman Talley (Valdosta)", "colemantalley.com", "Justin Scott", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Tillman & Tillman (Valdosta)", "tillmanlaw.com", "Wallace Tillman", "Real Estate, Probate & Title", 3, "/contact/"),
    ("GA", "Young, Thagard, Hoffmann (Valdosta)", "youngthagard.com", "Thomas Young", "Civil Trial Practice & Real Estate", 4, "/contact/"),
    ("GA", "Glover & Davis (Newnan)", "gloverdavis.com", "Littleton Glover", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Berman Fink Van Horn (Atlanta)", "bfvlaw.com", "Benjamin Fink", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Krevolin & Horst (Atlanta)", "khlawfirm.com", "Douglas Krevolin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Bloom Parham (Atlanta)", "bloom-law.com", "Stephen Parham", "Real Estate Litigation & Land Disputes", 1, "/contact/"),
    ("GA", "Schulten Ward Turner & Weiss (Atlanta)", "swtlaw.com", "Kevin Ward", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("GA", "Scrudder Bass (Atlanta)", "scrudderbass.com", "Glenn Bass", "Civil Trial & Real Estate", 4, "/contact/"),
    ("GA", "Weinberg Wheeler (Atlanta)", "wwhgd.com", "David Dial", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("GA", "Hawkins Parnell (Atlanta)", "hpylaw.com", "Jack Sibley", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Carlock Copeland (Atlanta)", "carlockcopeland.com", "Thomas Carlock", "Civil Trial & Real Estate", 4, "/contact/"),
    ("GA", "The Saylor Law Firm (Atlanta)", "saylorlaw.com", "Linda Saylor", "Probate, Estate & Heirship Litigation", 3, "/contact/"),
    ("GA", "Hungeling Law (Atlanta)", "hungelinglaw.com", "David Hungeling", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("GA", "Duncan Adams Law (Atlanta)", "duncanadamslaw.com", "Duncan Adams", "Real Estate Litigation & Quiet Title", 1, "/contact/"),
    ("GA", "The Finley Firm (Columbus)", "thefinleyfirm.com", "Benjamin Finley", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Stiles & Associates (Alpharetta)", "stileslaw.com", "Kevin Stiles", "Real Estate Litigation & Title Clearance", 1, "/contact/"),
    ("GA", "Lueder, Larkin & Hunter (Tucker)", "luederlaw.com", "John Lueder", "Real Estate, HOA & Foreclosure", 2, "/contact/"),
    ("GA", "Lipshutz Greenblatt (Atlanta)", "lgattorneys.com", "Randall Lipshutz", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("GA", "Lazega & Johanson (Atlanta)", "ljlaw.com", "Jay Lazega", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("GA", "Perrie & Associates (Marietta)", "perrielaw.com", "Robert Perrie", "Real Estate, Title & Probate", 3, "/contact/"),
    ("GA", "Weinstock & Scavo (Atlanta)", "wslaw.net", "Michael Weinstock", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "NowackHoward (Atlanta)", "nowackhoward.com", "Julie Howard", "HOA Foreclosure & Real Estate", 2, "/contact/"),
    ("GA", "Gowens, Price & Associates (Stockbridge)", "gowensprice.com", "Michael Gowens", "Real Estate Litigation & Title", 1, "/contact/"),
    ("GA", "Paul Black Law (Atlanta)", "paulblacklaw.com", "Paul Black", "Probate, Trust & Estate Litigation", 3, "/contact/"),
    ("GA", "Hurban Law (Lawrenceville)", "hurbanlaw.com", "Gabriel Hurban", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("GA", "O'Kelley & Sorohan (Duluth)", "oslawllc.com", "Joe O'Kelley", "Real Estate, Title Clearance & Foreclosure", 1, "/contact/"),
    ("GA", "Cook & James (Roswell)", "cookandjames.com", "Kara Cook", "Real Estate Litigation & Title", 1, "/contact/"),
    ("GA", "Gaslowitz Frankel (Atlanta)", "gaslowitzfrankel.com", "Adam Gaslowitz", "Fiduciary, Estate & Trust Litigation", 3, "/contact/"),
    ("GA", "The Farrell Law Firm (Marietta)", "farrellfirm.com", "Patrick Farrell", "Probate, Estate Planning & Real Estate", 3, "/contact/"),

    # NORTH CAROLINA (Charlotte, Raleigh, Triad, Coastal, Mountains)
    ("NC", "Battle, Winslow, Scott (Rocky Mount)", "battlewinslow.com", "Brian Scott", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("NC", "Sumrell Sugg (New Bern)", "sumrellsugg.com", "James Sugg", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("NC", "White & Allen (Kinston)", "whiteandallen.com", "Gray Johnsey", "Real Estate, Probate, Tax & Title", 3, "/contact/"),
    ("NC", "Taft, Taft & Haigler (Greenville)", "taftlawfirm.com", "Thomas Taft", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Hardee, Massey & Blount (Greenville)", "hardeemasseylaw.com", "Charles Hardee", "Civil Trial Practice", 4, "/contact/"),
    ("NC", "Teague, Rotenstreich (Greensboro)", "trslaw.com", "Paul Rotenstreich", "Civil Trial & Property Defense", 4, "/contact/"),
    ("NC", "Hill Evans Jordan (Greensboro)", "hejb.com", "Karl Hill", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("NC", "Sharpless & Stavola (Greensboro)", "sharpless-stavola.com", "Frederick Sharpless", "Civil Trial & Real Estate Litigation", 4, "/contact/"),
    ("NC", "Forman Rossabi Black (Greensboro)", "frb-law.com", "Amiel Rossabi", "Real Estate Litigation & HOA Practice", 2, "/contact/"),
    ("NC", "Henson & Talley (Greensboro)", "hensontalley.com", "Perry Henson", "Civil Litigation & Trial Defense", 4, "/contact/"),
    ("NC", "Adams, Howell (Cary)", "adamshowell.com", "Douglas Howell", "Real Estate, Title Clearance & Foreclosure", 1, "/contact/"),
    ("NC", "Blanco Tackabery (Winston-Salem)", "blancolaw.com", "Peter Juran", "Real Estate, Probate & Tax Litigation", 3, "/contact/"),
    ("NC", "Craige Jenkins Liipfert (Winston-Salem)", "craigejenkins.com", "Gordon Jenkins", "Real Estate, Probate & Title", 3, "/contact/"),
    ("NC", "Allman Spry (Winston-Salem)", "allmanspry.com", "Edwin Allman", "Real Estate, Probate & Land Use", 3, "/contact/"),
    ("NC", "Bennett & Guthrie (Winston-Salem)", "bennett-guthrie.com", "Richard Bennett", "Civil Trial & Real Estate", 4, "/contact/"),
    ("NC", "Hendrick Bryant (Winston-Salem)", "hendricklawfirm.com", "Matthew Hendrick", "Eminent Domain, Real Estate & Trial", 1, "/contact/"),
    ("NC", "Morrow Porter Vermitsky (Winston-Salem)", "mpvlaw.com", "John Morrow", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("NC", "Stowers & Nardone (Winston-Salem)", "stowerslaw.com", "David Stowers", "Real Estate Litigation & Foreclosure", 2, "/contact/"),
    ("NC", "Cheryl David Law (Greensboro)", "cheryldavid.com", "Cheryl David", "Probate, Estate Planning & Trust Law", 3, "/contact/"),
    ("NC", "Ragsdale Liggett (Raleigh)", "rl-law.com", "Frank Liggett", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("NC", "Hatch, Little & Bunn (Raleigh)", "hatchlittlebunn.com", "William Hatch", "Real Estate Litigation & HOA Foreclosure", 2, "/contact/"),
    ("NC", "Harris Sarratt & Hodges (Raleigh)", "hshlawfirm.com", "Donald Harris", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("NC", "Batten Lee (Raleigh)", "battenlee.com", "Kenneth Batten", "Civil Trial & Property Litigation", 4, "/contact/"),
    ("NC", "Ellis & Winters (Raleigh)", "elliswinters.com", "Leslie Packer", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("NC", "Burns, Day & Presnell (Raleigh)", "bdp-law.com", "James Burns", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("NC", "Jordan Price Wall (Raleigh)", "jordanprice.com", "Henry Jones", "Real Estate, HOA & Administrative Law", 2, "/contact/"),
    ("NC", "Nichols, Choi & Lee (Raleigh)", "ncl-law.com", "Jackson Nichols", "Administrative Law & Property Disputes", 4, "/contact/"),
    ("NC", "Hedrick Kepley (High Point)", "hedrickkepley.com", "Jeffrey Hedrick", "Real Estate, Probate & Commercial Law", 3, "/contact/"),
    ("NC", "Vann Attorneys (Raleigh)", "vannattorneys.com", "James Vann", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Hopler, Wilms, & Hanna (Durham)", "hoplerwilms.com", "Adam Hopler", "Probate, Estate & Real Estate", 3, "/contact/"),
    ("NC", "Kennon Craver (Durham)", "kennoncraver.com", "Joel Craig", "Real Estate Litigation & Land Use", 1, "/contact/"),
    ("NC", "Pulley, Watson (Durham)", "pulleywatson.com", "Tracy Lischer", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Baddour, Parker (Goldsboro)", "baddourparker.com", "Philip Baddour", "Civil Trial Practice", 4, "/contact/"),
    ("NC", "Everett Gaskins Hancock (Raleigh)", "eghlaw.com", "Ed Gaskins", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("NC", "Cauley Pridgen (Wilson)", "cauleypridgen.com", "James Cauley", "Real Estate, Municipal & Land Use", 4, "/contact/"),
    ("NC", "Rose Harrison Gilreath (Kill Devil Hills)", "outerbankslaw.com", "John Harrison", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("NC", "Shipman & Wright (Wilmington)", "shipmanlaw.com", "Gary Shipman", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("NC", "Crossley McIntosh (Wilmington)", "cmclawfirm.com", "Douglas Collier", "Civil Trial & Real Estate", 4, "/contact/"),
    ("NC", "Rountree Losee (Wilmington)", "rountreelosee.com", "George Rountree", "Real Estate Litigation & Maritime", 4, "/contact/"),
    ("NC", "Marshall, Williams & Gorham (Wilmington)", "mwglawfirm.com", "Lonnie Williams", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("NC", "Hodges & Coxe (Wilmington)", "hodgescoxe.com", "Bradley Coxe", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("NC", "Murchison, Taylor & Gibson (Wilmington)", "murchisontaylor.com", "Michael Murchison", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Lea/Schultz Law (Wilmington)", "leaschultzlaw.com", "James Lea", "Civil Trial & Property Litigation", 4, "/contact/"),
    ("NC", "Craige & Fox (Wilmington)", "craigeandfox.com", "Lauren Fox", "Real Estate, Probate & Civil Litigation", 3, "/contact/"),
    ("NC", "Hogue Hill (Wilmington)", "hoguehill.com", "David Hill", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("NC", "Block, Crouch (Wilmington)", "bcklaw.com", "Christopher Keeter", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Woodruff & Associates (Raleigh)", "woodrufflawfirm.com", "Gordon Woodruff", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("NC", "The Law Corner (Raleigh)", "thelawcorner.com", "Brent Adams", "Real Estate, Foreclosure & Family Law", 2, "/contact/"),
    ("NC", "Brady Law Firm (Cary)", "bradylawnc.com", "Charles Brady", "Real Estate, HOA & Title Law", 2, "/contact/"),
    ("NC", "Allen, Stahl & Kilbourne (Asheville)", "asklawnc.com", "James Kilbourne", "Real Estate Litigation & Title Law", 1, "/contact/"),

    # TENNESSEE (Nashville, Memphis, Knoxville, Chattanooga, Tri-Cities)
    ("TN", "Trauger & Tuke (Nashville)", "trauger-tuke.com", "Byron Trauger", "Real Estate Litigation & Public Agency", 4, "/contact/"),
    ("TN", "Ortale Kelley Herbert (Nashville)", "ortalekelley.com", "Daniel Herbert", "Real Estate Litigation & Insurance", 4, "/contact/"),
    ("TN", "Lieff Cabraser (Nashville)", "lieffcabraser.com", "Mark Chalos", "Complex Trial & Asset Recovery", 4, "/contact/"),
    ("TN", "Manier & Herod (Nashville)", "manierherod.com", "Michael Evans", "Surety, Insolvency & Real Estate", 1, "/contact/"),
    ("TN", "White & Reasor (Nashville)", "whitereasor.com", "David White", "Real Estate, Probate & Corporate", 3, "/contact/"),
    ("TN", "Spicer Rudstrom (Nashville)", "spicerfirm.com", "Marc Dedman", "Real Estate Litigation & Insurance Defense", 4, "/contact/"),
    ("TN", "Batson Nolan (Clarksville)", "batsonnolan.com", "Dan Nolan", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Cunningham, Mitchell (Clarksville)", "cmrlegal.com", "Mark Mitchell", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("TN", "Rainey, Kizer (Jackson)", "raineykizer.com", "Russell Reviere", "Real Estate Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Waldrop & Hall (Jackson)", "waldrophall.com", "David Hall", "Real Estate, Probate & Civil Law", 3, "/contact/"),
    ("TN", "Pentecost, Glenn (Jackson)", "pgmlawfirm.com", "James Pentecost", "Civil Trial Practice", 4, "/contact/"),
    ("TN", "Hunter, Smith & Davis (Kingsport)", "hsdlaw.com", "Mark Dessauer", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Wilson Worley (Kingsport)", "wilsonworley.com", "Richard Currie", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "Herndon, Coleman (Johnson City)", "hcblaw.com", "Matthew Bolton", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TN", "Milligan & Coleman (Greeneville)", "milligancoleman.com", "Mark Cowan", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("TN", "The Higgins Firm (Nashville)", "higginsfirm.com", "Jim Higgins", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("TN", "Cole Law Group (Brentwood)", "colelawgrouppc.com", "Peter Cole", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TN", "Rogers, Kamm & Shea (Nashville)", "rkslawgroup.com", "Helen Rogers", "Probate, Asset Division & Litigation", 3, "/contact/"),
    ("TN", "Bednarz & Bednarz (Nashville)", "bednarzlaw.com", "Joe Bednarz", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("TN", "Kinnard Law (Nashville)", "kinnardlaw.com", "Randall Kinnard", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("TN", "Rocky McElhaney Law (Nashville)", "rockylawfirm.com", "Rocky McElhaney", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("TN", "Hughes & Coleman (Nashville)", "hughesandcoleman.com", "Lee Coleman", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Pohl & Berk (Nashville)", "pohlandberk.com", "Mark Pohl", "Civil Trial Practice & Asset Disputes", 4, "/contact/"),
    ("TN", "Rutherford, DeMarco (Nashville)", "rdwlawfirm.com", "David Rutherford", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "McNabb, Bragorgos (Memphis)", "mbb-law.com", "Leland McNabb", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Glassman, Wyatt (Memphis)", "glassmanfirm.com", "Richard Glassman", "Civil Trial & Commercial Litigation", 4, "/contact/"),
    ("TN", "Bailey & Greer (Memphis)", "baileygreer.com", "Thomas Greer", "Civil Trial Practice & Property Law", 4, "/contact/"),
    ("TN", "Donati Law (Memphis)", "donatilaw.com", "Donald Donati", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Farris Bobango (Memphis)", "farrisbobango.com", "John Bobango", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "The Crone Law Firm (Memphis)", "cronelawfirmplc.com", "Alan Crone", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("TN", "Tune, Entrekin & White (Nashville)", "tewlaw.com", "Peter White", "Real Estate, Eminent Domain & Land Use", 1, "/contact/"),
    ("TN", "Thompson Burton (Franklin)", "thompsonburton.com", "Walt Burton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Story, Abernathy & Campbell (Franklin)", "storyabernathy.com", "David Story", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "Duncan, Hatcher, Fleenor (Chattanooga)", "dhf-law.com", "Phillip Fleenor", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Cavin & O'Herren (Knoxville)", "cavinoherren.com", "David Cavin", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Grant, Konvalinka & Harrison (Chattanooga)", "gkhpc.com", "John Anderson", "Real Estate Litigation, Tax & Probate", 1, "/contact/"),
]

print(f"Loaded {len(EXPANSION_CANDIDATES)} round 2 expansion candidates.")
