"""Round 6 Expansion: Targeted State Depth (TN, NC, TX, GA, CA)"""

EXPANSION_CANDIDATES_R6 = [
    # TENNESSEE (Knoxville, Chattanooga, Tri-Cities, Middle TN)
    ("TN", "O'Neil, Parker & Williamson, PLLC", "opw.com", "M. Douglas Murchison", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Frantz, McConnell & Seymour, LLP", "fmsllp.com", "Robert L. Kahn", "Real Estate Litigation, Probate & Title", 1, "/contact/"),
    ("TN", "Taylor & Knight, GP", "taylorknightlaw.com", "Arthur G. Seymour", "Civil Trial & Property Defense", 4, "/contact/"),
    ("TN", "Watson, Roach, Bickers & Bush, PLC", "watsonroach.com", "Robert H. Watson", "Civil Trial & Local Government", 4, "/contact/"),
    ("TN", "Paine, Tarwater, Bickers, LLP", "painelaw.com", "Dwight E. Tarwater", "Civil Trial Practice & Complex Litigation", 4, "/contact/"),
    ("TN", "Ritchie, Dillard, Davies & Johnson, P.C.", "rddjlaw.com", "Wade Davies", "Civil Trial & Asset Defense", 4, "/contact/"),
    ("TN", "Banks & Jones", "banksjones.com", "T. Scott Jones", "Civil Trial Practice", 4, "/contact/"),
    ("TN", "Eldridge & Cagle, PLLC", "eldridgeandcagle.com", "David M. Eldridge", "Trial Practice & Real Estate Disputes", 4, "/contact/"),
    ("TN", "Fox & Farmer Attorneys at Law", "foxandfarmerlaw.com", "Jerry Fox", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("TN", "Menefee & Brown, P.C.", "menefeebrown.com", "Mark Menefee", "Real Estate, Probate & Corporate", 3, "/contact/"),
    ("TN", "Holbrook Peterson Smith PLLC", "hpslawgroup.com", "David Peterson", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TN", "Ambrose, Wilson, Grimm & Durand, LLP", "awgd.com", "John Wilson", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("TN", "Gentry, Tipton & McLemore, P.C.", "gtmlaw.com", "Maurice Guinn", "Insolvency, Creditors Rights & Real Estate", 1, "/contact/"),
    ("TN", "Spiva & Horner, LLP", "spivahorner.com", "Howard Spiva", "Civil Trial Practice", 4, "/contact/"),
    ("TN", "McCord & Weintraub, P.C.", "mccordweintraub.com", "Keith McCord", "Real Estate & Estate Litigation", 3, "/contact/"),
    ("TN", "Baker, O'Kane & Thompson, PLLC", "botlaw.com", "Thomas Baker", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Law Offices of Tony Farmer & John Dreiser", "farmerdreiser.com", "Tony Farmer", "Civil Trial Practice", 4, "/contact/"),
    ("TN", "Butler, Vines and Babb, P.L.L.C.", "bvblaw.com", "James Vines", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("TN", "Lacy, Price & Mynatt, P.C.", "lpmlaw.org", "Wayne Lacy", "Real Estate, Probate & Civil Law", 3, "/contact/"),
    ("TN", "Tarpy, Cox, Fleishman & Leveille, P.L.L.C.", "tcfl-law.com", "Arthur Tarpy", "Real Estate Litigation & Corporate", 4, "/contact/"),

    # NORTH CAROLINA (Triad, Triangle, Sandhills, Coastal)
    ("NC", "Sharpe & Savrann, P.A.", "sharpeandsavrann.com", "David Sharpe", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("NC", "Hatch, Little & Bunn (Raleigh)", "hatchlittlebunn.com", "William Hatch", "Real Estate & HOA Foreclosure", 2, "/contact/"),
    ("NC", "Farris & Thomas Law", "farristhomas.com", "Robert Farris", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("NC", "Poyner Spruill LLP (Southern Pines)", "poynerspruill.com", "Dan Cahill", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("NC", "Van Camp, Meacham & Newman, PLLC", "vancamplaw.com", "James Van Camp", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Rowland & Yauger, Attorneys at Law", "rowlandyauger.com", "Michael Rowland", "Civil Trial & Foreclosure Defense", 2, "/contact/"),
    ("NC", "Staton, Fisher & Conover, P.A.", "statonlawfirm.com", "William Staton", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("NC", "Doster, Post, Silverman & Foushee, P.A.", "dosterpost.com", "Kevin Foushee", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("NC", "Wilson, Reives, Silverman & Doran, PLLC", "wilsonreiveslaw.com", "Jesse Reives", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("NC", "Gunn & Messick, PLLC", "gunnmessick.com", "Paul Messick", "Real Estate, Probate & Local Government", 3, "/contact/"),
    ("NC", "Moody, Williams, Atwater & Lee", "nctrianglelawyers.com", "Gerald Moody", "Civil Trial Practice & Property Law", 4, "/contact/"),
    ("NC", "Holcomb & Holcomb, P.A.", "holcomblaw.net", "David Holcomb", "Real Estate, Probate & Title Clearance", 1, "/contact/"),
    ("NC", "Walker, Lambe, Rhudy, Costley & Gill, PLLC", "walkerlambe.com", "O.E. Lambe", "Trusts, Estates & Real Estate", 3, "/contact/"),
    ("NC", "Twiford Law Firm, P.C.", "twifordlaw.com", "Edward Twiford", "Real Estate, Probate & Maritime Law", 3, "/contact/"),
    ("NC", "Hornthal, Riley, Ellis & Maland, L.L.P.", "hrem.com", "L.P. Hornthal", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("NC", "Sharp, Graham, Baker & Maupin, LLP", "obxlaw.com", "Russell Maupin", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("NC", "Aldridge, Seawell, Runyan, Theobald & Boettcher, LLP", "outerbankslawfirm.com", "Jerry Aldridge", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("NC", "Thompson & Ludlum, LLP", "thompsonludlum.com", "David Thompson", "Real Estate & Probate Law", 3, "/contact/"),
    ("NC", "Beavers, Holt & Sternlicht, P.A.", "beaversholt.com", "Mark Sternlicht", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Hutchens Law Firm (Charlotte)", "hutchenslawfirm.com", "Terry Hutchens", "Foreclosure & Real Estate Practice", 1, "/contact/"),

    # TEXAS (Dallas-Fort Worth, Central Texas, South Texas)
    ("TX", "The Farah Law Firm (Mansfield)", "farahlawfirm.com", "Nabil Farah", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("TX", "Brackett & Ellis, P.C.", "brackettsellis.com", "Michael Ellis", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("TX", "Bourland, Heflin, Alvarez, Minor & Matthews, PLC", "bourlandheflin.com", "Richard Bourland", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Harris, Finley & Bogle (Fort Worth)", "hfblaw.com", "Dee Finley", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("TX", "Pope, Hardwicke, Christie, Barksdale & Kelly, L.L.P.", "popehardwicke.com", "Bryan Kelly", "Eminent Domain & Real Estate Litigation", 1, "/contact/"),
    ("TX", "Brown, Proctor & Howell, L.L.P.", "bphlaw.com", "Robert Howell", "Civil Trial & Real Estate Defense", 4, "/contact/"),
    ("TX", "Gurney & Gurney, P.C.", "gurneylaw.com", "David Gurney", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("TX", "Curnutt & Hafer, LLP", "curnutthafer.com", "Doug Hafer", "Commercial Litigation & Real Estate Trial", 4, "/contact/"),
    ("TX", "The Blum Firm, P.C.", "theblumfirm.com", "Marvin E. Blum", "Estate Planning, Probate & Tax Litigation", 3, "/contact/"),
    ("TX", "Law Office of J. Kevin Clark (Fort Worth)", "fortworthdivorcelawyer.com", "Kevin Clark", "Asset Division & Probate Litigation", 3, "/contact/"),
    ("TX", "The Law Office of Robert E. Luedke (Fort Worth)", "luedkelaw.com", "Robert Luedke", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Ross & Matthews, P.C.", "rossandmatthews.com", "David Ross", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("TX", "The Law Offices of Eric A. Dupree", "dupreelaw.com", "Eric Dupree", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("TX", "KoonsFuller (Plano)", "koonsfuller.com", "Charla Bradshaw", "Complex Asset Division & Property Litigation", 3, "/contact/"),
    ("TX", "Albin Oldner Law (Plano)", "albinoldnerlaw.com", "Mark Albin", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Saunders, Walsh & Beard (McKinney)", "saunderswalsh.com", "Mark Walsh", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Warmbrodt & Associates, P.L.L.C.", "warmbrodtlaw.com", "Randall Warmbrodt", "Asset Division & Estate Law", 3, "/contact/"),
    ("TX", "The Nacol Law Firm (Dallas)", "nacollawfirm.com", "Mark Nacol", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("TX", "Shead & Associates (Dallas)", "sheadlaw.com", "David Shead", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("TX", "The Gonzalez Law Firm (Plano)", "gonzalezlawtx.com", "Al Gonzalez", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),

    # GEORGIA (Suburban Atlanta, Central & South GA)
    ("GA", "Moore Ingram Johnson & Steele, LLP", "mijs.com", "John Moore", "Real Estate Litigation, Land Title & Probate", 1, "/contact/"),
    ("GA", "Barnes & Thornburg LLP (Atlanta)", "btlaw.com", "John T.L. Koenig", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("GA", "Balch & Bingham LLP (Atlanta)", "balch.com", "Stan Blanton", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("GA", "Nelson Mullins Riley & Scarborough (Atlanta)", "nelsonmullins.com", "Michael Hollingsworth", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("GA", "Baker Donelson (Atlanta)", "bakerdonelson.com", "Linda Klein", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("GA", "Burr & Forman LLP (Atlanta)", "burr.com", "Erich Durlacher", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Chamberlain Hrdlicka (Atlanta)", "chamberlainlaw.com", "David Aughtry", "Tax Controversy & Real Estate Practice", 1, "/contact/"),
    ("GA", "Bradley Arant Boult Cummings (Atlanta)", "bradley.com", "Sidney Nurkin", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("GA", "Maynard Nexsen (Atlanta)", "maynardnexsen.com", "Jeff Friedman", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("GA", "Taylor English Duma (Atlanta)", "taylorenglish.com", "Marc Taylor", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Swift Currie (Atlanta)", "swiftcurrie.com", "Terry Brantley", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Drew Eckl (Atlanta)", "deflaw.com", "Joseph Chancey", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Freeman Mathis (Atlanta)", "fmglaw.com", "Ben Mathis", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("GA", "Goodman McGuffey (Atlanta)", "gm-llp.com", "Robert Luskin", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("GA", "Hall Booth Smith (Atlanta)", "hallboothsmith.com", "John Hall", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("GA", "HunterMaclean (Savannah)", "huntermaclean.com", "Bradford Johnson", "Real Estate Litigation & Probate", 1, "/contact/"),
    ("GA", "Oliver Maner (Savannah)", "olivermaner.com", "Patrick O'Connor", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Bouhan Falligant (Savannah)", "bouhan.com", "Benjamin Karpf", "Real Estate, Estate Planning & Litigation", 1, "/contact/"),
    ("GA", "Weiner Shearouse (Savannah)", "wswgs.com", "William Shearouse", "Real Estate, Probate & Title", 3, "/contact/"),
    ("GA", "Hull Barrett (Augusta)", "hullbarrett.com", "Mark Burgess", "Real Estate, Probate & Trial Law", 3, "/contact/"),

    # CALIFORNIA (Central Coast, Silicon Valley, Inland Empire)
    ("CA", "Mullen & Henzell L.L.P.", "mullenlaw.com", "Mack S. Staton", "Real Estate, Estate Planning & Trial Law", 3, "/contact/"),
    ("CA", "Fell, Marking, Abkin, Montgomery, Granet & Raney, LLP", "fmam.com", "David Granet", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("CA", "Seed Mackall LLP", "seedmackall.com", "Peter Seed", "Real Estate & Business Litigation", 4, "/contact/"),
    ("CA", "Griffith & Thornburgh, LLP", "griffiththornburgh.com", "John Thornburgh", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("CA", "Reicker, Pfau, Pyle & McRoy LLP", "rppmh.com", "Michael Pfau", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Price, Postel & Parma LLP", "ppplaw.com", "Craig Postel", "Real Estate, Water, Tax & Probate Law", 3, "/contact/"),
    ("CA", "Rogers, Sheffield & Campbell, LLP", "rogerssheffield.com", "Travis Logue", "Real Estate Litigation & Estate Planning", 3, "/contact/"),
    ("CA", "Cappello & Noël LLP", "cappellonoel.com", "A. Barry Cappello", "Lender Liability, Real Estate & Trial Law", 1, "/contact/"),
    ("CA", "Buena Park Real Estate Law Group", "buenaparklaw.com", "David Buena", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("CA", "Law Offices of Michael D. Kwasigroch (Simi Valley)", "kwaslaw.com", "Michael Kwasigroch", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
]

print(f"Loaded {len(EXPANSION_CANDIDATES_R6)} round 6 expansion candidates.")
