"""Round 3 Expansion: Unique Boutique Law Firms across Top 6 States"""

EXPANSION_CANDIDATES_R3 = [
    # FLORIDA BOUTIQUES (Unique Domains)
    ("FL", "Boyd Richards Parker & Colonnelli, P.L.", "boydrichards.com", "John Richards", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Vernis & Bowling", "florida-law.com", "Robert Bowling", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("FL", "Goldberg & Rosen, P.A.", "goldbergandrosen.com", "Judd Rosen", "Civil Trial Practice & Recovery", 4, "/contact/"),
    ("FL", "Haggard Law Firm", "haggardlawfirm.com", "Michael Haggard", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Rossman, Baumberger, Reboso & Spier, P.A.", "rbrlaw.com", "Manuel Reboso", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "Podhurst Orseck, P.A.", "podhurst.com", "Steven Marks", "Complex Trial Litigation", 4, "/contact/"),
    ("FL", "Grossman Roth Yaffa Cohen, P.A.", "grossmanroth.com", "Stuart Grossman", "Civil Trial & Recovery", 4, "/contact/"),
    ("FL", "Colson Hicks Eidson", "colson.com", "Dean Colson", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "Panter, Panter & Sampedro, P.A.", "panterlaw.com", "Brett Panter", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Dolan Dobrinsky Rosenblum Bluestein, LLP", "ddrblaw.com", "Daniel Dolan", "Civil Trial Practice", 4, "/contact/"),
    ("FL", "Silva & Silva, P.A.", "silvasilva.com", "Carlos Silva", "Civil Trial & Asset Disputes", 4, "/contact/"),
    ("FL", "Stewart Tilghman Fox Bianchi & Cain, P.A.", "stfblaw.com", "David Bianchi", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("FL", "Alvarez, Carbonell, Feltman & Da Silva", "acfdlaw.com", "Paul Feltman", "Real Estate Litigation & Insurance", 4, "/contact/"),
    ("FL", "Lydecker LLP", "lydecker.com", "Richard Lydecker", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("FL", "Zumpano Patricios, P.A.", "zplaw.com", "Joseph Zumpano", "Complex Litigation & Asset Recovery", 4, "/contact/"),
    ("FL", "Diaz Reus International Law Firm", "diazreus.com", "Michael Diaz", "Asset Recovery & Creditors Rights", 1, "/contact/"),
    ("FL", "Rivero Mestre LLP", "riveromestre.com", "Jorge Mestre", "Complex Commercial & Real Estate Trial", 4, "/contact/"),
    ("FL", "Sequor Law, P.A.", "sequorlaw.com", "Edward Davis", "Asset Recovery & Financial Litigation", 1, "/contact/"),
    ("FL", "Perlman, Bajandas, Yevoli & Albright, P.L.", "pbyalaw.com", "Paul Albright", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "AXS Law Group, PLLC", "axslawgroup.com", "Jeremy Hart", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Shubin & Bass, P.A.", "shubinbass.com", "John Shubin", "Real Estate, Land Use & Appellate", 1, "/contact/"),
    ("FL", "Bercow Radell Fernandez Larkin & Tapanes, PLLC", "brzoninglaw.com", "Jeffrey Bercow", "Real Estate, Zoning & Land Title", 1, "/contact/"),
    ("FL", "Lehtinen Schultz PLLC", "leschultz.com", "Dexter Lehtinen", "Real Estate Litigation & Environmental", 4, "/contact/"),
    ("FL", "Sanchez-Medina, Gonzalez, Quesada, Lage, Gomez & Machado LLP", "smgqlaw.com", "Roland Sanchez-Medina", "Real Estate, Banking & Corporate", 1, "/contact/"),
    ("FL", "Perez-Roura Law", "perezrouralaw.com", "Pedro Perez-Roura", "Real Estate, Probate & Estate Planning", 3, "/contact/"),
    ("FL", "The Soto Law Group (Fort Lauderdale)", "sotolawgroup.com", "Alexander Soto", "Real Estate Litigation & Title", 1, "/contact/"),
    ("FL", "Ritter Chusid (Boca Raton)", "ritterchusid.com", "Gregory Ritter", "Real Estate & Commercial Trial", 4, "/contact/"),
    ("FL", "Haliczer Pettis Schwamm (Fort Lauderdale)", "hpslegal.com", "James Haliczer", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Padgett Law Group (Tallahassee)", "padgettlawgroup.com", "David Padgett", "Foreclosure & Real Estate Practice", 1, "/contact/"),
    ("FL", "Gilbert Garcia Group (Tampa)", "gilbertgrouplaw.com", "Michelle Garcia Gilbert", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),

    # TEXAS BOUTIQUES (Unique Domains)
    ("TX", "Ahmad, Zavitsanos & Mensing PLLC", "azalaw.com", "Joe Ahmad", "Complex Commercial & Real Estate Trial", 4, "/contact/"),
    ("TX", "Susman Godfrey L.L.P.", "susmangodfrey.com", "Neal Manne", "Trial Practice & Commercial Disputes", 4, "/contact/"),
    ("TX", "McKool Smith", "mckoolsmith.com", "Mike McKool", "Trial Practice & Commercial Litigation", 4, "/contact/"),
    ("TX", "Reid Collins & Tsai LLP", "reidcollins.com", "Bill Reid", "Financial Recovery & Insolvency Litigation", 1, "/contact/"),
    ("TX", "Yetter Coleman LLP", "yettercoleman.com", "Paul Yetter", "Complex Real Estate & Commercial Trial", 4, "/contact/"),
    ("TX", "Porter Hedges LLP", "porterhedges.com", "Rob Reedy", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Andrews Myers, P.C.", "andrewsmyers.com", "Ben Westcott", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Roberts Markel Weinberg Butler Hailey PC", "rmwbh.com", "Marc Markel", "Real Estate, HOA & Foreclosure", 2, "/contact/"),
    ("TX", "Hirsch & Westheimer, P.C. (Houston)", "hirschwest.com", "Eric Lipper", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("TX", "BoyarMiller (Houston)", "boyarmiller.com", "Chris Miller", "Real Estate Litigation & Corporate", 4, "/contact/"),
    ("TX", "Weycer Kaplan (Houston)", "wkpz.com", "Mark Kaplan", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Hoover Slovacek (Houston)", "hooverslovacek.com", "Joseph Slovacek", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Sullins Johnston (Houston)", "sjrm.com", "Robert Johnston", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Pagel Davis Hill (Houston)", "pdhlaw.com", "David Pagel", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Crady Jewett McCulley (Houston)", "cjmhlaw.com", "Bob McCulley", "Real Estate, Probate & Tax", 3, "/contact/"),
    ("TX", "Ytterberg Deery Knull (Houston)", "ydklaw.com", "Alan Ytterberg", "Probate, Trust & Estate Planning", 3, "/contact/"),
    ("TX", "Fizer Beck (Houston)", "fizerbeck.com", "David Beck", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("TX", "MacIntyre McCulloch (Houston)", "mmslawhouston.com", "John Stanfield", "Probate & Estate Administration", 3, "/contact/"),
    ("TX", "Burdette & Rice (Dallas)", "dallasprobateattorneys.com", "Brian Rice", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("TX", "Pyke & Associates (Dallas)", "pyke-associates.com", "David Pyke", "Probate & Estate Administration", 3, "/contact/"),
    ("TX", "Albin Oldner Law (Frisco)", "albinoldnerlaw.com", "Mark Albin", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Schaefer Law Firm (Plano)", "schaeferfirm.com", "David Schaefer", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("TX", "Farah Law Firm (Arlington)", "farahlawfirm.com", "Nabil Farah", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("TX", "Ashmore Law Firm (Dallas)", "ashmorelaw.com", "Gary Ashmore", "Probate, Estate & Civil Litigation", 3, "/contact/"),
    ("TX", "Moses Palmer & Howell (Fort Worth)", "mph-law.com", "Tim Howell", "Real Estate Litigation & Land Title", 1, "/contact/"),
    ("TX", "Barlow Garsek & Pou (Fort Worth)", "bgp-law.com", "David Pou", "Real Estate, Banking & Litigation", 1, "/contact/"),
    ("TX", "Whitaker Chalk (Fort Worth)", "whitakerchalk.com", "Robert Schwartz", "Real Estate, Probate & Litigation", 3, "/contact/"),
    ("TX", "KoonsFuller (Dallas)", "koonsfuller.com", "Ike Vanden Eykel", "Complex Property Division & Trial", 3, "/contact/"),
    ("TX", "Ticer Law (Dallas)", "ticerlaw.com", "Mark Ticer", "Civil Litigation & Trial Law", 4, "/contact/"),
    ("TX", "Sloan Firm (Longview)", "sloanfirm.com", "John Sloan", "Trial Practice & Civil Recovery", 4, "/contact/"),

    # CALIFORNIA BOUTIQUES (Unique Domains)
    ("CA", "Manning & Kass, Ellrod, Ramirez, Trester LLP", "manningkass.com", "Steven D. Manning", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("CA", "Haight Brown & Bonesteel LLP", "hbblaw.com", "Christian E. Sanchelima", "Real Estate Litigation & Civil Defense", 4, "/contact/"),
    ("CA", "Wood, Smith, Henning & Berman LLP", "wshblaw.com", "Daniel A. Berman", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("CA", "Bremer Whyte Brown & O'Meara, LLP", "bremerwhyte.com", "Nicole Whyte", "Real Estate, Construction & Estate Planning", 3, "/contact/"),
    ("CA", "Collins Collins Muir + Stewart LLP", "ccmslaw.com", "Brian K. Stewart", "Real Estate Litigation & Public Agency", 4, "/contact/"),
    ("CA", "Tyson & Mendes LLP", "tysonmendes.com", "Robert Tyson", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("CA", "Tharpe & Howell, LLP", "tharpe-howell.com", "Todd E. Croutch", "Civil Litigation & Real Estate Law", 4, "/contact/"),
    ("CA", "Walsworth WFBM, LLP", "wfbm.com", "Dee A. Walsworth", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("CA", "Yukevich | Cavanaugh", "yukelaw.com", "James J. Yukevich", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("CA", "Horvitz & Levy LLP", "horvitzlevy.com", "David M. Axelrad", "Appellate Litigation & Real Estate Law", 4, "/contact/"),
    ("CA", "Greines, Martin, Stein & Richland LLP", "gmsr.com", "Robin Meadow", "Appellate Trial & Property Disputes", 4, "/contact/"),
    ("CA", "Cotchett, Pitre & McCarthy, LLP", "cpmlegal.com", "Joseph W. Cotchett", "Complex Trial Practice & Asset Recovery", 4, "/contact/"),
    ("CA", "Lieff Cabraser Heimann & Bernstein, LLP (SF)", "lieffcabraser.com", "Kelly M. Dermody", "Complex Civil Recovery & Property Rights", 4, "/contact/"),
    ("CA", "Walkup, Melodia, Kelly & Schoenberger", "walkuplawoffice.com", "Michael A. Kelly", "Civil Trial Practice & Asset Disputes", 4, "/contact/"),
    ("CA", "Keker, Van Nest & Peters LLP", "keker.com", "John Keker", "Complex Trial & Real Estate Litigation", 4, "/contact/"),
    ("CA", "Durie Tangri LLP", "durietangri.com", "Daralyn Durie", "Complex Civil Litigation", 4, "/contact/"),
    ("CA", "Altshuler Berzon LLP", "altber.com", "Fred Altshuler", "Civil Litigation & Property Rights", 4, "/contact/"),
    ("CA", "Phillips, Spallas & Angstadt LLP", "psalaw.net", "Robert Spallas", "Civil Trial & Real Estate Defense", 4, "/contact/"),
    ("CA", "Bledsoe, Diestel, Treppa & Crane LLP", "bledsoelaw.com", "David Treppa", "Real Estate Litigation & Trial Practice", 4, "/contact/"),
    ("CA", "Lombardi, Loper & Conant, LLP", "llcllp.com", "Ralph Lombardi", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("CA", "Gagen McCoy (Danville)", "gagenmccoy.com", "Charles Koss", "Real Estate, Probate & Land Use", 3, "/contact/"),
    ("CA", "McNamara Ambacher (Walnut Creek)", "mcnamaralaw.com", "Thomas Ambacher", "Civil Trial & Real Estate", 4, "/contact/"),
    ("CA", "Craddick Candland (San Ramon)", "craddicklaw.com", "David Conti", "Civil Litigation & Defense", 4, "/contact/"),
    ("CA", "Clapp Moroney (San Bruno)", "clappmoroney.com", "Mark Scheley", "Real Estate & Construction", 4, "/contact/"),
    ("CA", "Coddington Hicks (Redwood City)", "chdlawyers.com", "Clinton Coddington", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("CA", "Ropers Majeski (Menlo Park)", "ropers.com", "Michael Brady", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("CA", "Severson & Werson (San Francisco)", "severson.com", "Mark Kenney", "Banking, Foreclosure & Real Estate", 1, "/contact/"),
    ("CA", "Wright Finlay & Zak (Newport Beach)", "wrightlegal.net", "Robin Wright", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("CA", "McCarthy & Holthus (San Diego)", "mccarthyholthus.com", "Thomas Holthus", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("CA", "Zieve Brodnax & Steele (Irvine)", "zbslaw.com", "Les Zieve", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),

    # GEORGIA BOUTIQUES (Unique Domains)
    ("GA", "Taylor English Duma (Atlanta)", "taylorenglish.com", "Marc Taylor", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Swift Currie (Atlanta)", "swiftcurrie.com", "Terry Brantley", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Drew Eckl (Atlanta)", "deflaw.com", "Joseph Chancey", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Freeman Mathis (Atlanta)", "fmglaw.com", "Ben Mathis", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("GA", "Goodman McGuffey (Atlanta)", "gm-llp.com", "Robert Luskin", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("GA", "Hall Booth Smith (Atlanta)", "hallboothsmith.com", "John Hall", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("GA", "HunterMaclean (Savannah)", "huntermaclean.com", "Bradford Johnson", "Real Estate Litigation & Probate", 1, "/contact/"),
    ("GA", "Oliver Maner (Savannah)", "olivermaner.com", "Patrick O'Connor", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Bouhan Falligant (Savannah)", "bouhan.com", "Benjamin Karpf", "Real Estate, Estate Planning & Litigation", 1, "/contact/"),
    ("GA", "Weiner Shearouse (Savannah)", "wswgs.com", "William Shearouse", "Real Estate, Probate & Title", 3, "/contact/"),
    ("GA", "Hull Barrett (Augusta)", "hullbarrett.com", "Mark Burgess", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Fulcher Hagler (Augusta)", "fulcherlaw.com", "Cameron Nixon", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("GA", "Warlick Stebbins (Augusta)", "warlicklaw.com", "Charles Stebbins", "Real Estate, Probate & Title", 3, "/contact/"),
    ("GA", "Jones Cork (Macon)", "jonescork.com", "Jerome Strickland", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "James Bates (Macon)", "jamesbates.com", "Duke Groover", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("GA", "Chambless Higdon (Macon)", "chamblesslaw.com", "Joseph Chambless", "Civil Trial & Real Estate", 4, "/contact/"),
    ("GA", "Sell & Melton (Macon)", "sell-melton.com", "John Draughon", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("GA", "Martin Snow (Macon)", "martinsnow.com", "John McGoldrick", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("GA", "Page Scrantom (Columbus)", "psstf.com", "W.G. Scrantom", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("GA", "Hatcher Stubbs (Columbus)", "hatcherstubbs.com", "Barrington Vaught", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("GA", "Pope McGlamry (Columbus)", "pmfirm.com", "Neal Pope", "Civil Trial Practice & Asset Recovery", 4, "/contact/"),
    ("GA", "Blasingame Burch (Athens)", "bbga.com", "Henry Garrard", "Trial Practice & Real Estate Disputes", 4, "/contact/"),
    ("GA", "Fortson Bentley (Athens)", "fbg-law.com", "Edwin Fortson", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("GA", "McCalla Raymer (Roswell)", "mccalla.com", "Martin Stone", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("GA", "Rubin Lublin (Peachtree Corners)", "rubinlublin.com", "Peter Lublin", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),

    # NORTH CAROLINA BOUTIQUES (Unique Domains)
    ("NC", "Poyner Spruill (Raleigh)", "poynerspruill.com", "Dan Cahill", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Wyrick Robbins (Raleigh)", "wyrick.com", "Jimmy Yates", "Real Estate Litigation & Commercial Law", 4, "/contact/"),
    ("NC", "Manning Fulton (Raleigh)", "manningfulton.com", "Barry Mann", "Real Estate, Eminent Domain & Litigation", 1, "/contact/"),
    ("NC", "Schell Bray (Greensboro)", "schellbray.com", "Michael Schell", "Real Estate, Estate Planning & Probate", 3, "/contact/"),
    ("NC", "Tuggle Duggins (Greensboro)", "tuggleduggins.com", "Richard Tuggle", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Higgins Benjamin (Greensboro)", "greensborolaw.com", "John Higgins", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Johnston Allison (Charlotte)", "jahlaw.com", "David Gilpin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "James McElroy (Charlotte)", "jmdlaw.com", "Marshall Yoder", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("NC", "Horack Talley (Charlotte)", "horacktalley.com", "Keith Nichols", "Real Estate Litigation & HOA Law", 2, "/contact/"),
    ("NC", "Moon Wright (Charlotte)", "mwhlaw.com", "Richard Wright", "Insolvency, Creditors Rights & Real Estate", 1, "/contact/"),
    ("NC", "Cranfill Sumner (Raleigh)", "cshlaw.com", "Marshall Wall", "Real Estate Litigation & Civil Defense", 4, "/contact/"),
    ("NC", "Young Moore (Raleigh)", "youngmoorelaw.com", "David Duke", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("NC", "Teague Campbell (Raleigh)", "teaguecampbell.com", "Dayle Flammia", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Tharrington Smith (Raleigh)", "tharringtonsmith.com", "Hill Allen", "Real Estate Litigation & Education Law", 4, "/contact/"),
    ("NC", "Cheshire Parker (Raleigh)", "cheshirepark.com", "Joseph Cheshire", "Civil Trial & Asset Forfeiture", 4, "/contact/"),
    ("NC", "Roberts & Stevens (Asheville)", "roberts-stevens.com", "Marc Rudow", "Real Estate Litigation & Probate", 1, "/contact/"),
    ("NC", "Van Winkle Law (Asheville)", "vwlawfirm.com", "Larry McDevitt", "Real Estate Litigation, Probate & Title", 1, "/contact/"),
    ("NC", "McGuire Wood (Asheville)", "mwbavl.com", "Sabrina Rockoff", "Real Estate, Estate Planning & Litigation", 3, "/contact/"),
    ("NC", "Ferikes & Bleynat (Asheville)", "ashevillelitigators.com", "Edward Bleynat", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Hutchens Law Firm (Fayetteville)", "hutchenslawfirm.com", "Terry Hutchens", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),

    # TENNESSEE BOUTIQUES (Unique Domains)
    ("TN", "Gullett Sanford (Nashville)", "gsrm.com", "Phillip Young", "Real Estate Litigation & Estate Planning", 3, "/contact/"),
    ("TN", "Dodson Parker (Nashville)", "dodsonparker.com", "Harlan Dodson", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Leitner Williams (Chattanooga)", "leitnerfirm.com", "Paul Leitner", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Chambliss Bahner (Chattanooga)", "chamblisslaw.com", "Mark Turner", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Miller & Martin (Chattanooga)", "millermartin.com", "Scott Parrish", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Luther-Anderson (Chattanooga)", "lutheranderson.com", "William Luther", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Gearhiser Peters (Chattanooga)", "gearhiserpeters.com", "Wayne Peters", "Real Estate, Probate & Tax Litigation", 3, "/contact/"),
    ("TN", "Patrick Beard (Chattanooga)", "pbsjlaw.com", "Gary Patrick", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("TN", "Speek Webb (Chattanooga)", "speekandwebb.com", "Jerry Speek", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("TN", "Evans Petree (Memphis)", "evanspetree.com", "Joseph Walker", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("TN", "Glankler Brown (Memphis)", "glankler.com", "Michael Coury", "Insolvency, Real Estate & Creditors Rights", 1, "/contact/"),
    ("TN", "Burch Porter (Memphis)", "bpjlaw.com", "Les Jones", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("TN", "Harris Shelton (Memphis)", "harrisshelton.com", "Brett Hughes", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("TN", "Martin Tate (Memphis)", "martintate.com", "Lee Piovarcy", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Apperson Crump (Memphis)", "appersoncrump.com", "Albert Harvey", "Real Estate, Probate & Trial Litigation", 3, "/contact/"),
    ("TN", "Pietrangelo Cook (Memphis)", "plegal.com", "John Cook", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("TN", "Kramer Rayson (Knoxville)", "kramer-rayson.com", "John Johnson", "Real Estate, Probate & Employment", 3, "/contact/"),
    ("TN", "Woolf McClane (Knoxville)", "wmbac.com", "Chadwick Hatmaker", "Real Estate Litigation & Tax", 1, "/contact/"),
    ("TN", "Egerton McAfee (Knoxville)", "emlaw.com", "Cheryl Rice", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Bernstein Stair (Knoxville)", "bsmlaw.com", "Bernard Bernstein", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("TN", "Eldridge & Blakney (Knoxville)", "eblaw.us", "David Eldridge", "Trial Practice & Real Estate Litigation", 4, "/contact/"),
    ("TN", "Lewis Thomason (Knoxville)", "lewisthomason.com", "Lisa Ramsay Cole", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Wimberly Lawson (Knoxville)", "wimberlylawson.com", "Ronald Daves", "Civil Litigation & Commercial Practice", 4, "/contact/"),
    ("TN", "Kennerly Montgomery (Knoxville)", "kmfpc.com", "Robert Green", "Real Estate Litigation, Municipal & Tax", 1, "/contact/"),
    ("TN", "Hodges Doughty (Knoxville)", "hdclaw.com", "Dean Farmer", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("TN", "Arnett Draper (Knoxville)", "adlawfirm.com", "Jack Draper", "Commercial Litigation & Real Estate", 4, "/contact/"),
    ("TN", "Sherrard Roe (Nashville)", "srvhlaw.com", "John Voigt", "Real Estate Litigation & Healthcare", 4, "/contact/"),
    ("TN", "Neal & Harwell (Nashville)", "nealharwell.com", "Aubrey Harwell", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("TN", "Riley & Jacobson (Nashville)", "rjfirm.com", "Mack Riley", "Real Estate Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Wiseman Ashworth (Nashville)", "watlaw.com", "Thomas Wiseman", "Civil Trial & Real Estate Litigation", 4, "/contact/"),
]

print(f"Loaded {len(EXPANSION_CANDIDATES_R3)} round 3 expansion candidates.")
