"""Florida Law Firm Pipeline Candidates"""

CANDIDATES = [
    # Miami-Dade & South Florida
    ("FL", "Carlton Fields, P.A.", "carltonfields.com", "Gary L. Carman", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("FL", "Bilzin Sumberg Baena Price & Axelrod LLP", "bilzin.com", "Michael N. Kreitzer", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Stearns Weaver Miller", "stearnsweaver.com", "Eugene E. Stearns", "Real Estate Litigation & Land Disputes", 1, "/contact-us/"),
    ("FL", "Shutts & Bowen LLP", "shutts.com", "Francis E. Rodriguez", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("FL", "Berger Singerman LLP", "bergersingerman.com", "Paul Steven Singerman", "Creditors Rights & Insolvency Litigation", 1, "/contact/"),
    ("FL", "Greenspoon Marder LLP", "gmlaw.com", "Gerald Greenspoon", "Real Estate Litigation & Foreclosure Defense", 2, "/contact-us/"),
    ("FL", "Kluger, Kaplan, Silverman, Katzen & Levine, P.L.", "klugerkaplan.com", "Alan J. Kluger", "Real Estate & Commercial Trial Practice", 4, "/contact/"),
    ("FL", "Haber Law", "haber.law", "David B. Haber", "Real Estate & Construction Litigation", 4, "/contact-us/"),
    ("FL", "Rennert Vogel Mandler & Rodriguez, P.A.", "rvmrlaw.com", "Jill Vogel", "Real Estate & Tax Litigation", 1, "/contact-us/"),
    ("FL", "Coffey Burlington, P.L.", "coffeyburlington.com", "Kendall Coffey", "Real Estate & Complex Commercial Litigation", 4, "/contact/"),
    ("FL", "Markowitz Ringel Trusty & Hartog, P.A.", "mrthlaw.com", "Jerry M. Markowitz", "Creditors Rights, Probate & Insolvency", 3, "/contact/"),
    ("FL", "Genovese Joblove & Battista, P.A.", "gjb-law.com", "John H. Genovese", "Receiverships, Creditors Rights & Real Estate", 1, "/contact/"),
    ("FL", "Damian & Valori LLP", "dvllp.com", "Melanie E. Damian", "Receiverships & Complex Business Litigation", 1, "/contact/"),
    ("FL", "Levine Kellogg Lehman Schneider + Grossman LLP", "lklsg.com", "Lawrence A. Kellogg", "Creditors Rights & Real Estate Litigation", 1, "/contact/"),
    ("FL", "Meland Budwick, P.A.", "melandbudwick.com", "Mark S. Meland", "Real Estate, Receiverships & Insolvency", 1, "/contact/"),
    ("FL", "Bast Amron LLP", "bastamron.com", "Brett M. Amron", "Insolvency Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Kozyak Tropin & Throckmorton", "kttlaw.com", "John W. Kozyak", "Complex Real Estate & Insolvency Litigation", 1, "/contact/"),
    ("FL", "Fowler White Burnett P.A.", "fowler-white.com", "Christopher E. Knight", "Real Estate & Commercial Litigation", 4, "/contact-us/"),
    ("FL", "Boyd & Jenerette, P.A.", "boyd-jenerette.com", "Jane Anderson", "Real Estate Litigation & Civil Defense", 4, "/contact/"),
    ("FL", "Cole, Scott & Kissane, P.A.", "csklegal.com", "Richard E. Cole", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("FL", "Quintairos, Prieto, Wood & Boyer, P.A.", "qpwblaw.com", "Eric W. Boyer", "Real Estate & Creditors Rights", 4, "/contact-us/"),
    ("FL", "Conroy Simberg", "conroysimberg.com", "Thomas F. Conroy", "Real Estate & Property Litigation", 4, "/contact-us/"),
    ("FL", "Wicker Smith O'Hara McCoy & Ford P.A.", "wickersmith.com", "Jackson F. McCoy", "Civil Trial & Real Estate Disputes", 4, "/contact/"),
    ("FL", "RumbergerKirk", "rumberger.com", "Frank C. Wesighan", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Kubicki Draper, P.A.", "kubickidraper.com", "Jane Thornton", "Real Estate Litigation & Title Claims", 4, "/contact/"),
    ("FL", "Banker Lopez Gassler P.A.", "bankerlopez.com", "Robert E. Banker", "Real Estate Disputes & Trial Litigation", 4, "/contact/"),
    ("FL", "Stichter, Riedel, Blain & Postler, P.A.", "srbp.com", "Don M. Stichter", "Insolvency, Foreclosure & Real Estate", 2, "/contact-us/"),
    ("FL", "Johnson, Pope, Bokor, Ruppel & Burns, LLP", "jpfirm.com", "Darryl R. Richards", "Real Estate Litigation & Tax Practice", 1, "/contact/"),
    ("FL", "Barnett, Bolt, Kirkwood, Long, Koche & Foster, P.A.", "barnettbolt.com", "Leslie J. Barnett", "Tax Planning, Probate & Real Estate", 3, "/contact/"),
    ("FL", "de la Parte & Gilbert, P.A.", "dgfirm.com", "Edward P. de la Parte", "Real Estate Litigation & Administrative Law", 4, "/contact/"),
    ("FL", "Smolker Bartlett Loeb Hinds & Sheppard, P.A.", "smolkerbartlett.com", "David Smolker", "Property Rights & Real Estate Litigation", 1, "/contact/"),
    ("FL", "Older Lundy Alvarez Koch & Martino", "olalaw.com", "Benjamin Lundy", "Probate, Estate & Civil Litigation", 3, "/contact-us/"),
    ("FL", "McIntyre Thanasides", "mcintyrefirm.com", "Ricky McIntyre", "Foreclosure Defense, Bankruptcy & Real Estate", 2, "/contact-us/"),
    ("FL", "Anton Castro Law", "tampabaylawfirm.com", "S. David Anton", "Probate & Real Estate Litigation", 3, "/contact-us/"),
    ("FL", "Danahy & Murray, P.A.", "danahyandmurray.com", "Matthew R. Danahy", "Property Claims & Real Estate Litigation", 4, "/contact/"),
    ("FL", "Merlin Law Group, P.A.", "merlinlawgroup.com", "William F. Merlin", "Property Recovery & Insurance Claims", 4, "/contact-us/"),
    ("FL", "Weisser Elazar & Kantor, PLLC", "weisserlaw.com", "Brett Weisser", "Probate, Trust & Property Recovery", 3, "/contact/"),
    ("FL", "Rogers Towers, P.A.", "rtlaw.com", "Fred D. Franklin", "Real Estate Litigation & Foreclosures", 1, "/contact/"),
    ("FL", "Marks Gray, P.A.", "marksgray.com", "Frederick H. Kent", "Real Estate, Probate & Civil Litigation", 3, "/contact-us/"),
    ("FL", "Saalfield Shad, P.A.", "saalfieldlaw.com", "Richard Saalfield", "Real Estate & Trial Litigation", 4, "/contact/"),
    ("FL", "Driver, McAfee, Hawthorne & Diebenow, PLLC", "dmh-law.com", "Steve Diebenow", "Real Estate & Land Use Litigation", 4, "/contact/"),
    ("FL", "Murphy & Anderson, P.A.", "murphyandersonlaw.com", "Niels P. Murphy", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Milam Howard Nicandri Dees & Gillam, P.A.", "milamhoward.com", "Robert A. Heekin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Smith Hulsey & Busey", "smithhulsey.com", "Stephen D. Busey", "Insolvency, Real Estate & Trial Practice", 1, "/contact/"),
    ("FL", "Taylor, Day, Grimm & Boyd", "taylordaylaw.com", "Reed W. Grimm", "Real Estate & Commercial Trial Law", 4, "/contact/"),
    ("FL", "Moseley Prichard Parrish Knight & Jones", "mppkj.com", "James F. Moseley", "Civil Trial & Real Estate Litigation", 4, "/contact/"),
    ("FL", "Gilligan, Gooding, Batsel, Anderson & Phelan, P.A.", "ocalalaw.com", "Patrick G. Gilligan", "Real Estate, Probate & Land Use", 3, "/contact-us/"),
    ("FL", "Blanchard, Merriam, Adel, Kirkland & Green, P.A.", "bmaklaw.com", "Curt Kirkland", "Real Estate & Probate Litigation", 3, "/contact/"),
    ("FL", "Dell Graham, P.A.", "dellgraham.com", "David A. Dell", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("FL", "Scruggs, Carmichael & Wershow, P.A.", "scruggs-carmichael.com", "John Wershow", "Real Estate Litigation & Estate Administration", 3, "/contact/"),
    ("FL", "Siegel Hughes & Ross", "shrlawfirm.com", "Brent G. Siegel", "Real Estate Litigation & Eminent Domain", 4, "/contact-us/"),
    ("FL", "Clayton-Johnston, P.A.", "clayton-johnston.com", "Leonard E. Ireland", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("FL", "Folds Walker, LLC", "foldswalker.com", "Allison Folds", "Real Estate Litigation & Municipal Law", 4, "/contact-us/"),
    ("FL", "Salter Feiber, P.A.", "salterlaw.net", "David E. Salter", "Real Estate, Title Clearance & Probate", 3, "/contact/"),
    ("FL", "Pennington, P.A.", "penningtonlaw.com", "Carl R. Pennington", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Messer Caparello, P.A.", "lawfla.com", "Mark S. Ellis", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("FL", "Nabors, Giblin & Nickerson, P.A.", "ngn-tally.com", "Arthur R. Neiss", "Public Finance & Property Litigation", 4, "/contact/"),
    ("FL", "Sniffen & Spellman, P.A.", "sniffenlaw.com", "Robert J. Sniffen", "Civil Trial & Property Litigation", 4, "/contact-us/"),
    ("FL", "Bryant Miller Olive P.A.", "bmolaw.com", "Grace E. Dunlap", "Public Finance & Real Estate Practice", 4, "/contact-us/"),
    ("FL", "Searcy Denney Scarola Barnhart & Shipley, P.A.", "searcylaw.com", "Christian D. Searcy", "Civil Trial & Property Recovery", 4, "/contact-us/"),
    ("FL", "Lytal, Reiter, Smith, Ivey & Fronrath", "foryourrights.com", "Mark W. Clark", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("FL", "Clark, Fountain, La Vista, Prather & Littky-Rubin", "clarkfountain.com", "Mark W. Clark", "Complex Civil Recovery", 4, "/contact-us/"),
    ("FL", "Babbitt & Johnson, P.A.", "babbitt-johnson.com", "Theodore Babbitt", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("FL", "Domnick Cunningham & Whalen", "dcwlaw.com", "Sean C. Domnick", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("FL", "Reid Burman Lebedeker Xenick Pepin", "reidburmanlaw.com", "J. Michael Burman", "Real Estate Litigation & Title Disputes", 1, "/contact-us/"),
    ("FL", "Fisher & Bendeck, P.A.", "fisherbendeck.com", "Jeffrey D. Fisher", "Complex Litigation & Asset Division", 3, "/contact-us/"),
    ("FL", "Ciklin Lubitz", "ciklinlubitz.com", "Alan J. Ciklin", "Real Estate, Land Use & Creditors Rights", 1, "/contact/"),
    ("FL", "Haile Shaw & Pfaffenberger, P.A.", "haileshaw.com", "Robert Haile", "Real Estate Litigation & Estate Administration", 3, "/contact-us/"),
    ("FL", "Jones Foster P.A.", "jonesfoster.com", "Scott G. Hawkins", "Real Estate Litigation, Probate & Trust", 3, "/contact-us/"),
    ("FL", "Ward Damon, PL", "warddamon.com", "Philip H. Ward", "Real Estate, Foreclosure Defense & Distressed Debt", 2, "/contact-us/"),
    ("FL", "Comiter, Singer, Baseman & Braun, LLP", "comitersinger.com", "Richard B. Comiter", "Estate Planning, Probate & Tax Litigation", 3, "/contact-us/"),
    ("FL", "Nason, Yeager, Gerson, Harris & Fumero, P.A.", "nasonyeager.com", "Nathan E. Nason", "Real Estate Litigation, Land Title & Environmental", 4, "/contact/"),
    ("FL", "McDonald Hopkins LLC (FL)", "mcdonaldhopkins.com", "Peter M. Bernhardt", "Real Estate Litigation & Distressed Property", 1, "/contact-us/"),
    ("FL", "Fox Rothschild LLP (FL)", "foxrothschild.com", "Amy S. Rubin", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Duane Morris LLP (FL)", "duanemorris.com", "Harvey W. Gurland", "Real Estate Litigation & Foreclosures", 1, "/contact/"),
    ("FL", "Cozen O'Connor (FL)", "cozen.com", "Martin T. Schrier", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Saul Ewing LLP (FL)", "saul.com", "Charles D. Brecker", "Real Estate Development & Litigation", 4, "/contact/"),
    ("FL", "Nelson Mullins Riley & Scarborough LLP (FL)", "nelsonmullins.com", "George S. LeMieux", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Holland & Knight LLP (FL)", "hklaw.com", "Judith M. Mercier", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Greenberg Traurig, P.A.", "gtlaw.com", "Alan T. Dimond", "Real Estate Litigation & Tax Deed Disputes", 1, "/contact-us/"),
    ("FL", "Gunster", "gunster.com", "H. William Perry", "Real Estate Litigation, Land Title & Probate", 1, "/contact-us/"),
    ("FL", "Akerman LLP", "akerman.com", "Scott A. Meyers", "Real Estate Litigation & Distressed Property", 1, "/contact/"),
    ("FL", "GrayRobinson, P.A.", "gray-robinson.com", "Dean Cannon", "Real Estate Litigation, Land Title & Creditors Rights", 1, "/contact/"),
    ("FL", "Lowndes, Drosdick, Doster, Kantor & Reed, P.A.", "lowndes-law.com", "William T. Dymond", "Real Estate Litigation & Distressed Assets", 1, "/contact-us/"),
    ("FL", "Trenam Law", "trenam.com", "Lara R. Fernandez", "Creditors Rights, Foreclosure & Real Estate", 1, "/contact-us/"),
    ("FL", "Hill Ward Henderson", "hwhlaw.com", "R. Reid Haney", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Bush Ross, P.A.", "bushross.com", "Jeffrey W. Warren", "Insolvency, Real Estate & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Winderweedle, Haines, Ward & Woodman, P.A.", "whww.com", "Michael C. Sasso", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Bogin, Munns & Munns, P.A.", "boginmunns.com", "Ranier Munns", "Real Estate Litigation, Foreclosure & Probate", 2, "/contact-us/"),
    ("FL", "Shuffield, Lowman & Wilson, P.A.", "shuffieldlowman.com", "William R. Lowman", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("FL", "The Soto Law Group, P.A.", "sotolawgroup.com", "Alexander Soto", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("FL", "Oppenheim Law", "oppenheimlaw.com", "Roy Oppenheim", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("FL", "Law Offices of Daniel A. Rose, P.A.", "danroselaw.com", "Daniel A. Rose", "Foreclosure Defense & Property Law", 2, "/contact/"),
    ("FL", "Jacobs Legal, PLLC", "jakelegal.com", "Bruce Jacobs", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("FL", "Weintraub & Weintraub, P.A.", "weintraublaw.com", "Richard Weintraub", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("FL", "Ritter Chusid, LLP", "ritterchusid.com", "Gregory Ritter", "Real Estate & Commercial Trial Law", 4, "/contact/"),
    ("FL", "Zarco Einhorn Salkowski, P.A.", "zarcolaw.com", "Robert Zarco", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("FL", "Krupnick Campbell Malone Buser Slama Hancock, P.A.", "krupnicklaw.com", "Scott S. Liberman", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Tripp Scott, P.A.", "trippscott.com", "Ed Pozzuoli", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Haliczer, Pettis & Schwamm, P.A.", "hpslegal.com", "James S. Haliczer", "Civil Trial & Complex Recovery", 4, "/contact/"),
    ("FL", "Kopelowitz Ostrow Ferguson Weiselberg Gilbert", "kolawyers.com", "Jan Atlas", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Brinkley Morgan", "brinkleymorgan.com", "John N. Ellem", "Real Estate, Probate & Civil Litigation", 3, "/contact/"),
    ("FL", "Weiss Serota Helfman Cole & Bierman, P.L.", "wsh-law.com", "Mitchell J. Burnstein", "Eminent Domain, Real Estate & Land Title", 1, "/contact/"),
    ("FL", "Berman Kean, P.A.", "bermankean.com", "Richard Berman", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Behar, Gutt & Glazer, P.A.", "bgglaw.com", "Robert J. Behar", "Creditors Rights, Real Estate & Foreclosure", 1, "/contact/"),
    ("FL", "Patterson & Maloney", "pattersonmaloney.com", "Michael Patterson", "Real Estate & Probate Litigation", 3, "/contact/"),
    ("FL", "Geller Law Firm", "gellerlawfirm.com", "Marc Geller", "Probate, Real Estate & Civil Litigation", 3, "/contact/"),
    ("FL", "The Law Office of David Steinfeld, P.L.", "davidsteinfeld.com", "David Steinfeld", "Real Estate & Business Litigation", 4, "/contact/"),
    ("FL", "Gielow Groom Terpstra & McEvoy", "ggtm.com", "Eric Gielow", "Real Estate, Title & Land Use", 4, "/contact/"),
    ("FL", "Rosenthal Rosenthal Rasco LLC", "rrrlaw.com", "Eduardo I. Rasco", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "Brodie & Friedman, P.A.", "brodiefriedman.com", "Jason A. Brodie", "Asset Division & Probate Litigation", 3, "/contact/"),
    ("FL", "Klein Law Group, P.A.", "kleinattorneys.com", "Eric N. Klein", "Real Estate, Bankruptcy & Foreclosure Defense", 2, "/contact/"),
    ("FL", "Silverberg & Weiss, P.A.", "silverbergweiss.com", "Paul K. Silverberg", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Garrity Traina, P.A.", "garritytraina.com", "Vincent Garrity", "Real Estate & Title Litigation", 4, "/contact/"),
    ("FL", "Sachs Sax Caplan, P.L.", "ssclawfirm.com", "Peter S. Sachs", "Real Estate, HOA & Distressed Property", 2, "/contact/"),
    ("FL", "Graner Law Group, P.A.", "granerlaw.com", "Steven Graner", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "The Law Offices of Larry E. Bray, P.A.", "braylawoffices.com", "Larry E. Bray", "Real Estate, Foreclosure & Estate Planning", 2, "/contact/"),
    ("FL", "Pincus & Currier LLP", "pincusandcurrier.com", "Mark Pincus", "Real Estate & Probate Litigation", 3, "/contact/"),
    ("FL", "Cohen, Norris, Wolmer, Ray, Telepman, Berkowitz & Cohen", "fcohenlaw.com", "Felix M. Cohen", "Real Estate, Title & Distressed Assets", 1, "/contact/"),
    ("FL", "Padula Bennardo Levine LLP", "pbl-law.com", "Stephen J. Padula", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Loren & Kean Law", "lorenkeanlaw.com", "Bruce Loren", "Construction & Real Estate Litigation", 4, "/contact/"),
    ("FL", "Katzman Chandler", "katzmanchandler.com", "Leigh C. Katzman", "Real Estate & HOA Foreclosure Law", 2, "/contact/"),
    ("FL", "Gerstin & Associates", "gerstin.com", "Joshua Gerstin", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("FL", "Kahan & Associates, PLLC", "kahanlaw.com", "Brian Kahan", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "Shapiro, Blasi, Wasserman & Hermann, P.A.", "sbwh.law", "Michael D. Wasserman", "Real Estate, Foreclosure & Creditors Rights", 1, "/contact/"),
    ("FL", "Lavalle, Brown & Ronan, P.A.", "lavallebrown.com", "Charles C. Lavalle", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("FL", "Ellis, Ged & Bodden, P.A.", "ellisandged.com", "Glen B. Ged", "Real Estate, Probate & Asset Recovery", 3, "/contact/"),
    ("FL", "Feldman & Schneiderman, P.A.", "bocalaw.com", "Mitchell A. Feldman", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "The Florida Probate Law Firm, PLLC", "floridaprobatelawfirm.com", "Travis Finchum", "Probate, Trust & Surplus Heirship", 3, "/contact/"),
    ("FL", "Adrian Philip Thomas, P.A.", "florida-probate-lawyer.com", "Adrian Philip Thomas", "Probate & Estate Litigation", 3, "/contact/"),
    ("FL", "Boyer Law Firm, P.L.", "boyerlawfirm.com", "Francis Boyer", "Real Estate, Probate & Asset Recovery", 3, "/contact/"),
    ("FL", "Ansbacher Law", "ansbacher.net", "Barry Ansbacher", "Real Estate, Title & Foreclosure Litigation", 1, "/contact/"),
    ("FL", "Harris Guidi Rosner, P.A.", "harrisguidi.com", "Robert Harris", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("FL", "The Coleman Firm", "thecolemanfirm.com", "David Coleman", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("FL", "Fisher, Tousey, Leas & Medina", "fishertousey.com", "Mark Leas", "Estate Planning, Tax & Real Estate Law", 3, "/contact/"),
    ("FL", "Edwards & Ragatz, P.A.", "edwardsragatz.com", "Thomas Edwards", "Civil Litigation & Trial Law", 4, "/contact/"),
    ("FL", "Milam & Milam, P.A.", "milamlaw.com", "Richard Milam", "Real Estate & Probate Litigation", 3, "/contact/"),
    ("FL", "Murphy & Ellis, PLLC", "murphyellis.com", "Mark Ellis", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Donahoo & McMenamy, P.A.", "dmjaxlaw.com", "John Donahoo", "Estate Planning, Probate & Real Estate", 3, "/contact/"),
    ("FL", "Cobbie A. Vance, P.A.", "vancelawfl.com", "Cobbie Vance", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("FL", "The Law Offices of Jason K.S. Porter, P.A.", "jasonporterlaw.com", "Jason Porter", "Foreclosure Defense & Civil Trial", 2, "/contact/"),
    ("FL", "Zisser Family Law", "zisserfamilylaw.com", "Carolyn Zisser", "Asset Division & Estate Litigation", 3, "/contact/"),
    ("FL", "Glaser & Ebbs", "glaserandebbs.com", "Mark Glaser", "Civil Trial & Real Estate", 4, "/contact/"),
    ("FL", "Heekin Law", "heekinlaw.com", "David Heekin", "Real Estate, Title & Estate Planning", 1, "/contact/"),
    ("FL", "Campione & Hackney, P.A.", "campionelaw.com", "Mark Campione", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("FL", "Bowen & Schroth, P.A.", "bowenschroth.com", "Derek Schroth", "Real Estate, Local Government & Litigation", 4, "/contact/"),
    ("FL", "McLin Burnsed", "mclinburnsed.com", "Mark Burnsed", "Real Estate, Estate Planning & Litigation", 3, "/contact/"),
    ("FL", "CRAWFORD, MODICA & O'KEEFE, P.A.", "cmo-law.com", "Timothy Crawford", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Stone & Gerken, P.A.", "stoneandgerken.com", "Richard Stone", "Real Estate & Probate Law", 3, "/contact/"),
    ("FL", "Gaylord & Rogers, LLC", "gaylordrogers.com", "Kevin Rogers", "Real Estate Litigation & Title Clearance", 4, "/contact/"),
    ("FL", "Bice Cole Law Firm, PL", "bicecolelaw.com", "Robert Bice", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Potter, Clement, Lowery & Mitchell", "potterclement.com", "Charles Clement", "Real Estate, Probate & Title", 3, "/contact/"),
    ("FL", "Rassman Law", "rassmanlaw.com", "Todd Rassman", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("FL", "The Rosenthal Law Firm, P.A.", "rosenthalcounsel.com", "Alex Rosenthal", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "de Beaubien, Simmons, Knight, Mantzaris & Neal, LLP", "dbksmn.com", "Kenneth Mantzaris", "Real Estate, Foreclosure & Creditors Rights", 1, "/contact/"),
    ("FL", "Dellecker, Wilson, King, McKenna, Ruffier & Sos, LLP", "dwklaw.com", "Robert Dellecker", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "Newsome Melton", "newsomelaw.com", "Richard Newsome", "Complex Civil Litigation", 4, "/contact/"),
    ("FL", "Colling Gilbert Wright & Carter", "thefloridafirm.com", "Stewart Colling", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("FL", "Fassett, Anthony & Taylor, P.A.", "fassettlaw.com", "Kim Anthony", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Kirwin Norris, P.A.", "kirwinnorris.com", "Bruce Norris", "Construction & Real Estate Litigation", 4, "/contact/"),
    ("FL", "Stovash, Case, Shay & Pearce, P.A.", "scslegal.com", "Robert J. Stovash", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("FL", "Mateer & Harbert, P.A.", "mateerharbert.com", "David Harbert", "Real Estate, Eminent Domain & Litigation", 1, "/contact/"),
    ("FL", "Wright, Fulford, Moorhead & Brown, P.A.", "wfmblaw.com", "Scott Fulford", "Construction & Real Estate Litigation", 4, "/contact/"),
    ("FL", "Latham, Luna, Eden & Beaudine, LLP", "lathamluna.com", "Michael J. Beaudine", "Real Estate Litigation & Land Use", 4, "/contact/"),
    ("FL", "Killgore, Pearlman, Semanie & Denius, P.A.", "kpsdlaw.com", "Robert Killgore", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("FL", "Fishback Dominick", "fishbacklaw.com", "Charles Dominick", "Real Estate, Local Government & Probate", 3, "/contact/"),
    ("FL", "Vose Law Firm LLP", "voselaw.com", "Becky Vose", "Real Estate & Municipal Property Law", 4, "/contact/"),
    ("FL", "The Maher Law Firm", "maherlawfirm.com", "Michael Maher", "Trial Litigation & Asset Recovery", 4, "/contact/"),
    ("FL", "Appleton Reiss, PLLC", "appletonreiss.com", "Craig Appleton", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("FL", "Gibbons Law Firm", "gibbonslawfirm.com", "Daniel Gibbons", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "The Soto Firm", "sotofirm.com", "Edwin Soto", "Real Estate & Distressed Debt", 2, "/contact/"),
    ("FL", "Kosto & Rotella, P.A.", "kostorotella.com", "Louis Rotella", "Creditors Rights & Foreclosure Law", 1, "/contact/"),
    ("FL", "Pohl & Short, P.A.", "pohlshort.com", "Frank Pohl", "Real Estate, Corporate & Probate Law", 3, "/contact/"),
    ("FL", "The Bigney Law Firm", "bigneylaw.com", "Daniel Bigney", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("FL", "NeJame Law", "nejamelaw.com", "Mark NeJame", "Civil Litigation, Real Estate & Trial Law", 4, "/contact/"),
    ("FL", "Overstreet, Miles, Cumbie & Finkenbinder, P.A.", "omcflaw.com", "John Miles", "Real Estate, Probate & Estate Administration", 3, "/contact/"),
    ("FL", "Swann Hadley Stump Dietrich & Specht, P.A.", "swannhadley.com", "Richard Swann", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("FL", "Hilyard, Bogan & Palmer, P.A.", "hilyardlawfirm.com", "Bruce Bogan", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("FL", "Bell & Roper, P.A.", "bellroperlaw.com", "Michael Roper", "Civil Litigation & Local Government", 4, "/contact/"),
    ("FL", "Fisher Rushmer, P.A.", "fisherlawfirm.com", "Joseph Rushmer", "Civil Trial & Property Litigation", 4, "/contact/"),
    ("FL", "Wooten, Kimbrough, Damaso & Dennis, P.A.", "whkpa.com", "Council Wooten", "Trial Practice & Asset Recovery", 4, "/contact/"),
    ("FL", "The Umansky Law Firm", "crimlegal.com", "William D. Umansky", "Civil Litigation & Trial Defense", 4, "/contact/"),
    ("FL", "Baumgartner Law", "baumgartnerlaw.com", "Bruce Baumgartner", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("FL", "Luks, Santaniello, Petrillo, Cohen & Peterfriend", "ls-law.com", "Dan Santaniello", "Civil Trial & Property Litigation", 4, "/contact/"),
    ("FL", "Roetzel & Andress, LPA (FL)", "ralaw.com", "Paul A. Giordano", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Bond, Schoeneck & King PLLC (FL)", "bsk.com", "Dennis C. Brown", "Real Estate & Estate Planning", 3, "/contact-us/"),
    ("FL", "Cummings & Lockwood LLC (FL)", "cl-law.com", "William N. Wright", "Trusts, Estates & Wealth Planning", 3, "/contact-us/"),
    ("FL", "Quarles & Brady LLP (FL)", "quarles.com", "Bradley G. Rigor", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Porter Wright Morris & Arthur LLP (FL)", "porterwright.com", "Edward J. Long", "Real Estate, Probate & Litigation", 3, "/contact-us/"),
    ("FL", "Hahn Loeser & Parks LLP (FL)", "hahnlaw.com", "Mark R. Fischer", "Real Estate Litigation & Creditors Rights", 1, "/contact-us/"),
    ("FL", "Woodward, Pires & Lombardo, P.A.", "wpl-legal.com", "Craig R. Woodward", "Real Estate, Probate & Land Use", 3, "/contact/"),
    ("FL", "Grant Fridkin Pearson, P.A.", "gfpac.com", "Jeffrey D. Fridkin", "Real Estate Litigation & Probate Disputes", 1, "/contact/"),
    ("FL", "Bond, Botes & Shuttlesworth, P.C.", "bondnbotes.com", "Bradford Botes", "Foreclosure Defense & Debt Relief", 2, "/contact/"),
    ("FL", "Laird A. Lile, PLLC", "lairdalile.com", "Laird A. Lile", "Probate, Trust Administration & Estate Litigation", 3, "/contact/"),
    ("FL", "Coleman, Hazzard, Taylor, Klaus, Doupé & Diaz, P.A.", "chtlegal.com", "J. Michael Coleman", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("FL", "Cardillo, Keith & Bonaquist, P.A.", "ckblaw.com", "William Keith", "Real Estate, Estate Planning & Litigation", 3, "/contact/"),
    ("FL", "Weldon & Rothman, PL", "weldonrothman.com", "Bradley Weldon", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("FL", "Salvatori, Wood, Buckel, Lavezzi & Kelley", "swbl-law.com", "Leo Salvatori", "Real Estate, Probate & Land Use", 3, "/contact/"),
    ("FL", "Goede, DeBoest & Cross, PLLC", "gadclaw.com", "John E. Goede", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("FL", "Pavese Law Firm", "paveselaw.com", "Christopher J. Shields", "Real Estate, Land Use & Probate", 3, "/contact/"),
    ("FL", "Knott Ebelini Hart", "knott-law.com", "George Knott", "Real Estate Litigation & Land Title", 1, "/contact/"),
    ("FL", "Royston, Rayzor, Vickery & Williams, LLP (FL)", "roystonlaw.com", "David R. Royston", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("FL", "Boyle & Leonard, P.A.", "insurance-counsel.com", "Mark A. Boyle", "Property Rights & Civil Litigation", 4, "/contact/"),
    ("FL", "Aloia, Roland, Lubell & Morgan, PLLC", "lawdefined.com", "Frank J. Aloia", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("FL", "Geraghty, Dougherty, Edwards & Stockman, P.A.", "gdeslaw.com", "Patrick Geraghty", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("FL", "Sheppard, Brett, Stewart, Hersch, Kinsey & Hill, P.A.", "sbshlaw.com", "Craig R. Hersch", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("FL", "Osterhout & McKinney, P.A.", "osterhoutmckinney.com", "David McKinney", "Probate & Estate Administration", 3, "/contact/"),
    ("FL", "The Dellutri Law Group, P.A.", "dellutrilawgroup.com", "Carmine Dellutri", "Foreclosure Defense, Bankruptcy & Debt Recovery", 2, "/contact/"),
    ("FL", "Goldstein, Buckley, Cechman, Rice & Purtz, P.A.", "gbclaw.com", "J. Jeffrey Rice", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("FL", "Kagan Law Firm", "kaganlawfl.com", "Jesse Kagan", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("FL", "Spivey Law Firm", "spiveylaw.com", "Randall Spivey", "Trial Practice & Asset Recovery", 4, "/contact/"),
    ("FL", "Viles & Beckman, LLC", "vilesandbeckman.com", "Marcus W. Viles", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("FL", "McHale, P.A.", "mchalepa.com", "John McHale", "Real Estate, Title & Foreclosure Defense", 2, "/contact/"),
    ("FL", "Hale Law, P.A.", "halelaw.com", "Patrick M. Hale", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("FL", "Syprett Meshad, P.A.", "smrl.com", "John M. Meshad", "Real Estate Litigation, Foreclosure & Probate", 1, "/contact/"),
    ("FL", "Icard, Merrill, Cullis, Timm, Furen & Ginsburg, P.A.", "icardmerrill.com", "Robert G. Lyons", "Real Estate, Land Use & Probate Litigation", 1, "/contact/"),
    ("FL", "Williams Parker Harrison Dietz & Getzen", "williamsparker.com", "Michael J. Wilson", "Real Estate, Probate, Tax & Title Litigation", 1, "/contact/"),
    ("FL", "Fergeson Skipper, P.A.", "fergesonskipper.com", "James O. Fergeson", "Real Estate, Probate & Estate Administration", 3, "/contact/"),
    ("FL", "Berlin Patten Ebling, PLLC", "berlinpatten.com", "Keith Ebling", "Real Estate, Title Clearance & Foreclosure", 1, "/contact/"),
    ("FL", "Dunlap & Moran, P.A.", "dunlapmoran.com", "Scott W. Dunlap", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("FL", "Najmy Thompson, P.L.", "najmythompson.com", "Joseph L. Najmy", "Real Estate Litigation & Land Use", 4, "/contact/"),
    ("FL", "Bowman, George, Scheb, Kimbrough, Koach & Chapman, P.A.", "bowmangeorge.com", "Robert Scheb", "Real Estate, Probate & Litigation", 3, "/contact/"),
    ("FL", "Gibson, Kohl & Wolff, P.L.", "floridataxlawyers.com", "Robert Gibson", "Tax Deed, Probate & Real Estate Litigation", 1, "/contact/"),
    ("FL", "Lutz, Bobo & Telfair, P.A.", "lutzbobo.com", "Charlie Telfair", "Civil Litigation & Trial Law", 4, "/contact/"),
    ("FL", "Harllee & Bald, P.A.", "harlleebald.com", "John Harllee", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("FL", "Grimes Hawkins Gladfelter & Galvano, P.L.", "grimesgoebel.com", "Caleb Grimes", "Real Estate, Land Use & Probate", 3, "/contact/"),
    ("FL", "Blalock Walters, P.A.", "blalockwalters.com", "Jonathan Fleece", "Real Estate Litigation, Land Title & Probate", 1, "/contact/"),
    ("FL", "Kallins, Little & Delgado", "kallinslaw.com", "Melton H. Little", "Civil Trial & Real Estate", 4, "/contact/"),
    ("FL", "Legler, Murphy & Battaglia, LLP", "leglermurphy.com", "Thomas Murphy", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("FL", "Heintz Law", "heintzlaw.com", "Steven R. Heintz", "Trial Practice & Asset Recovery", 4, "/contact/"),
    ("FL", "Band, Gates & Dramis, P.L.", "bandgates.com", "David Band", "Real Estate, Probate & Civil Litigation", 3, "/contact/"),
    ("FL", "Marrone Law Group, P.A.", "marronelaw.com", "Joseph Marrone", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("FL", "The Law Office of Stephen K. Hachey, P.A.", "hacheylaw.com", "Stephen Hachey", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("FL", "Cobb Cole", "cobbcole.com", "W. Scott Cole", "Real Estate, Land Use & Litigation", 4, "/contact/"),
    ("FL", "Wright & Casey, P.A.", "wrightcasey.com", "Paul Wright", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("FL", "Landis Graham French, P.A.", "landisgrahamfrench.com", "Frank G. French", "Real Estate Litigation, Probate & Title", 1, "/contact/"),
    ("FL", "Rice Law Firm", "ricelawfirm.com", "Paul Rice", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("FL", "Vassallo, Bilotta & Davis", "vassallobilotta.com", "Joseph Vassallo", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("FL", "Gassman, Crotty & Denicolo, P.A.", "gassmanlaw.com", "Alan S. Gassman", "Probate, Estate Planning & Asset Recovery", 3, "/contact/"),
    ("FL", "England & England, P.A.", "englandlaw.com", "Arthur England", "Real Estate & Estate Litigation", 3, "/contact/"),
    ("FL", "Battaglia, Ross, Dicus & McQuaid, P.A.", "stpetelawgroup.com", "Sean K. McQuaid", "Real Estate Litigation, Probate & Title Law", 1, "/contact/"),
    ("FL", "Baskind & Baskind, P.A.", "baskindlaw.com", "Neil Baskind", "Real Estate Litigation & Title Law", 4, "/contact/"),
    ("FL", "Boyle, Leonard & Anderson, P.A.", "insurancedenial.law", "Mark Boyle", "Real Estate & Property Litigation", 4, "/contact/"),
    ("FL", "The Law Office of Brian P. Kowal, P.A.", "briankowallaw.com", "Brian P. Kowal", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("FL", "Decker, von Keller & Bannon, P.A.", "deckervonkeller.com", "Charles Decker", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("FL", "Gilbert Garcia Group, P.A.", "gilbertgrouplaw.com", "Michelle Garcia Gilbert", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("FL", "Kahane & Associates, P.A.", "kahaneandassociates.com", "Marc Kahane", "Foreclosure & Real Estate Litigation", 1, "/contact/"),
    ("FL", "Diaz Anselmo & Associates, P.A.", "dallegal.com", "Roy Diaz", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("FL", "Padgett Law Group", "padgettlawgroup.com", "David Padgett", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("FL", "Robertson, Anschutz, Schneid, Crane & Partners, PLLC", "rasflaw.com", "Robert Anschutz", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("FL", "Tromberg, Morris & Poulin, PLLC", "tmppllc.com", "Andrea Tromberg", "Foreclosure Litigation & Real Estate", 1, "/contact/"),
    ("FL", "Brock & Scott, PLLC (FL)", "brockandscott.com", "Thomas Brock", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("FL", "Marinosci Law Group, P.C. (FL)", "mlg-defaultlaw.com", "Gary Marinosci", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("FL", "Storey Law Group, P.A.", "storeylawgroup.com", "David Storey", "Real Estate Litigation & Foreclosures", 1, "/contact/"),
    ("FL", "Aldridge Pite, LLP (FL)", "aldridgepite.com", "John Aldridge", "Foreclosure Defense & Real Estate Practice", 1, "/contact/"),
    ("FL", "Quintairos Prieto Wood Boyer PA (Tampa)", "qpwblaw.com", "Hugh Boyer", "Creditors Rights & Real Estate Trial Law", 1, "/contact/"),
    ("FL", "Liebler, Gonzalez & Portuondo", "lgplaw.com", "Juan Gonzalez", "Banking, Foreclosure & Real Estate Litigation", 1, "/contact/"),
    ("FL", "Henshaw & Culbertson LLP (FL)", "hinshawlaw.com", "Ronald L. Kammer", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("FL", "Burr & Forman LLP (FL)", "burr.com", "William S. Fish", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Phelps Dunbar LLP (FL)", "phelps.com", "A. Dennis Valles", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("FL", "Adams and Reese LLP (FL)", "adamsandreese.com", "David M. Snyder", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Baker Donelson (FL)", "bakerdonelson.com", "L. Rachel Lary", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("FL", "Balch & Bingham LLP (FL)", "balch.com", "S. Allen Baker", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("FL", "Bradley Arant Boult Cummings LLP (FL)", "bradley.com", "Robert R. Maddox", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("FL", "Maynard Nexsen PC (FL)", "maynardnexsen.com", "C. Ellis Brazeal", "Real Estate & Creditors Rights", 1, "/contact/"),
]

print(f"Loaded {len(CANDIDATES)} Florida candidate practices.")
