"""Georgia Law Firm Pipeline Candidates"""

CANDIDATES = [
    # Atlanta Metro & Northern Georgia
    ("GA", "The Libby Law Firm", "thelibbylawfirm.com", "David Libby", "Probate, Estate & Real Estate Litigation", 3, "/contact-us/"),
    ("GA", "Caldwell, Carlson, Elliott & DeLoach, LLP", "ccedlaw.com", "Harmon W. Caldwell", "Fiduciary, Estate & Commercial Real Estate", 3, "/contact/"),
    ("GA", "Williams Teusink, LLC", "williamsteusink.com", "Rick Williams", "Real Estate Litigation & Title Clearance", 1, "/contact/"),
    ("GA", "The Robbins Firm", "robbinsfirm.com", "Richard Robbins", "Real Estate Litigation & Land Use", 1, "/contact/"),
    ("GA", "Meyring Law Firm", "meyringlaw.com", "Robert Meyring", "Probate, Estate & Heirship Litigation", 3, "/contact/"),
    ("GA", "Brian M. Douglas & Associates, LLC", "atlantagaestateplanning.com", "Brian M. Douglas", "Probate, Trust Litigation & Real Estate", 3, "/contact/"),
    ("GA", "Parker, Hudson, Rainer & Dobbs LLP", "phrd.com", "Wayne Hillis", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Arnall Golden Gregory LLP", "agg.com", "Jonathan E. Eady", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("GA", "Morris, Manning & Martin, LLP", "mmmlaw.com", "Robert C. Threlkeld", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("GA", "Taylor English Duma LLP", "taylorenglish.com", "Marc A. Taylor", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Swift, Currie, McGhee & Hiers, LLP", "swiftcurrie.com", "Terry O. Brantley", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Drew Eckl & Farnham, LLP", "deflaw.com", "Joseph C. Chancey", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Freeman Mathis & Gary, LLP", "fmglaw.com", "Ben Mathis", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("GA", "Goodman McGuffey LLP", "gm-llp.com", "Robert A. Luskin", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("GA", "Hall Booth Smith, P.C.", "hallboothsmith.com", "John E. Hall", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("GA", "HunterMaclean", "huntermaclean.com", "Bradford G. Johnson", "Real Estate Litigation & Probate", 1, "/contact/"),
    ("GA", "Oliver Maner LLP", "olivermaner.com", "Patrick T. O'Connor", "Real Estate, Probate & Trial Litigation", 3, "/contact/"),
    ("GA", "Bouhan Falligant LLP", "bouhan.com", "Benjamin W. Karpf", "Real Estate, Estate Planning & Litigation", 1, "/contact/"),
    ("GA", "Weiner, Shearouse, Weitz, Greenberg & Shawe, LLC", "wswgs.com", "William Shearouse", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("GA", "Hull Barrett, PC", "hullbarrett.com", "Mark S. Burgess", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("GA", "Fulcher Hagler LLP", "fulcherlaw.com", "W. Cameron Nixon", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("GA", "Warlick, Stebbins, Murray & Chew, LLP", "warlicklaw.com", "Charles C. Stebbins", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("GA", "Jones Cork, LLP", "jonescork.com", "H. Jerome Strickland", "Real Estate, Probate & Trial Litigation", 3, "/contact/"),
    ("GA", "James-Bates-Brannan-Groover-LLP", "jamesbates.com", "Duke R. Groover", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("GA", "Chambless, Higdon, Richardson, Katz & Griggs, LLP", "chamblesslaw.com", "Joseph H. Chambless", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Sell & Melton LLP", "sell-melton.com", "John A. Draughon", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("GA", "Martin Snow, LLP", "martinsnow.com", "John T. McGoldrick", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("GA", "Page, Scrantom, Sprouse, Tucker & Ford, P.C.", "psstf.com", "W.G. Scrantom", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("GA", "Hatcher, Stubbs, Fleishel & Stewart, LLP", "hatcherstubbs.com", "J. Barrington Vaught", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("GA", "Pope McGlamry, P.C.", "pmfirm.com", "C. Neal Pope", "Civil Trial Practice & Asset Recovery", 4, "/contact/"),
    ("GA", "Blasingame, Burch, Garrard & Ashley, P.C.", "bbga.com", "Henry G. Garrard", "Trial Practice & Real Estate Disputes", 4, "/contact/"),
    ("GA", "Fortson, Bentley and Griffin, P.A.", "fbg-law.com", "Edwin Fortson", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("GA", "Bondurant Mixson & Elmore LLP", "bmelaw.com", "Emmet J. Bondurant", "Complex Trial & Real Estate Litigation", 4, "/contact/"),
    ("GA", "King & Spalding LLP (GA)", "kslaw.com", "Robert D. Hays", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Alston & Bird LLP (GA)", "alston.com", "Richard R. Hays", "Real Estate Litigation & Distressed Debt", 1, "/contact/"),
    ("GA", "Troutman Pepper Hamilton Sanders LLP (GA)", "troutman.com", "Thomas E. Reilly", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Kilpatrick Townsend & Stockton LLP (GA)", "ktslaw.com", "J. Henry Walker", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("GA", "Eversheds Sutherland (US) LLP (GA)", "eversheds-sutherland.com", "Mark D. Wasserman", "Real Estate Litigation & Tax", 1, "/contact/"),
    ("GA", "Bryan Cave Leighton Paisner LLP (GA)", "bclplaw.com", "William V. Custer", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Burr & Forman LLP (GA)", "burr.com", "Erich N. Durlacher", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Baker Donelson (GA)", "bakerdonelson.com", "Linda A. Klein", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("GA", "Nelson Mullins Riley & Scarborough LLP (GA)", "nelsonmullins.com", "Michael E. Hollingsworth", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Womble Bond Dickinson (US) LLP (GA)", "womblebonddickinson.com", "G. William Finch", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Adams and Reese LLP (GA)", "adamsandreese.com", "Jeffrey A. Wurst", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("GA", "Phelps Dunbar LLP (GA)", "phelps.com", "Karl J. Koch", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("GA", "Balch & Bingham LLP (Atlanta)", "balch.com", "Stan Blanton", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("GA", "Bradley Arant Boult Cummings LLP (GA)", "bradley.com", "Sidney J. Nurkin", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("GA", "Maynard Nexsen PC (GA)", "maynardnexsen.com", "Jeff Friedman", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("GA", "Fox Rothschild LLP (GA)", "foxrothschild.com", "Darryl J. May", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Chamberlain, Hrdlicka, White, Williams & Aughtry (GA)", "chamberlainlaw.com", "David D. Aughtry", "Tax Controversy & Real Estate Practice", 1, "/contact/"),
    ("GA", "Berman Fink Van Horn P.C.", "bfvlaw.com", "Benjamin I. Fink", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Krevolin & Horst, LLC", "khlawfirm.com", "Douglas P. Krevolin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Bloom Parham, LLP", "bloom-law.com", "Stephen M. Parham", "Real Estate Litigation & Land Disputes", 1, "/contact/"),
    ("GA", "Schulten Ward Turner & Weiss, LLP", "swtlaw.com", "Kevin L. Ward", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("GA", "Scrudder Bass Quillian Horlock Taylor & Lazarus, P.C.", "scrudderbass.com", "Glenn S. Bass", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Weinberg Wheeler Hudgins Gunn & Dial", "wwhgd.com", "David A. Dial", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("GA", "Hawkins Parnell & Young, LLP", "hpylaw.com", "Jack N. Sibley", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Carlock, Copeland & Stair, LLP", "carlockcopeland.com", "Thomas S. Carlock", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("GA", "Moffett, Penick & Frazier", "mpflaw.com", "F. Carlton King", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("GA", "Webb, Klase & Lemond, LLC", "webbllc.com", "Edward A. Webb", "Commercial Trial & Property Rights", 4, "/contact/"),
    ("GA", "Gass Turek LLC (GA)", "gassturek.com", "J. Ric Gass", "Civil Trial & Commercial Litigation", 4, "/contact/"),
    ("GA", "The Saylor Law Firm LLP", "saylorlaw.com", "Linda Saylor", "Probate, Estate & Heirship Litigation", 3, "/contact/"),
    ("GA", "Hungeling Law", "hungelinglaw.com", "David Hungeling", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("GA", "Duncan Adams Law", "duncanadamslaw.com", "Duncan Adams", "Real Estate Litigation & Quiet Title", 1, "/contact/"),
    ("GA", "The Finley Firm, P.C.", "thefinleyfirm.com", "J. Benjamin Finley", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("GA", "Stiles & Associates LLC", "stileslaw.com", "Kevin Stiles", "Real Estate Litigation & Title Clearance", 1, "/contact/"),
    ("GA", "Lueder, Larkin & Hunter, LLC", "luederlaw.com", "John T. Lueder", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("GA", "Lipshutz Greenblatt LLC", "lgattorneys.com", "Randall M. Lipshutz", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("GA", "Lazega & Johanson LLC", "ljlaw.com", "Jay Lazega", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("GA", "Winter Capriola Schwartz, P.C.", "wcs-law.com", "Stephen A. Winter", "Real Estate, Tax Sale & Excess Funds", 1, "/contact/"),
    ("GA", "Weissman PC (Atlanta)", "weissman.law", "Bradley A. Hutchins", "Tax Sale, Excess Funds & Foreclosure", 1, "/contact/"),
    ("GA", "Winter Law Group (Atlanta)", "winterlawgroup.com", "Stephen A. Winter", "Tax Sale Excess Funds & Real Estate", 1, "/contact/"),
    ("GA", "Phillips Law Firm LLC", "phillipslawga.com", "Christopher D. Phillips", "Foreclosure, Excess Funds & Title", 1, "/contact/"),
    ("GA", "McCalla Raymer Leibert Pierce, LLC", "mccalla.com", "Martin M. Stone", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("GA", "Rubin Lublin, LLC", "rubinlublin.com", "Peter L. Lublin", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("GA", "Brock & Scott, PLLC (GA)", "brockandscott.com", "Thomas Brock", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("GA", "Aldridge Pite, LLP (GA)", "aldridgepite.com", "John Aldridge", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("GA", "Padgett Law Group (GA)", "padgettlawgroup.com", "David Padgett", "Foreclosure & Real Estate Litigation", 1, "/contact/"),
    ("GA", "Robertson, Anschutz, Schneid, Crane & Partners, PLLC (GA)", "rasflaw.com", "Robert Anschutz", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("GA", "Marinosci Law Group, P.C. (GA)", "mlg-defaultlaw.com", "Gary Marinosci", "Foreclosure, Title & Creditors Rights", 1, "/contact/"),
    ("GA", "Tromberg, Morris & Poulin, PLLC (GA)", "tmppllc.com", "Andrea Tromberg", "Foreclosure & Real Estate Practice", 1, "/contact/"),
    ("GA", "Albertelli Law (GA)", "albertellilaw.com", "James E. Albertelli", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("GA", "Shapiro & Swertfeger, LLP", "shapiro-swertfeger.com", "Gerald M. Shapiro", "Foreclosure & Real Estate Litigation", 1, "/contact/"),
    ("GA", "Johnson & Freedman, LLC", "jflegal.com", "C. David Johnson", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("GA", "Campbell & Brannon, L.L.C.", "campbellandbrannon.com", "Michael Brannon", "Real Estate, Title & Foreclosure", 1, "/contact/"),
    ("GA", "McMichael & Gray, PC", "mcmichaelandgray.com", "Randy McMichael", "Real Estate, Title Clearance & Foreclosure", 1, "/contact/"),
    ("GA", "Perrie & Associates, LLC", "perrielaw.com", "Robert Perrie", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("GA", "Weinstock & Scavo, P.C.", "wslaw.net", "Michael Weinstock", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Dorough & Dorough, LLC", "doroughlaw.com", "David Dorough", "Real Estate, HOA & Land Law", 2, "/contact/"),
    ("GA", "NowackHoward, LLC", "nowackhoward.com", "Julie McGhee Howard", "HOA Foreclosure & Real Estate Law", 2, "/contact/"),
    ("GA", "Gowens, Price & Associates, LLC", "gowensprice.com", "Michael Gowens", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("GA", "The Law Office of Paul Black", "paulblacklaw.com", "Paul Black", "Probate, Trust & Estate Litigation", 3, "/contact/"),
    ("GA", "Hurban Law, LLC", "hurbanlaw.com", "K. Gabriel Hurban", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("GA", "O'Kelley & Sorohan, Attorneys at Law, LLC", "oslawllc.com", "Joe O'Kelley", "Real Estate, Title Clearance & Foreclosure", 1, "/contact/"),
    ("GA", "Cook & James, LLC", "cookandjames.com", "Kara Cook", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("GA", "Bagwell Holt Smith P.A. (GA)", "bhlawoffice.com", "Michael R. Bagwell", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("GA", "Gaslowitz Frankel LLC", "gaslowitzfrankel.com", "Adam R. Gaslowitz", "Fiduciary, Estate & Trust Litigation", 3, "/contact/"),
    ("GA", "The Farrell Law Firm, PC", "farrellfirm.com", "Patrick Farrell", "Probate, Estate Planning & Real Estate", 3, "/contact/"),
    ("GA", "Estate Law Center USA", "estatelawcenter.com", "David M. Lefton", "Probate & Estate Administration", 3, "/contact/"),
    ("GA", "Schreeder, Wheeler & Flint, LLP", "swfllp.com", "David Flint", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("GA", "Bondurant, Mixson & Elmore LLP (Atlanta)", "bmelaw.com", "H. Lamar Mixson", "Commercial Litigation & Property Rights", 4, "/contact/"),
]

print(f"Loaded {len(CANDIDATES)} Georgia candidate practices.")
