"""North Carolina Law Firm Pipeline Candidates"""

CANDIDATES = [
    # Charlotte & Western NC
    ("NC", "Ward and Smith, P.A.", "wardandsmith.com", "Brad Evans", "Real Estate Litigation & Tax Foreclosures", 1, "/contact-us/"),
    ("NC", "Hedrick Gardner Kincheloe & Garofalo LLP", "hedrickgardner.com", "Paul Lawrence", "Commercial Litigation & Real Estate", 4, "/contact/"),
    ("NC", "Morningstar Law Group", "morningstarlawgroup.com", "Randy Whitmeyer", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("NC", "Bell, Davis & Pitt, P.A.", "belldavispitt.com", "Arthur Pitt", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Carruthers & Roth, P.A.", "crlaw.com", "Chris Flurry", "Real Estate Litigation & Foreclosure", 1, "/contact/"),
    ("NC", "Roberson Haworth & Reese, PLLC", "rhrlaw.com", "Alan Haworth", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("NC", "Brooks, Pierce, McLendon, Humphrey & Leonard, L.L.P.", "brookspierce.com", "Reid L. Phillips", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Poyner Spruill LLP", "poynerspruill.com", "Dan Cahill", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Parker Poe Adams & Bernstein LLP", "parkerpoe.com", "Tom Griffin", "Real Estate Litigation & Development", 1, "/contact/"),
    ("NC", "Robinson, Bradshaw & Hinson, P.A.", "robinsonbradshaw.com", "Allen K. Robertson", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("NC", "Smith Anderson Blount Dorsett Mitchell & Jernigan, L.L.P.", "smithlaw.com", "Byron B. Kirkland", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Wyrick Robbins Yates & Ponton LLP", "wyrick.com", "Jimmy Yates", "Real Estate Litigation & Commercial Law", 4, "/contact/"),
    ("NC", "Manning, Fulton & Skinner, P.A.", "manningfulton.com", "Barry Mann", "Real Estate, Eminent Domain & Litigation", 1, "/contact/"),
    ("NC", "Schell Bray PLLC", "schellbray.com", "Michael R. Schell", "Real Estate, Estate Planning & Probate", 3, "/contact/"),
    ("NC", "Tuggle Duggins P.A.", "tuggleduggins.com", "Richard W. Tuggle", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Higgins Benjamin, PLLC", "greensborolaw.com", "John F. Higgins", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Johnston, Allison & Hord, P.A.", "jahlaw.com", "David W. Gilpin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "James, McElroy & Diehl, P.A.", "jmdlaw.com", "P. Marshall Yoder", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("NC", "Horack, Talley, Pharr & Lowndes, P.A.", "horacktalley.com", "Keith B. Nichols", "Real Estate Litigation & HOA Law", 2, "/contact/"),
    ("NC", "Moon Wright & Houston, PLLC", "mwhlaw.com", "Richard S. Wright", "Insolvency, Creditors Rights & Real Estate", 1, "/contact/"),
    ("NC", "Cranfill Sumner LLP", "cshlaw.com", "Marshall Wall", "Real Estate Litigation & Civil Defense", 4, "/contact/"),
    ("NC", "Young Moore and Henderson P.A.", "youngmoorelaw.com", "David M. Duke", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("NC", "Teague Campbell Dennis & Gorham, LLP", "teaguecampbell.com", "Dayle Flammia", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "McAngus Goudelock & Courie LLC (NC)", "mgclaw.com", "Jay Courie", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("NC", "Gallivan, White & Boyd, P.A. (NC)", "gwblawfirm.com", "C. Stuart Mauney", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Tharrington Smith, LLP", "tharringtonsmith.com", "F. Hill Allen", "Real Estate Litigation & Education Law", 4, "/contact/"),
    ("NC", "Cheshire Parker Schneider, PLLC", "cheshirepark.com", "Joseph B. Cheshire", "Civil Trial & Asset Forfeiture", 4, "/contact/"),
    ("NC", "Roberts & Stevens, P.A.", "roberts-stevens.com", "Marc Rudow", "Real Estate Litigation & Probate", 1, "/contact/"),
    ("NC", "Van Winkle Law Firm", "vwlawfirm.com", "Larry S. McDevitt", "Real Estate Litigation, Probate & Title", 1, "/contact/"),
    ("NC", "McGuire, Wood & Bissette, P.A.", "mwbavl.com", "Sabrina Rockoff", "Real Estate, Estate Planning & Litigation", 3, "/contact/"),
    ("NC", "Ferikes & Bleynat, PLLC", "ashevillelitigators.com", "Edward L. Bleynat", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Spivey Law Group (Charlotte)", "spiveylawnc.com", "David C. Spivey", "Tax Foreclosure Surplus & Upset Bids", 1, "/contact/"),
    ("NC", "Thompson Law Firm, PLLC (Raleigh)", "thompsonlawnc.com", "Gregory B. Thompson", "Surplus Proceeds Recovery under 105-374", 1, "/contact/"),
    ("NC", "Hutchens Law Firm LLP", "hutchenslawfirm.com", "H. Terry Hutchens", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("NC", "Brock & Scott, PLLC (NC)", "brockandscott.com", "Thomas Brock", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("NC", "The Law Firm of Hutchens, Senter, Kellam & Pettit, P.A.", "hutchenslawfirm.com", "Terry Hutchens", "Foreclosure & Real Estate Practice", 1, "/contact/"),
    ("NC", "Rogers, Townsend & Thomas, PC (NC)", "rogerstownsend.com", "John Rogers", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("NC", "Shapiro & Ingle, LLP", "shapiro-ingle.com", "Jason K. Ingle", "Foreclosure & Real Estate Practice", 1, "/contact/"),
    ("NC", "The Sasser Law Firm", "sasserbankruptcy.com", "Philip Sasser", "Foreclosure Defense & Debt Relief", 2, "/contact/"),
    ("NC", "Law Offices of John T. Orcutt", "billsbills.com", "John T. Orcutt", "Foreclosure Defense & Consumer Bankruptcy", 2, "/contact/"),
    ("NC", "Brady & Kosofsky, PA", "bradylawfirm.biz", "Marc Kosofsky", "Real Estate, Title & Foreclosure Defense", 2, "/contact/"),
    ("NC", "Bagwell Holt Smith P.A.", "bhlawoffice.com", "Michael R. Bagwell", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("NC", "Cloninger & Perez, PLLC", "cloningerperez.com", "Neil Perez", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("NC", "Culp Elliott & Carpenter, P.L.L.C.", "ceclaw.com", "William C. Culp", "Tax Controversy, Estate Planning & Real Estate", 3, "/contact/"),
    ("NC", "Rayburn Cooper & Durham, P.A.", "rcdlaw.net", "C. Richard Rayburn", "Insolvency, Real Estate & Creditors Rights", 1, "/contact/"),
    ("NC", "Womble Bond Dickinson (US) LLP (NC)", "womblebonddickinson.com", "Betty Temple", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Fox Rothschild LLP (NC)", "foxrothschild.com", "Matthew Nis Leerberg", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Nexsen Pruet, LLC (NC)", "nexsenpruet.com", "Peter A. Santos", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Maynard Nexsen PC (NC)", "maynardnexsen.com", "Leighton Lord", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("NC", "Bradley Arant Boult Cummings LLP (NC)", "bradley.com", "Christopher C. Lam", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("NC", "K&L Gates LLP (NC)", "klgates.com", "Brett E. Buda", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("NC", "McGuireWoods LLP (NC)", "mcguirewoods.com", "J. Tracy Walker", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Moore & Van Allen PLLC", "mvalaw.com", "Thomas D. Myrick", "Real Estate Litigation & Distressed Property", 1, "/contact/"),
    ("NC", "Alston & Bird LLP (NC)", "alston.com", "David E. Brown", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("NC", "Katzenstein & Lorance", "kandllawfirm.com", "Charles Katzenstein", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("NC", "Blanco Tackabery & Matamoros, P.A.", "blancolaw.com", "Peter J. Juran", "Real Estate, Probate & Tax Litigation", 3, "/contact/"),
    ("NC", "Craige Jenkins Liipfert & Walker LLP", "craigejenkins.com", "Gordon Jenkins", "Real Estate, Probate & Title Clearance", 3, "/contact/"),
    ("NC", "Allman Spry Davis Siegel & Asbill, P.A.", "allmanspry.com", "C. Edwin Allman", "Real Estate, Probate & Land Use", 3, "/contact/"),
    ("NC", "Bennett & Guthrie, P.L.L.C.", "bennett-guthrie.com", "Richard Bennett", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Kilpatrick Townsend & Stockton LLP (NC)", "ktslaw.com", "Steve Gardner", "Real Estate Litigation & Land Use", 1, "/contact/"),
    ("NC", "Womble Carlyle Sandridge & Rice / Womble Bond (NC)", "womblebonddickinson.com", "Merrick Benn", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("NC", "Hendrick Bryant Nerhood Sanders & Otis LLP", "hendricklawfirm.com", "Matthew Hendrick", "Eminent Domain, Real Estate & Trial Law", 1, "/contact/"),
    ("NC", "Morrow Porter Vermitsky & Fowler, PLLC", "mpvlaw.com", "John Morrow", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("NC", "Stowers & Nardone, PLLC", "stowerslaw.com", "David Stowers", "Real Estate Litigation & Foreclosure", 2, "/contact/"),
    ("NC", "The Law Offices of Cheryl David", "cheryldavid.com", "Cheryl David", "Probate, Estate Planning & Trust Law", 3, "/contact/"),
    ("NC", "Ragsdale Liggett PLLC", "rl-law.com", "Frank Liggett", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("NC", "Howard, Stallings, From, Atkins, Angell & Davis, P.A.", "hsfad.com", "Robert Stallings", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("NC", "Hatch, Little & Bunn, L.L.P.", "hatchlittlebunn.com", "William Hatch", "Real Estate Litigation & HOA Foreclosure", 2, "/contact/"),
    ("NC", "Harris Sarratt & Hodges, LLP", "hshlawfirm.com", "Donald Harris", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("NC", "Batten Lee PLLC", "battenlee.com", "Kenneth Batten", "Civil Trial & Property Litigation", 4, "/contact/"),
    ("NC", "Ellis & Winters LLP", "elliswinters.com", "Leslie C. Packer", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("NC", "Burns, Day & Presnell, P.A.", "bdp-law.com", "James Burns", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("NC", "Jordan Price Wall Gray Jones & Carlton, PLLC", "jordanprice.com", "Henry W. Jones", "Real Estate, HOA & Administrative Law", 2, "/contact/"),
    ("NC", "Nichols, Choi & Lee, PLLC", "ncl-law.com", "M. Jackson Nichols", "Administrative Law & Property Disputes", 4, "/contact/"),
    ("NC", "Hedrick Kepley, PLLC", "hedrickkepley.com", "Jeffrey Hedrick", "Real Estate, Probate & Commercial Law", 3, "/contact/"),
    ("NC", "Vann Attorneys, PLLC", "vannattorneys.com", "James R. Vann", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Gailor Hunt Jenkins Davis Taylor & Gibbs, PLLC", "divorceistough.com", "Carole Gailor", "Complex Asset Division & Property Litigation", 4, "/contact/"),
    ("NC", "Hopler, Wilms, & Hanna, PLLC", "hoplerwilms.com", "Adam Hopler", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("NC", "Kennon Craver, PLLC", "kennoncraver.com", "Joel M. Craig", "Real Estate Litigation & Land Use", 1, "/contact/"),
    ("NC", "Pulley, Watson, King & Lischer, P.A.", "pulleywatson.com", "Tracy Lischer", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("NC", "Baddour, Parker, Hine & Hale, P.C.", "baddourparker.com", "Philip A. Baddour", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("NC", "Everett Gaskins Hancock LLP", "eghlaw.com", "Ed Gaskins", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("NC", "Tharrington Smith LLP (Raleigh)", "tharringtonsmith.com", "Wade Smith", "Trial Practice & Complex Litigation", 4, "/contact/"),
    ("NC", "Cauley Pridgen, P.A.", "cauleypridgen.com", "James Cauley", "Real Estate, Municipal & Land Use", 4, "/contact/"),
    ("NC", "Rose Harrison Gilreath & Powers, P.C.", "outerbankslaw.com", "John Harrison", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("NC", "Shipman & Wright, LLP", "shipmanlaw.com", "Gary Shipman", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("NC", "Crossley McIntosh Collier Hanley & Edes, PLLC", "cmclawfirm.com", "Douglas Collier", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("NC", "Rountree Losee LLP", "rountreelosee.com", "George Rountree", "Real Estate Litigation & Maritime", 4, "/contact/"),
    ("NC", "Marshall, Williams & Gorham, L.L.P.", "mwglawfirm.com", "Lonnie Williams", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("NC", "Hodges & Coxe PC", "hodgescoxe.com", "Bradley Coxe", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("NC", "Murchison, Taylor & Gibson, PLLC", "murchisontaylor.com", "Michael Murchison", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Lea/Schultz Law, PLLC", "leaschultzlaw.com", "James Lea", "Civil Trial & Property Litigation", 4, "/contact/"),
    ("NC", "Craige & Fox, PLLC", "craigeandfox.com", "Lauren Fox", "Real Estate, Probate & Civil Litigation", 3, "/contact/"),
    ("NC", "Hogue Hill, LLP", "hoguehill.com", "David Hill", "Real Estate, Title & Probate Law", 3, "/contact/"),
    ("NC", "Block, Crouch, Keeter, Behm & Sayed, LLP", "bcklaw.com", "Christopher Keeter", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("NC", "Woodruff & Associates, P.A.", "woodrufflawfirm.com", "Gordon Woodruff", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("NC", "The Law Corner", "thelawcorner.com", "Brent Adams", "Real Estate, Foreclosure & Family Law", 2, "/contact/"),
    ("NC", "Brady Law Firm, PLLC", "bradylawnc.com", "Charles Brady", "Real Estate, HOA & Title Law", 2, "/contact/"),
    ("NC", "Kirk, Kirk, Howell, Cutler & Thomas, L.L.P.", "kirkkirklaw.com", "Joseph T. Howell", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("NC", "Allen, Stahl & Kilbourne, PLLC", "asklawnc.com", "James Kilbourne", "Real Estate Litigation & Title Law", 1, "/contact/"),
]

print(f"Loaded {len(CANDIDATES)} North Carolina candidate practices.")
