"""Tennessee Law Firm Pipeline Candidates"""

CANDIDATES = [
    # Nashville & Middle Tennessee
    ("TN", "Bass, Berry & Sims PLC", "bassberry.com", "Todd J. Rolapp", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Butler Snow LLP (TN)", "butlersnow.com", "Christopher R. Maddux", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Baker, Donelson, Bearman, Caldwell & Berkowitz, PC", "bakerdonelson.com", "Timothy M. Lupinacci", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("TN", "Waller Lansden Dortch & Davis / Holland & Knight", "hklaw.com", "Matthew R. Burnstein", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("TN", "Bradley Arant Boult Cummings LLP (TN)", "bradley.com", "Jonathan M. Skeeters", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Gullett Sanford Robinson & Martin PLLC", "gsrm.com", "Phillip G. Young", "Real Estate Litigation & Estate Planning", 3, "/contact/"),
    ("TN", "Bone McAllester Norton / Spencer Fane", "spencerfane.com", "Charles Robert Bone", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Dodson Parker Behm & Capparella, PC", "dodsonparker.com", "Harlan Dodson", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Leitner, Williams, Dooley & Napolitan, PLLC", "leitnerfirm.com", "Paul R. Leitner", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Chambliss, Bahner & Stophel, P.C.", "chamblisslaw.com", "Mark A. Turner", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Miller & Martin PLLC", "millermartin.com", "Scott Parrish", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Luther-Anderson, P.L.L.P.", "lutheranderson.com", "William A. Luther", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TN", "Gearhiser, Peters, Elliott & Cannon, P.L.L.C.", "gearhiserpeters.com", "R. Wayne Peters", "Real Estate, Probate & Tax Litigation", 3, "/contact/"),
    ("TN", "Patrick, Beard, Schulman & Jacoway, P.C.", "pbsjlaw.com", "Gary R. Patrick", "Real Estate Litigation & Civil Trial", 4, "/contact/"),
    ("TN", "Speek, Webb, Turner & Newkirk", "speekandwebb.com", "Jerry Speek", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("TN", "Evans Petree PC", "evanspetree.com", "Joseph B. Walker", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("TN", "Glankler Brown, PLLC", "glankler.com", "Michael P. Coury", "Insolvency, Real Estate & Creditors Rights", 1, "/contact/"),
    ("TN", "Burch, Porter & Johnson, PLLC", "bpjlaw.com", "Les Jones", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("TN", "Wyatt, Tarrant & Combs, LLP (TN)", "wyattfirm.com", "Franklin H. Farris", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Harris Shelton Hanover Walsh, PLLC", "harrisshelton.com", "Brett Hughes", "Real Estate, Probate & Banking", 3, "/contact/"),
    ("TN", "Martin, Tate, Morrow & Marston, P.C.", "martintate.com", "Lee L. Piovarcy", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Apperson Crump PLC", "appersoncrump.com", "Albert C. Harvey", "Real Estate, Probate & Trial Litigation", 3, "/contact/"),
    ("TN", "Pietrangelo Cook PLC", "plegal.com", "John Cook", "Real Estate Litigation & Construction", 4, "/contact/"),
    ("TN", "Kramer Rayson LLP", "kramer-rayson.com", "John T. Johnson", "Real Estate, Probate & Employment", 3, "/contact/"),
    ("TN", "Woolf, McClane, Bright, Allen & Carpenter, PLLC", "wmbac.com", "J. Chadwick Hatmaker", "Real Estate Litigation & Tax", 1, "/contact/"),
    ("TN", "Egerton, McAfee, Armistead & Davis, P.C.", "emlaw.com", "Cheryl G. Rice", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Bernstein, Stair & McAdams LLP", "bsmlaw.com", "Bernard E. Bernstein", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("TN", "Eldridge & Blakney, PC", "eblaw.us", "David M. Eldridge", "Trial Practice & Real Estate Litigation", 4, "/contact/"),
    ("TN", "Lewis Thomason, P.C.", "lewisthomason.com", "Lisa Ramsay Cole", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Wimberly Lawson Wright Daves & Jones, PLLC", "wimberlylawson.com", "Ronald G. Daves", "Civil Litigation & Commercial Practice", 4, "/contact/"),
    ("TN", "Kennerly, Montgomery & Finley, P.C.", "kmfpc.com", "Robert H. Green", "Real Estate Litigation, Municipal & Tax", 1, "/contact/"),
    ("TN", "Hodges, Doughty & Carson, PLLC", "hdclaw.com", "Dean B. Farmer", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("TN", "Arnett, Draper & Draper, LLP", "adlawfirm.com", "Jack Draper", "Commercial Litigation & Real Estate", 4, "/contact/"),
    ("TN", "Sherrard Roe Voigt & Harbison, PLC", "srvhlaw.com", "John Voigt", "Real Estate Litigation & Healthcare", 4, "/contact/"),
    ("TN", "Neal & Harwell, PLC", "nealharwell.com", "Aubrey B. Harwell", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("TN", "Riley & Jacobson, PLC", "rjfirm.com", "Mack A. Riley", "Real Estate Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Wiseman Ashworth Trauger", "watlaw.com", "Thomas W. Wiseman", "Civil Trial & Real Estate Litigation", 4, "/contact/"),
    ("TN", "Cornelius & Collins, LLP", "cornelius-collins.com", "Brian Holmes", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Trauger & Tuke", "trauger-tuke.com", "Byron R. Trauger", "Real Estate Litigation & Public Agency", 4, "/contact/"),
    ("TN", "Ortale Kelley Herbert & Crawford", "ortalekelley.com", "Daniel C. Herbert", "Real Estate Litigation & Insurance", 4, "/contact/"),
    ("TN", "Lieff Cabraser Heimann & Bernstein, LLP (TN)", "lieffcabraser.com", "Mark P. Chalos", "Complex Trial & Asset Recovery", 4, "/contact/"),
    ("TN", "Adams and Reese LLP (Nashville)", "adamsandreese.com", "Gif Thornton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Burr & Forman LLP (Nashville)", "burr.com", "Ken Bryant", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Phelps Dunbar LLP (TN)", "phelps.com", "Robert P. Vance", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("TN", "Maynard Nexsen PC (TN)", "maynardnexsen.com", "David B. Anderson", "Real Estate & Creditors Rights", 1, "/contact/"),
    ("TN", "Manier & Herod, P.C.", "manierherod.com", "Michael E. Evans", "Surety, Insolvency & Real Estate", 1, "/contact/"),
    ("TN", "White & Reasor, PLC", "whitereasor.com", "David White", "Real Estate, Probate & Corporate", 3, "/contact/"),
    ("TN", "Frost Brown Todd LLP (TN)", "fbtlaw.com", "Mekesha H. Montgomery", "Real Estate Litigation & Finance", 1, "/contact/"),
    ("TN", "Nelson Mullins Riley & Scarborough LLP (TN)", "nelsonmullins.com", "Larry W. Bridgesmith", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Stites & Harbison, PLLC (TN)", "stites.com", "Gregory D. Smith", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Dickinson Wright PLLC (TN)", "dickinsonwright.com", "Harlan I. Prater", "Real Estate Litigation & Insolvency", 1, "/contact/"),
    ("TN", "Gordon Rees Scully Mansukhani, LLP (TN)", "grsm.com", "Heather C. Rogers", "Real Estate Litigation & Commercial Defense", 4, "/contact/"),
    ("TN", "Hall Booth Smith, P.C. (TN)", "hallboothsmith.com", "Karl M. Braun", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("TN", "Spicer Rudstrom, PLLC", "spicerfirm.com", "Marc O. Dedman", "Real Estate Litigation & Insurance Defense", 4, "/contact/"),
    ("TN", "Batson Nolan PLC", "batsonnolan.com", "Dan L. Nolan", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TN", "Cunningham, Mitchell & Rocconi", "cmrlegal.com", "Mark Mitchell", "Real Estate, Probate & Civil Trial", 3, "/contact/"),
    ("TN", "Rainey, Kizer, Reviere & Bell, P.L.C.", "raineykizer.com", "Russell E. Reviere", "Real Estate Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Waldrop & Hall, P.A.", "waldrophall.com", "H. David Hall", "Real Estate, Probate & Civil Law", 3, "/contact/"),
    ("TN", "Pentecost, Glenn & Mauldin, PLLC", "pgmlawfirm.com", "James I. Pentecost", "Civil Trial Practice & Local Government", 4, "/contact/"),
    ("TN", "Hunter, Smith & Davis, LLP", "hsdlaw.com", "Mark S. Dessauer", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Wilson Worley, PC", "wilsonworley.com", "Richard M. Currie", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "Herndon, Coleman, Brading & McKee, LLP", "hcblaw.com", "J. Matthew Bolton", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TN", "Milligan & Coleman PLLC", "milligancoleman.com", "Mark A. Cowan", "Real Estate, Probate & Trial Practice", 3, "/contact/"),
    ("TN", "Barger & Gaines (TN)", "bargergaines.com", "Paul Barger", "Civil Trial & Asset Defense", 4, "/contact/"),
    ("TN", "The Higgins Firm, PLLC", "higginsfirm.com", "Jim Higgins", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("TN", "Cole Law Group, PC", "colelawgrouppc.com", "Peter Cole", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TN", "Rogers, Kamm & Shea", "rkslawgroup.com", "Helen Sfikas Rogers", "Probate, Asset Division & Litigation", 3, "/contact/"),
    ("TN", "Patterson Intellectual Property Law, P.C.", "iplawgroup.com", "Edward D. Lanquist", "Civil Litigation & Commercial Practice", 4, "/contact/"),
    ("TN", "Bednarz & Bednarz", "bednarzlaw.com", "Joe Bednarz", "Civil Trial Practice & Property Claims", 4, "/contact/"),
    ("TN", "Kinnard Law", "kinnardlaw.com", "Randall L. Kinnard", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("TN", "Rocky McElhaney Law Firm", "rockylawfirm.com", "Rocky McElhaney", "Civil Trial & Property Recovery", 4, "/contact/"),
    ("TN", "Hughes & Coleman Injury Lawyers (TN)", "hughesandcoleman.com", "Lee Coleman", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Pohl & Berk, LLP", "pohlandberk.com", "Mark Pohl", "Civil Trial Practice & Asset Disputes", 4, "/contact/"),
    ("TN", "Rutherford, DeMarco & White, PLLC", "rdwlawfirm.com", "David Rutherford", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TN", "McNabb, Bragorgos, Burgess & Sorin, PLLC", "mbb-law.com", "Leland M. McNabb", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "Glassman, Wyatt, Tuttle & Cox, P.C.", "glassmanfirm.com", "Richard Glassman", "Civil Trial & Commercial Litigation", 4, "/contact/"),
    ("TN", "Bailey & Greer, PLLC", "baileygreer.com", "Thomas R. Greer", "Civil Trial Practice & Property Law", 4, "/contact/"),
    ("TN", "The Cochran Firm (Memphis)", "cochranfirm.com", "Jeffrey S. Rosenblum", "Civil Trial & Recovery Practice", 4, "/contact/"),
    ("TN", "Donati Law, PLLC", "donatilaw.com", "Donald A. Donati", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("TN", "Farris Bobango PLC", "farrisbobango.com", "John Bobango", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TN", "The Crone Law Firm, PLC", "cronelawfirmplc.com", "Alan G. Crone", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("TN", "Chancery Court Surplus Practice Group (Davidson)", "carverlawtn.com", "Mark A. Carver", "Chancery Surplus Recovery under 67-5-2510", 1, "/contact/"),
    ("TN", "West Tennessee Tax Sale Group (Shelby)", "yoakumlaw.com", "Brian L. Yoakum", "Tax Sale Excess Proceeds Litigation", 1, "/contact/"),
    ("TN", "Brock & Scott, PLLC (TN)", "brockandscott.com", "Thomas Brock", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("TN", "Marinosci Law Group, P.C. (TN)", "mlg-defaultlaw.com", "Gary Marinosci", "Foreclosure, Title & Creditors Rights", 1, "/contact/"),
    ("TN", "Padgett Law Group (TN)", "padgettlawgroup.com", "David Padgett", "Foreclosure & Real Estate Litigation", 1, "/contact/"),
    ("TN", "Rubin Lublin, LLC (TN)", "rubinlublin.com", "Peter L. Lublin", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("TN", "McCalla Raymer Leibert Pierce, LLC (TN)", "mccalla.com", "Martin M. Stone", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("TN", "Robertson, Anschutz, Schneid, Crane & Partners, PLLC (TN)", "rasflaw.com", "Robert Anschutz", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("TN", "Aldridge Pite, LLP (TN)", "aldridgepite.com", "John Aldridge", "Foreclosure & Real Estate Practice", 1, "/contact/"),
    ("TN", "Mackie Wolf Zientz & Mann, P.C. (TN)", "mwzmlaw.com", "Keller Mackie", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
]

print(f"Loaded {len(CANDIDATES)} Tennessee candidate practices.")
