"""Texas Law Firm Pipeline Candidates"""

CANDIDATES = [
    # Houston & Harris County
    ("TX", "The Weaver Law Firm", "weaverlawyers.com", "Richard Weaver", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("TX", "The Womack Law Firm", "markwomacklaw.com", "Mark Womack", "Wrongful Foreclosure & Real Estate Litigation", 2, "/contact/"),
    ("TX", "Jeffrey Jackson & Associates, PLLC", "jjacksonpllc.com", "Jeffrey Jackson", "Foreclosure Defense & Real Estate Law", 2, "/contact/"),
    ("TX", "Guzman Law Firm", "guzmanbankruptcy.com", "Hector Guzman", "Foreclosure Defense & Debt Relief", 2, "/contact/"),
    ("TX", "Carrington, Coleman, Sloman & Blumenthal, L.L.P.", "ccsb.com", "Monica W. Latin", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Bell Nunnally & Martin LLP", "bellnunnally.com", "Christopher Trowbridge", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Munsch Hardt Kopf & Harr, P.C.", "munsch.com", "E. Lee Morris", "Insolvency, Real Estate & Creditors Rights", 1, "/contact/"),
    ("TX", "Winstead PC", "winstead.com", "Jeff Matthews", "Real Estate Litigation & Distressed Assets", 1, "/contact/"),
    ("TX", "Jackson Walker LLP", "jw.com", "C. Wade Cooper", "Real Estate Litigation, Eminent Domain & Tax", 1, "/contact/"),
    ("TX", "Cokinos | Young", "cokinoslaw.com", "Gregory M. Cokinos", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Cowles & Thompson, P.C.", "cowlesthompson.com", "David R. Woodward", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("TX", "Kane Russell Coleman Logan PC", "krcl.com", "Joseph M. Coleman", "Insolvency, Creditors Rights & Real Estate", 1, "/contact/"),
    ("TX", "Fee, Smith & Sharp, L.L.P.", "feesmith.com", "Michael P. Sharp", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Scheef & Stone, L.L.P.", "solidcounsel.com", "John Scheef", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Cantey Hanger LLP", "canteyhanger.com", "Michael G. Appleman", "Real Estate, Probate & Trial Litigation", 3, "/contact/"),
    ("TX", "Griffith, Jay & Carman, PLLC", "gjclaw.com", "John Griffith", "Real Estate Litigation & Land Title", 4, "/contact/"),
    ("TX", "Underwood Law Firm, P.C.", "underwoodlawfirm.com", "Gavin Gadberry", "Real Estate, Tax & Trial Practice", 1, "/contact/"),
    ("TX", "Sprouse Shrader Smith PLLC", "sprouselaw.com", "Joel R. Sprouse", "Real Estate, Estate Planning & Litigation", 3, "/contact/"),
    ("TX", "Mullin Hoard & Brown, L.L.P.", "mhba.com", "David Mullin", "Banking, Real Estate & Creditors Rights", 1, "/contact/"),
    ("TX", "Crenshaw, Dupree & Milam, L.L.P.", "cdmlaw.com", "Cecil Kuhne", "Real Estate & Trial Litigation", 4, "/contact/"),
    ("TX", "McCleskey, Harriger, Brazill & Graf, L.L.P.", "mccleskeylaw.com", "Jerry Kolander", "Real Estate, Probate & Litigation", 3, "/contact/"),
    ("TX", "Naman, Howell, Smith & Lee, PLLC", "namanhowell.com", "Larry O. Brady", "Real Estate, Tax & Creditors Rights", 1, "/contact/"),
    ("TX", "Pakis, Giotes, Page & Burleson, P.C.", "pakislaw.com", "David N. Deaconson", "Real Estate, Probate & Litigation", 3, "/contact/"),
    ("TX", "Haley & Olson, P.C.", "haleyolson.com", "Blake Rasner", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("TX", "Beard Kultgen Brophy Bostwick & Dickson, PLLC", "beardkultgen.com", "David Dickson", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TX", "Bickerstaff Heath Delgado Acosta LLP", "bickerstaff.com", "C. Robert Heath", "Real Estate, Eminent Domain & Public Law", 4, "/contact/"),
    ("TX", "McGinnis Lochridge", "mcginnislaw.com", "Doug Dodds", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Armbrust & Brown, PLLC", "abaustin.com", "David Armbrust", "Real Estate Development & Litigation", 4, "/contact/"),
    ("TX", "Allensworth", "allensworthlaw.com", "Will Allensworth", "Construction & Real Estate Litigation", 4, "/contact/"),
    ("TX", "DuBois, Bryant & Campbell, LLP", "dbcllp.com", "Rick DuBois", "Real Estate, Tax & Estate Planning", 3, "/contact/"),
    ("TX", "Wright & Greenhill, P.C.", "wrightgreenhill.com", "Heidi A. Coughlin", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Richards Rodriguez & Skeith LLP", "rrsfirm.com", "Dan Richards", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("TX", "George Brothers Kincaid & Horton LLP", "gbkh.com", "D. Douglas Brothers", "Complex Trial & Real Estate Litigation", 4, "/contact/"),
    ("TX", "Scott Douglass & McConnico LLP", "scottdoug.com", "Steve McConnico", "Trial Litigation & Real Estate Disputes", 4, "/contact/"),
    ("TX", "Enoch Kever PLLC", "enochkever.com", "Craig Enoch", "Appellate & Real Estate Trial Practice", 4, "/contact/"),
    ("TX", "Curney, Farmer, House, Osuna & Jackson, P.C.", "curneyfarmer.com", "David M. Farmer", "Civil Litigation & Trial Practice", 4, "/contact/"),
    ("TX", "Plunkett, Griesenbeck & Elizabeth, Inc.", "pgelaw.com", "Lewin Plunkett", "Real Estate & Civil Litigation", 4, "/contact/"),
    ("TX", "Schmoyer Reinhard LLP", "sr-lawfirm.com", "Shannon B. Schmoyer", "Civil Trial & Commercial Litigation", 4, "/contact/"),
    ("TX", "Thornton, Biechlin, Reynolds & Guerra, P.C.", "thorntonfirm.com", "Robert R. Biechlin", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("TX", "Cox Pradia Law Firm, P.L.L.C.", "coxpradialaw.com", "Jonathan H. Cox", "Civil Trial & Property Litigation", 4, "/contact/"),
    ("TX", "Abraham, Watkins, Nichols, Agosto, Aziz & Stogner", "abrahamwatkins.com", "Mo Aziz", "Civil Trial & Asset Recovery", 4, "/contact/"),
    ("TX", "Rusty Hardin & Associates, LLP", "rustyhardin.com", "Rusty Hardin", "Commercial Litigation & Civil Trial", 4, "/contact/"),
    ("TX", "Smyser Kaplan & Veselka, L.L.P.", "skv.com", "Craig Smyser", "Commercial Trial & Property Litigation", 4, "/contact/"),
    ("TX", "Gibbs & Bruns LLP", "gibbsbruns.com", "Robin C. Gibbs", "Complex Commercial & Real Estate Trial", 4, "/contact/"),
    ("TX", "Beck Redden LLP", "beckredden.com", "David J. Beck", "Trial & Appellate Real Estate Practice", 4, "/contact/"),
    ("TX", "Reynolds Frizzell LLP", "reynoldsfrizzell.com", "Jean Frizzell", "Commercial & Real Estate Litigation", 4, "/contact/"),
    ("TX", "Ware, Jackson, Lee, O'Neill, Smith & Barrow, LLP", "warejackson.com", "Don Jackson", "Civil Trial & Property Disputes", 4, "/contact/"),
    ("TX", "MehaffyWeber P.C.", "mehaffyweber.com", "Barbara J. Barron", "Commercial Litigation & Real Estate", 4, "/contact/"),
    ("TX", "Germer PLLC", "germer.com", "Lawrence L. Germer", "Civil Trial & Real Estate Law", 4, "/contact/"),
    ("TX", "Strong Pipkin Bissell & Ledyard, L.L.P.", "strongpipkin.com", "Michael L. Baker", "Civil Trial & Commercial Law", 4, "/contact/"),
    ("TX", "Orgain Bell & Tucker, LLP", "obt.com", "John W. Johnson", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TX", "Benckenstein & Oxford, L.L.P.", "benoxford.com", "Hubert Oxford", "Real Estate, Probate & Trial Law", 3, "/contact/"),
    ("TX", "Gagnon, Peacock & Vereeke, P.C.", "gapslegal.com", "Jack Gagnon", "Wrongful Foreclosure & Real Estate Litigation", 2, "/contact/"),
    ("TX", "The Pettit Law Firm", "pettitfirm.com", "Julie Pettit", "Foreclosure Defense & Workout Litigation", 2, "/contact/"),
    ("TX", "Roquemore Skierski PLLC", "roqski.com", "Dan Roquemore", "Commercial Real Estate & Title Litigation", 1, "/contact/"),
    ("TX", "Wilson Legal Group P.C.", "wilsonlegalgroup.com", "John Wilson", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("TX", "Cobb Martinez Woodward PLLC", "cobbmartinez.com", "William D. Cobb", "Civil Trial & Real Estate Defense", 4, "/contact/"),
    ("TX", "Godwin Bowman PC", "godwinbowman.com", "Donald E. Godwin", "Trial Practice & Real Estate Litigation", 4, "/contact/"),
    ("TX", "Stutzman, Bromberg, Esserman & Plifka, P.C.", "sbelegal.com", "Sander L. Esserman", "Insolvency, Creditors Rights & Real Estate", 1, "/contact/"),
    ("TX", "Passman & Jones, P.C.", "passmanjones.com", "Shannon S. Thomas", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Friedman & Feiger, L.L.P.", "fflawoffice.com", "Lawrence J. Friedman", "Real Estate Litigation & Trial Practice", 4, "/contact/"),
    ("TX", "Fee Smith Sharp & Vitullo LLP", "feesmith.com", "Thomas W. Fee", "Civil Litigation & Trial Defense", 4, "/contact/"),
    ("TX", "Hallett & Perrin, P.C.", "hallettperrin.com", "Leland C. de la Garza", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Farrow-Gillespie Heath Wilmoth LLP", "fghwlaw.com", "Scott Heath", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Macdonald Devin, P.C.", "macdonalddevin.com", "David M. Macdonald", "Civil Trial & Real Estate Defense", 4, "/contact/"),
    ("TX", "Vial Fotheringham LLP (TX)", "vf-law.com", "David Fotheringham", "HOA Foreclosure & Real Estate Litigation", 2, "/contact/"),
    ("TX", "Riddle & Butts, LLP", "riddlebutts.com", "Christine Butts", "Probate, Estate & Heirship Litigation", 3, "/contact/"),
    ("TX", "The Cromeens Law Firm, PLLC", "cromeenslawfirm.com", "Karalynn Cromeens", "Real Estate, Liens & Property Litigation", 1, "/contact/"),
    ("TX", "The Curley Law Firm", "thecurleylawfirm.com", "Adam Curley", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("TX", "Wright Commercial Litigation", "wrightcommerciallitigation.com", "Rick Wright", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("TX", "Silberman Law Firm, PLLC", "silblawfirm.com", "David Silberman", "Real Estate, Probate & Foreclosure Law", 2, "/contact/"),
    ("TX", "Ford+Bergner LLP", "fordbergner.com", "Don Ford", "Probate, Trust & Estate Litigation", 3, "/contact/"),
    ("TX", "Romano & Sumner, PLLC", "romanosumner.com", "Kenny Sumner", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Daughtry & Jordan, P.C.", "daughtryjordan.com", "David Jordan", "HOA Foreclosure & Real Estate Litigation", 2, "/contact/"),
    ("TX", "Roberts Markel Weinberg Butler Hailey PC", "rmwbh.com", "Marc Markel", "Real Estate, HOA & Foreclosure Litigation", 2, "/contact/"),
    ("TX", "Sears Bennett & Gerdes, LLP", "searsfirm.com", "Ross Sears", "Real Estate Litigation & Trial Law", 4, "/contact/"),
    ("TX", "Hirsch & Westheimer, P.C.", "hirschwest.com", "Eric Lipper", "Real Estate, Probate & Creditors Rights", 1, "/contact/"),
    ("TX", "BoyarMiller", "boyarmiller.com", "Chris Miller", "Real Estate Litigation & Corporate", 4, "/contact/"),
    ("TX", "Weycer, Kaplan, Pulaski & Zuber, P.C.", "wkpz.com", "Mark Kaplan", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Chamberlain, Hrdlicka, White, Williams & Aughtry (TX)", "chamberlainlaw.com", "Larry Campagna", "Tax Controversy & Real Estate Practice", 1, "/contact/"),
    ("TX", "Crain, Caton & James, P.C.", "craincaton.com", "Peter G. Nemeth", "Probate, Trust & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Feldman & Feldman, P.C.", "feldman.law", "Cris Feldman", "Real Estate & Commercial Trial Law", 4, "/contact/"),
    ("TX", "Christian Smith & Jewell, LLP", "csj-law.com", "William R. Jewell", "Commercial Litigation & Property Disputes", 4, "/contact/"),
    ("TX", "Doyle Dennis Avery LLP", "doyledennis.com", "Michael P. Doyle", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("TX", "Schiffer Hicks Johnson PLLC", "shjlawfirm.com", "Adam Schiffer", "Trial Litigation & Real Estate Disputes", 4, "/contact/"),
    ("TX", "Hicks Thomas LLP", "hicks-thomas.com", "John B. Thomas", "Commercial Litigation & Property Law", 4, "/contact/"),
    ("TX", "Ytterberg Deery Knull LLP", "ydklaw.com", "Alan Ytterberg", "Probate, Trust & Estate Administration", 3, "/contact/"),
    ("TX", "Crady Jewett McCulley & Houren LLP", "cjmhlaw.com", "Bob McCulley", "Real Estate, Probate & Tax Litigation", 3, "/contact/"),
    ("TX", " पग & Associates, PLLC / Pagel, Davis & Hill, P.C.", "pdhlaw.com", "David Pagel", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Sullins, Johnston, Rohrbach & Magers", "sjrm.com", "Robert Johnston", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Hoover Slovacek LLP", "hooverslovacek.com", "Joseph O. Slovacek", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Wheat Oppenheim PLLC", "wheatoppenheim.com", "David Wheat", "Real Estate Litigation & Foreclosure", 2, "/contact/"),
    ("TX", "The Law Office of Mike Massey", "mytxattorney.com", "Mike Massey", "Probate & Estate Administration", 3, "/contact/"),
    ("TX", "Farner & Lawson, P.C.", "farnerlawson.com", "Thomas Lawson", "Probate, Trust & Estate Planning", 3, "/contact/"),
    ("TX", "Stephens & Stephens, LLP", "stephensfirm.com", "Richard Stephens", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("TX", "The Springer Law Firm", "springer-law.com", "Sarah Springer", "Probate, Estate & Civil Litigation", 3, "/contact/"),
    ("TX", "The Pollard Firm, PLLC", "pollardfirm.com", "Brad Pollard", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Goff & Goff, PLLC", "gofflawtexas.com", "Russell Goff", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("TX", "The Gonzalez Law Group, PLLC", "gonzalezlawgroup.net", "Marco Gonzalez", "Foreclosure Defense, Real Estate & Probate", 2, "/contact/"),
    ("TX", "Baysinger & Green, PLLC", "baysingergreen.com", "Kyle Baysinger", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TX", "The Law Office of Bryan Fagan, PLLC", "bryanfagan.com", "Bryan Fagan", "Estate Planning, Probate & Asset Division", 3, "/contact/"),
    ("TX", "Hayes & Wilson, PLLC", "hayeswilsonlaw.com", "Bill Hayes", "Probate, Estate & Guardianship Litigation", 3, "/contact/"),
    ("TX", "Frazier & Frazier", "frazierlaw.com", "Robert Frazier", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Cenatiempo & Douthit, PLLC", "cdlawtx.com", "Michael Cenatiempo", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("TX", "The Strong Firm P.C.", "thestrongfirm.com", "Bret L. Strong", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Daughtry & Farine, P.C.", "daughtryfarine.com", "David Farine", "HOA Foreclosure & Real Estate Law", 2, "/contact/"),
    ("TX", "The Jurek Law Group, PLLC", "jureklaw.com", "Michael Jurek", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Fizer, Beck, Webster, Bentley & Scroggins, a professional corporation", "fizerbeck.com", "David Beck", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("TX", "MacIntyre, McCulloch & Stanfield, L.L.P.", "mmslawhouston.com", "John Stanfield", "Probate, Estate & Trust Law", 3, "/contact/"),
    ("TX", "Burdette & Rice, PLLC", "dallasprobateattorneys.com", "Brian Rice", "Probate, Estate & Trust Litigation", 3, "/contact/"),
    ("TX", "Pyke & Associates, P.C.", "pyke-associates.com", "David Pyke", "Probate & Estate Administration", 3, "/contact/"),
    ("TX", "Albin Oldner Law, PLLC", "albinoldnerlaw.com", "Mark Albin", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "Schaefer Law Firm, P.C.", "schaeferfirm.com", "David Schaefer", "Real Estate Litigation & Title Disputes", 1, "/contact/"),
    ("TX", "The Farah Law Firm, P.C.", "farahlawfirm.com", "Nabil Farah", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("TX", "The Ashmore Law Firm, P.C.", "ashmorelaw.com", "Gary Ashmore", "Probate, Estate & Civil Litigation", 3, "/contact/"),
    ("TX", "Moses, Palmer & Howell, L.L.P.", "mph-law.com", "Tim Howell", "Real Estate Litigation & Land Title", 1, "/contact/"),
    ("TX", "Harris, Finley & Bogle, P.C.", "hfblaw.com", "Dee Finley", "Real Estate Litigation & Banking", 1, "/contact/"),
    ("TX", "Bourland, Wall & Wenzel, P.C.", "bwwlaw.com", "Michael V. Bourland", "Probate, Estate, Tax & Real Estate", 3, "/contact/"),
    ("TX", "Shannon, Gracey, Ratliff & Miller, L.L.P.", "shannongracey.com", "Richard Montgomery", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Barlow Garsek & Pou, LLP", "bgp-law.com", "David Pou", "Real Estate, Banking & Litigation", 1, "/contact/"),
    ("TX", "Whitaker Chalk Swindle & Schwartz PLLC", "whitakerchalk.com", "Robert Schwartz", "Real Estate, Probate & Litigation", 3, "/contact/"),
    ("TX", "KoonsFuller, P.C.", "koonsfuller.com", "Ike Vanden Eykel", "Complex Property Division & Trial Practice", 3, "/contact/"),
    ("TX", "Linebarger Goggan Blair & Sampson, LLP (Defense Counsel Track)", "lgbs.com", "Mark C. Ticer", "Tax Litigation & Public Law", 1, "/contact/"),
    ("TX", "Perdue Brandon Fielder Collins & Mott, LLP (Special Counsel)", "pbfcm.com", "Mike Fielder", "Delinquent Tax Proceedings & Litigation", 1, "/contact/"),
    ("TX", "Law Offices of Mark C. Ticer", "ticerlaw.com", "Mark Ticer", "Civil Litigation & Trial Law", 4, "/contact/"),
    ("TX", "Mullin Hoard & Brown, L.L.P. (Dallas)", "mhba.com", "Steve Hoard", "Banking & Creditors Rights", 1, "/contact/"),
    ("TX", "Sloan, Bagwell, Donaldson and Hilbun, PLLC", "sloanfirm.com", "John Sloan", "Trial Practice & Civil Recovery", 4, "/contact/"),
    ("TX", "Martin, Disiere, Jefferson & Wisdom, L.L.P.", "mdjwlaw.com", "Chris Martin", "Civil Litigation & Property Defense", 4, "/contact/"),
    ("TX", "Segal McCambridge Singer & Mahoney (TX)", "smsm.com", "Gregory O. Gheen", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Galloway, Johnson, Tompkins, Burr & Smith (TX)", "gallowaylawfirm.com", "Jason P. Waguespack", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("TX", "Cokinos Young (Dallas)", "cokinoslaw.com", "Craig E. Power", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Platt Cheema Richmond PLLC", "pcrfirm.com", "Bobby Richmond", "Real Estate Litigation & Transactions", 1, "/contact/"),
    ("TX", "Scheef & Stone LLP (Frisco)", "solidcounsel.com", "Shawn Stone", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Vance, Theriot & Vance", "vancetheriot.com", "David Vance", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TX", "Kessler & Collins, P.C.", "kesslercollins.com", "Gary Kessler", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Shields Legal Group", "shieldslegal.com", "James Shields", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("TX", "Chamblee Ryan, P.C.", "chambleeryan.com", "William H. Chamblee", "Civil Trial & Real Estate Defense", 4, "/contact/"),
    ("TX", "Gillespie Sanford LLP", "gillespiesanford.com", "Ken Sanford", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Barrows Firm, P.C.", "barrowsfirm.com", "Leslie Barrows", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Shead & Associates, P.C.", "sheadlaw.com", "David Shead", "Foreclosure Defense & Real Estate Litigation", 2, "/contact/"),
    ("TX", "The Gonzalez Law Firm, P.C.", "gonzalezlawtx.com", "Al Gonzalez", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Tittle Law Group, PLLC", "tittlelawgroup.com", "Jason Tittle", "Real Estate Litigation & Title Law", 1, "/contact/"),
    ("TX", "The Corbin Law Firm", "corbinlawfirm.com", "David Corbin", "Real Estate & Commercial Litigation", 4, "/contact/"),
    ("TX", "The Minor Law Firm", "minorlawtx.com", "Brett Minor", "Real Estate, Probate & Foreclosure", 2, "/contact/"),
    ("TX", "Ramos & Del Cueto, PLLC", "rdclaw.com", "Paul Del Cueto", "Civil Trial & Property Defense", 4, "/contact/"),
    ("TX", "Barton, East & Caldwell, P.L.L.C.", "beclaw.com", "David Barton", "Real Estate Litigation & Title Clearance", 1, "/contact/"),
    ("TX", "Tinsman & Sciano, Inc.", "tinsmanlaw.com", "Daniel Sciano", "Civil Trial Practice & Asset Recovery", 4, "/contact/"),
    ("TX", "Katzman & Katzman, P.C. (TX)", "katzmanlaw.com", "Howard Katzman", "Real Estate Litigation & Foreclosure", 2, "/contact/"),
    ("TX", "The Nacol Law Firm P.C.", "nacollawfirm.com", "Mark Nacol", "Real Estate Litigation & Probate Disputes", 3, "/contact/"),
    ("TX", "The Chenault Law Firm", "chenaultlawfirm.com", "Jill Chenault", "Probate, Estate & Real Estate Litigation", 3, "/contact/"),
    ("TX", "Saunders, Walsh & Beard", "saunderswalsh.com", "Mark Walsh", "Real Estate & Construction Litigation", 4, "/contact/"),
    ("TX", "Hendershot Cowart P.C.", "hchlawyers.com", "Trey Hendershot", "Real Estate Litigation & Commercial Trial", 4, "/contact/"),
    ("TX", "Wright Firm, LLP", "thewrightlawyers.com", "Paul Wright", "Real Estate, Probate & Family Asset Recovery", 3, "/contact/"),
    ("TX", "The Cromeens Law Firm (Dallas)", "cromeenslawfirm.com", "Karalynn Cromeens", "Real Estate, Liens & Quiet Title", 1, "/contact/"),
    ("TX", "Sandoz & Sandoz, PLLC", "sandozlaw.com", "David Sandoz", "Real Estate & Foreclosure Defense", 2, "/contact/"),
    ("TX", "Leavitt & Eldredge Law Firm", "leavitteldredge.com", "Richard Leavitt", "Civil Litigation & Commercial Property", 4, "/contact/"),
    ("TX", "Kushner Law Firm, PLLC", "kushnerlaw.com", "David Kushner", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("TX", "The Weaver Law Firm (San Antonio)", "weaverlawyers.com", "Richard Weaver", "Real Estate Litigation & Foreclosure Defense", 2, "/contact/"),
    ("TX", "The Morales Firm, P.C.", "moralesfirm.com", "Jesse Morales", "Real Estate Litigation & Probate", 3, "/contact/"),
    ("TX", "The Law Office of David S. Kohm", "kohm.com", "David S. Kohm", "Foreclosure Defense, Bankruptcy & Real Estate", 2, "/contact/"),
    ("TX", "Toronjo & Prosser Law", "dallasbankruptcylaw.com", "Joshua Toronjo", "Foreclosure Defense & Distressed Assets", 2, "/contact/"),
    ("TX", "Bailey & Galyen Attorneys at Law", "galyen.com", "Phillip Galyen", "Foreclosure Defense, Probate & Real Estate", 2, "/contact/"),
    ("TX", "Allmand Law Firm, PLLC", "allmandlaw.com", "Reed Allmand", "Foreclosure Defense & Asset Protection", 2, "/contact/"),
    ("TX", "Rubin & Associates, PC", "rubinlawfirm.com", "Ron Rubin", "Foreclosure Defense & Debt Relief", 2, "/contact/"),
    ("TX", "Leinart Law Firm", "leinartlaw.com", "Marcus Leinart", "Foreclosure Defense & Distressed Real Estate", 2, "/contact/"),
    ("TX", "Acker Warren, P.C.", "ackerwarren.com", "Sean Acker", "Foreclosure Defense & Debt Litigation", 2, "/contact/"),
    ("TX", "The Wright Law Firm", "thewrightfirm.com", "David Wright", "Real Estate, Foreclosure & Probate", 2, "/contact/"),
    ("TX", "Fears Nachawati Law Firm", "fnlawfirm.com", "Bryan Fears", "Commercial Litigation & Property Rights", 4, "/contact/"),
    ("TX", "The Law Offices of Eric L. Davis", "ericdavislaw.com", "Eric Davis", "Civil Trial & Real Estate Practice", 4, "/contact/"),
    ("TX", "Sethi & Mazaheri LLC (TX)", "sethi-mazaheri.com", "Reza Mazaheri", "Real Estate & Commercial Law", 4, "/contact/"),
    ("TX", "Goff & Goff, PLLC (San Antonio)", "gofflawtexas.com", "Russell Goff", "Real Estate, Title & Foreclosure", 2, "/contact/"),
    ("TX", "Barton, East & Caldwell, P.L.L.C. (San Antonio)", "beclaw.com", "David Barton", "Real Estate Litigation & Creditors Rights", 1, "/contact/"),
    ("TX", "Langley & Banack, Inc. (Kerrville)", "langleybanack.com", "Arthur Banack", "Real Estate, Probate & Title Law", 3, "/contact/"),
    ("TX", "Brock & Scott, PLLC (TX)", "brockandscott.com", "Thomas Brock", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("TX", "Bonial & Associates, P.C.", "bonialpc.com", "Paul Bonial", "Foreclosure, Bankruptcy & Real Estate", 1, "/contact/"),
    ("TX", "Barrett Daffin Frappier Turner & Engel, LLP", "bdfgroup.com", "Michael Barrett", "Foreclosure, Creditors Rights & Title", 1, "/contact/"),
    ("TX", "Mackie Wolf Zientz & Mann, P.C.", "mwzmlaw.com", "Keller Mackie", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("TX", "Hughes, Watters & Askanase, L.L.P.", "hwa.com", "Wayne Kitchens", "Foreclosure, Creditors Rights & Real Estate", 1, "/contact/"),
    ("TX", "Robertson, Anschutz, Schneid, Crane & Partners, PLLC (TX)", "rasflaw.com", "Robert Anschutz", "Foreclosure & Creditors Rights", 1, "/contact/"),
    ("TX", "Marinosci Law Group, P.C. (TX)", "mlg-defaultlaw.com", "Gary Marinosci", "Foreclosure, Title & Creditors Rights", 1, "/contact/"),
    ("TX", "Padgett Law Group (TX)", "padgettlawgroup.com", "David Padgett", "Foreclosure & Real Estate Litigation", 1, "/contact/"),
    ("TX", "Aldridge Pite, LLP (TX)", "aldridgepite.com", "John Aldridge", "Foreclosure & Real Estate Practice", 1, "/contact/"),
]

print(f"Loaded {len(CANDIDATES)} Texas candidate practices.")
