#!/usr/bin/env python3
"""
Surplus Docket — Astra (GPT-4o) Targeted System & Code Audit
============================================================
Performs a token-optimized, high-conviction audit of:
1. Morning feed email dispatch reliability and idempotency guards.
2. Zero false claims compliance (12-month history removal, site parity).
3. Statutory rules, fee calculations, and CRM export integrity.

Designed to minimize API fees (strictly token-capped).
"""

import os
import sys
import json
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_FILE = BASE_DIR / "output" / "astra_code_and_system_audit.md"
LEDGER_FILE = BASE_DIR / "data" / "ai_usage_ledger.json"

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
MODEL = os.environ.get("ASTRA_MODEL", "gpt-4o")

SYSTEM_PROMPT = """You are Astra, Principal LegalTech Architect, Security Engineer, and Lead Code Auditor for Surplus Docket (https://surplusdocket.com).
Your review must be rigorous, concise, and focused on:
1. Code soundness & production readiness.
2. 100% truth in advertising / zero false claims (ensuring zero refund risk from attorneys).
3. Autonomous reliability: ensuring the daily 7:00 AM EST morning court intelligence feed dispatches without silent failures or duplicate spam.
Be direct, point out any lurking edge cases or potential failure modes, and give specific code/config recommendations."""

USER_PROMPT = """Review the current Surplus Docket revenue engine backend and website architecture:

### 1. Delivery & Dispatch Pipeline (`portal/dispatch_morning_feed.py` & `.github/workflows/dispatch_morning_feed.yml`):
- Schedule: Dual cron in GitHub Actions (`0 11 * * 1-5` for EDT summer, `0 12 * * 1-5` for EST winter) + backup workflow offset at `:15`.
- Idempotency Guard: Checks `portal/daily_dispatch_log.json` for `last_dispatched_date == date_key` with status `SUCCESS`. Skips duplicate sends on the same calendar day unless `--force` is passed.
- Credentials: SMTP via Gmail App Password (`GMAIL_APP_PASS` secret) with `From: Surplus Docket Intelligence <dockets@surplusdocket.com>`, `Reply-To: dockets@surplusdocket.com`.
- Subscriber List: `portal/subscribers.json` with active subscriber `david@surplusdocket.com`.
- Attachments: `Master_Surplus_Lead_Feed.csv` and `Master_Surplus_Lead_Feed.xlsx` generated by `portal/feed_generator.py`.
- Identified Prior Issue: `daily_dispatch_log.json` was previously committed to git with today's date during testing, which caused the idempotency check to skip sending today. For tomorrow (`2026-10-01`), the date key will be fresh.

### 2. Zero False Claims & Website Parity Audit:
- 12-Month Business Claims: Removed all references to "700+ actionable dockets annually" or "50-80 dockets/mo over 12 months" since the business has not been operating 12 months. Replaced with forward-looking daily ingestion capacity.
- FAQ Generalization: Removed hyper-specific single-county email questions (e.g., "Does Surplus Docket cover Broward County..."). Generalized to universal practitioner inquiries across `site/index.html` and `site/florida-tax-deed-surplus.html` and their Schema.org `FAQPage` JSON-LD.
- Schema Parity: Fixed field mismatch (`Entity_Classification` -> `Entity_Type` matching `enrichment/processor.py`).
- Timing Parity: Eliminated legacy "Priority 6:00 AM" claims across all pages, standardizing to 7:00 AM EST Mon-Fri.
- Trial Scope: Fixed `refund-policy.html` to clarify the 7-day trial covers Tri-State Core (FL, TX, GA, $249/mo), not all 6 states.
- Statutory Accuracy: Verified Fla. Stat. § 197.582 (120 days from notice) and Fla. Stat. § 45.032 (60 days from disbursement).

### 3. Verification & Test Suite:
- 304 unit tests passing in `tests/`.
- `compliance/verify_all_publications.py` pre-publication audit passes with 0 discrepancies (100% deterministic math, zero banned hype phrases, 100% Stripe checkout URL integrity).

Please provide your technical evaluation:
1. Is the email dispatch and idempotency logic solid? What edge cases could cause tomorrow's 7:00 AM dispatch to fail or delay?
2. Are the website claims, pricing tiers, and statutory statements legally sound and defensible against refund disputes?
3. What are the top 2-3 technical recommendations to make the codebase even more resilient?
"""

def main():
    if not OPENAI_API_KEY:
        print("[!] ERROR: OPENAI_API_KEY is not set.")
        sys.exit(1)

    print(f"[*] Consulting Astra ({MODEL}) with token-capped prompt to minimize API fees...")
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": USER_PROMPT}
        ],
        "temperature": 0.2,
        "max_tokens": 1500
    }

    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json"
        }
    )

    try:
        with urllib.request.urlopen(req, timeout=90) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            content = res_data["choices"][0]["message"]["content"]
            usage = res_data.get("usage", {})
            prompt_tokens = usage.get("prompt_tokens", 0)
            completion_tokens = usage.get("completion_tokens", 0)
            total_tokens = usage.get("total_tokens", 0)
            
            # Approximate cost for gpt-4o ($2.50/M input, $10.00/M output) or gpt-4o-mini
            if "mini" in MODEL:
                est_cost = (prompt_tokens * 0.15 + completion_tokens * 0.60) / 1_000_000
            else:
                est_cost = (prompt_tokens * 2.50 + completion_tokens * 10.00) / 1_000_000

            print(f"[✓] Received response from Astra.")
            print(f"    • Prompt Tokens:     {prompt_tokens}")
            print(f"    • Completion Tokens: {completion_tokens}")
            print(f"    • Total Tokens:      {total_tokens}")
            print(f"    • Estimated API Fee: ${est_cost:.4f} USD")

            OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
            OUTPUT_FILE.write_text(content, encoding="utf-8")
            print(f"[✓] Audit report saved to: {OUTPUT_FILE}")

            # Record in usage ledger
            if LEDGER_FILE.exists():
                try:
                    ledger = json.loads(LEDGER_FILE.read_text(encoding="utf-8"))
                    ledger.append({
                        "timestamp": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                        "provider": "openai",
                        "model": MODEL,
                        "task_type": "astra_code_and_system_audit",
                        "input_tokens": prompt_tokens,
                        "output_tokens": completion_tokens,
                        "audio_seconds": 0,
                        "estimated_cost_usd": round(est_cost, 5),
                        "status": "success"
                    })
                    LEDGER_FILE.write_text(json.dumps(ledger, indent=2), encoding="utf-8")
                    print(f"[✓] Logged entry to {LEDGER_FILE.name}")
                except Exception as le:
                    print(f"Notice updating ledger: {le}")

            print("\n" + "=" * 60)
            print(content)
            print("=" * 60)
            return 0
    except Exception as e:
        print(f"[!] Error querying Astra: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
